const en = {
  // nav
  'nav.dashboard': 'Dashboard',
  'nav.income': 'Income',
  'nav.expenses': 'Expenses',
  'nav.salaries': 'Salaries',
  'nav.reports': 'Reports',
  'nav.report': 'Report',
  'nav.admins': 'Staff',
  'nav.finance': 'Finance',
  'nav.analytics': 'Analytics',
  'nav.stats': 'Statistics',
  'nav.tax': 'Taxes',
  'nav.taxNdss': 'VAT 20%',
  'nav.taxSocNalog': 'Social Tax 10%',
  'nav.taxOtzyvnoyNalog': 'Turnover Tax 1.5%',
  'nav.taxTotal': 'Total Taxes',
  'nav.taxOrg': 'Organization',
  'nav.allStudents': 'All students',
  'nav.allGroups': 'All groups',
  'nav.attendance': 'Attendance',
  'nav.more': 'More',
  'nav.discipline': 'Discipline',
  'nav.announcements': 'Announcements',
  'nav.reminders': 'Reminders',
  'nav.audit': 'Audit',
  'nav.features': 'Features',
  'nav.billing': 'Billing',
  'nav.methodics': 'Methodics',
  'nav.shopCatalog': 'Shop Catalog',
  'nav.settings': 'Settings',
  'nav.students': 'Students',
  'nav.groups': 'Groups',
  'nav.mentors': 'Mentors',
  'nav.chat': 'Chat',
  'nav.payments': 'Payments',
  'nav.branch': 'Branch',
  'nav.branches': 'Branches',
  'nav.allBranches': 'All branches',
  'nav.noBranches': 'No branches',
  'nav.noGroups': 'No groups',
  'nav.methodistTypes': 'Training types',
  'nav.people': 'People & clients',
  'nav.clientBase': 'Client base',
  'nav.myStudents': 'My students',
  'nav.participantBase': 'Participant base',
  'nav.schedule': 'Schedule',
  'nav.main': 'main',
  'nav.collapse': 'Collapse',
  'nav.pin': 'Pin',
  'nav.collapsePanel': 'Collapse panel',
  'nav.pinPanel': 'Pin panel',

  // common
  'common.total': 'Total',
  'common.amount': 'Amount',
  'common.search': 'Search...',
  'common.profile': 'Profile',
  'common.logout': 'Logout',
  'common.myProfile': 'My profile',
  'common.exit': 'Exit',
  'common.branch': 'Branch',
  'common.allBranches': 'All branches',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.date': 'Date',
  'common.time': 'Time',
  'common.phone': 'Phone',
  'common.email': 'Email',
  'common.name': 'Name',
  'common.fullName': 'Full Name',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.create': 'Create',
  'common.details': 'Details',
  'common.view': 'View',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.loading': 'Loading...',
  'common.error': 'An error occurred',
  'common.success': 'Success',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.frozen': 'Frozen',
  'common.archived': 'Archived',
  'common.export': 'Export',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.empty': 'No data found',
  'common.reload': 'Reload',
  'common.month': 'Month',
  'common.period': 'Period',
  'common.notes': 'Notes',
  'common.description': 'Description',
  'common.accountMenu': 'Account menu',
  'common.yesterday': 'Yesterday',

  // roles
  'role.seo': 'SEO (Head)',
  'role.admin': 'Administrator',
  'role.branch_manager': 'Branch Manager',
  'role.finance_manager': 'Finance Manager',
  'role.mentor': 'Mentor',
  'role.methodist': 'Methodist',
  'role.student': 'Student',
  'role.parent': 'Parent',
  'role.employee': 'Employee',

  // notifications
  'notifications.title': 'Notifications',
  'notifications.empty': 'No new notifications',
  'notifications.emptyDesc': 'Unread messages will appear here.',
  'notifications.new': 'new',
  'notifications.allMessages': 'All messages',
  'notifications.newMessage': 'New message',
  'notifications.soundOn': 'Sound enabled',
  'notifications.soundOff': 'Sound muted',
  'notifications.muteSound': 'Mute sound',
  'notifications.unmuteSound': 'Unmute sound',

  // kpi & dashboard
  'kpi.income': 'Monthly income',
  'kpi.expenses': 'Monthly expenses',
  'kpi.salaries': 'Monthly salaries',
  'kpi.profit': 'Net profit',
  'kpi.netProfit': 'Net profit',
  'kpi.orgIncome': 'Org income',
  'kpi.orgExpenses': 'Org expenses',
  'kpi.orgProfit': 'Org profit',
  'kpi.students': 'Total students',
  'kpi.groups': 'Total groups',
  'kpi.mentors': 'Total mentors',
  'kpi.debt': 'Outstanding debt',
  'kpi.attendance': 'Attendance rate',

  // dashboard details
  'dash.branchStats': 'Branch Metrics',
  'dash.activeStudents': 'Active Students',
  'dash.groups': 'Groups',
  'dash.overdueInvoices': 'Overdue Invoices',
  'dash.recentPayments': 'Recent Payments',
  'dash.noPayments': 'No payments yet',
  'dash.student': 'Student',
  'dash.reminders': 'Reminders',
  'dash.overduePaymentsTitle': 'Overdue Payments',
  'dash.overduePaymentsDesc': 'Currently {{count}} invoices are overdue. Monitor payments.',
  'dash.activeStudentsTitle': 'Active Students',
  'dash.activeStudentsDesc': '{{count}} active students are studying at the branch.',
  'dash.thisMonth': 'This Month',
  'dash.income': 'Income',
  'dash.expenses': 'Expenses',
  'dash.profit': 'Profit',
  'dash.loadError': 'Loading error',
  'dash.title': 'Dashboard',
  'dash.welcome': 'Welcome',
  'dash.bmSubtitle': 'branch general overview',
  'dash.incomeThisMonth': 'Income this month',
  'dash.expensesThisMonth': 'Expenses this month',
  'dash.debtDesc': 'overdue payments',
  'dash.profitFormula': 'income − expenses',
  'dash.vsPrevMonth': 'compared to last month',
  'dash.mainBranch': 'Main branch',
  'dash.addressNotSet': 'Address not specified',
  'dash.phoneNotSet': 'Phone not specified',
  'dash.workHoursNotSet': 'Working hours not specified',
  'dash.staff': 'Staff',
  'dash.recentBranchPayments': 'Recent Payments',
  'dash.noPaymentsYet': 'No payments yet',
  'dash.last6Months': 'Last 6 months: income vs expenses',

  // branch details
  'branch.about': 'About branch',
  'branch.locationStats': 'location & statistics',
  'branch.contacts': 'Contacts',
  'branch.address': 'Address',
  'branch.phone': 'Phone',
  'branch.financeTotal': 'Finance (total)',
  'branch.tgCardTitle': 'Parent group (Telegram)',
  'branch.tgConnected': 'Group connected',
  'branch.tgDisconnect': 'Disconnect',
  'branch.tgDesc': 'Attendance and performance updates will automatically be sent to this group. First add the bot to the group, then generate the connection code.',
  'branch.tgGetCode': 'Get connection code',
  'branch.tgStep1': 'Add bot to group',
  'branch.tgStep2': 'Send the following command in the group',
  'branch.tgCodeValid': 'Code is valid for {{min}} minutes.',
  'branch.notFound': 'Branch data not found',
  'branch.unlinkConfirm': 'Are you sure you want to disconnect the group?',

  // tax
  'tax.title': 'Tax Report',
  'tax.subtitle': 'Tax calculations by branch and organization',
  'tax.export': 'Export CSV',
  'tax.due': 'Total tax due',
  'tax.tableTitle': 'Branch tax overview',
  'tax.netProfit': 'Net profit',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Select language',

  // ---------- finance-manager panel (formerly pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Dashboard',
  'finance.nav.income': 'Income',
  'finance.nav.expenses': 'Expenses',
  'finance.nav.salaries': 'Salaries',
  'finance.nav.reports': 'Reports',
  'finance.nav.report': 'Report',
  'finance.nav.admins': 'Staff',
  'finance.nav.finance': 'Finance',
  'finance.nav.analytics': 'Analytics',
  'finance.nav.stats': 'Statistics',
  'finance.nav.tax': 'Taxes',
  'finance.nav.taxTitle': 'Tax Report',
  'finance.nav.taxNdss': 'VAT 20%',
  'finance.nav.taxSocNalog': 'Social tax 10%',
  'finance.nav.taxOtzyvnoyNalog': 'Profit tax 1.5%',
  'finance.nav.taxTotal': 'Total',
  'finance.nav.taxOrg': 'Organization',
  'finance.nav.allStudents': 'All students',
  'finance.nav.allGroups': 'All groups',
  'finance.nav.attendance': 'Attendance',
  'finance.nav.more': 'More',
  'finance.nav.discipline': 'Discipline',
  'finance.nav.announcements': 'Announcements',
  'finance.nav.reminders': 'Reminders',
  'finance.nav.audit': 'Audit',
  'finance.nav.settings': 'Settings',
  'finance.nav.students': 'Students',
  'finance.nav.groups': 'Groups',
  'finance.nav.mentors': 'Mentors',
  'finance.nav.chat': 'Chat',
  'finance.nav.payments': 'Payments',
  'finance.nav.branch': 'Branch',
  'finance.nav.branches': 'Branches',
  'finance.nav.allBranches': 'All branches',
  'finance.nav.noBranches': 'No branches',
  'finance.nav.noGroups': 'No groups',
  'finance.nav.methodistTypes': 'Training types',
  'finance.nav.main': 'main',
  'finance.nav.collapse': 'Collapse',
  'finance.nav.pin': 'Pin',
  'finance.nav.collapsePanel': 'Collapse panel',
  'finance.nav.pinPanel': 'Pin panel',

  'finance.kpi.income': 'Monthly income',
  'finance.kpi.expenses': 'Monthly expenses',
  'finance.kpi.salaries': 'Monthly payroll',
  'finance.kpi.netProfit': 'Net profit',
  'finance.kpi.orgIncome': 'Org income',
  'finance.kpi.orgExpenses': 'Org expenses',
  'finance.kpi.orgProfit': 'Org profit',

  'finance.common.total': 'Total',
  'finance.common.share': 'Share',
  'finance.common.amount': 'Amount',
  'finance.common.date': 'Date',
  'finance.common.status': 'Status',
  'finance.common.method': 'Method',
  'finance.common.note': 'Note',
  'finance.common.category': 'Category',
  'finance.common.employee': 'Employee',
  'finance.common.position': 'Position',
  'finance.common.branch': 'Branch',
  'finance.common.allBranches': 'All branches',
  'finance.common.month': 'Month',
  'finance.common.period': 'Period',
  'finance.common.vsPrev': 'vs previous month',
  'finance.common.noData': 'No data',
  'finance.common.students': 'Students',
  'finance.common.groups': 'Groups',
  'finance.common.staff': 'Staff',
  'finance.common.loading': 'Loading…',
  'finance.common.page': 'Page',
  'finance.common.save': 'Save',
  'finance.common.cancel': 'Cancel',
  'finance.common.add': 'Add',
  'finance.common.edit': 'Edit',
  'finance.common.delete': 'Delete',
  'finance.common.confirmDelete': 'Delete this record?',

  'finance.dash.title': 'Finance dashboard',
  'finance.dash.subtitle': 'Whole org · by branch and month',
  'finance.dash.trendChart': 'Org income and expenses',
  'finance.dash.profitLine': 'Profit',
  'finance.dash.branchShare': 'Branch share of income',
  'finance.dash.monthlyProfit': 'Net profit for 6 months',
  'finance.dash.viewReports': 'Detailed report',
  'finance.dash.days30Org': 'Last 30 days · whole org',
  'finance.dash.chartSub': 'Actual receipts over 30 days',
  'finance.dash.branches': 'Branches',

  'finance.income.title': 'Income',
  'finance.income.subtitle': 'Payments by branch and month',
  'finance.income.tableTitle': 'Payments',
  'finance.income.student': 'Student',
  'finance.income.group': 'Group',

  'finance.expenses.title': 'Expenses',
  'finance.expenses.subtitle': 'Expenses by branch and category',
  'finance.expenses.catBreakdown': 'By category',
  'finance.expenses.add': 'New expense',
  'finance.expenses.edit': 'Edit expense',
  'finance.expenses.orgWide': 'Whole organization',
  'finance.expenses.categoryPlaceholder': 'E.g. Rent',

  'finance.salaries.title': 'Salaries',
  'finance.salaries.subtitle': 'Payroll by branch',
  'finance.salaries.payroll': 'Monthly payroll',
  'finance.salaries.sheetTitle': 'Payroll sheet',

  'finance.reports.title': 'Reports',
  'finance.reports.subtitle': 'Monthly summary by branch',
  'finance.reports.org': 'Organization',
  'finance.reports.cashFlow': 'Cash flow',
  'finance.reports.branchTable': 'Branches · summary',
  'finance.reports.branchNet': 'Branch net',
  'finance.reports.branchDetail': 'Branch detail',
  'finance.reports.net': 'Net profit',
  'finance.reports.opProfit': 'Operating profit',
  'finance.reports.vsPrevMonth': 'vs previous month',
  'finance.reports.export': 'Export CSV',
  'finance.reports.paymentsThisMonth': 'Payments · this month',
  'finance.reports.byStatus': 'By payment status',
  'finance.reports.byMethod': 'By payment method',
  'finance.reports.overdueAmount': 'Overdue',
  'finance.reports.expensesByCategory': 'Expenses by category',
  'finance.reports.subtitleLive': 'Live backend data · last 30 days',
  'finance.reports.incomeLabel': 'Revenue over 30 days',
  'finance.reports.activeStudents': 'Active students',
  'finance.reports.last30days': 'Last 30 days',
  'finance.reports.debtLabel': 'Debt',
  'finance.reports.incomeDebtByBranch': 'Revenue and debt by branch',
  'finance.reports.methodsSubtitle': 'Completed transactions',
  'finance.reports.noCompletedPayments': 'No completed payments',
  'finance.reports.orgRow': 'ORGANIZATION',
  'finance.method.cash': 'Cash',
  'finance.method.card': 'Card',
  'finance.method.transfer': 'Transfer',
  'finance.method.bankTransfer': 'Bank transfer',
  'finance.salaryStatus.draft': 'Draft',
  'finance.salaryStatus.approved': 'Approved',
  'finance.salaryStatus.paid': 'Paid',

  'finance.settings.title': 'Settings',
  'finance.settings.subtitle': 'Profile and preferences',
  'finance.settings.personal': 'Personal info',
  'finance.settings.personalSub': 'These details are shown in the system and saved to your profile',
  'finance.settings.firstName': 'First name',
  'finance.settings.lastName': 'Last name',
  'finance.settings.phone': 'Phone',
  'finance.settings.city': 'City',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Save',
  'finance.settings.saved': 'Settings saved',
  'finance.settings.lang': 'Interface language',
  'finance.settings.langSub': 'Applied instantly across the whole panel',
  'finance.settings.security': 'Security',
  'finance.settings.securitySub': 'Password change and account details are managed via the main account',
};

export default en;
