const en = {
  // nav
  'nav.dashboard': 'Dashboard',
  'nav.income': 'Income',
  'nav.expenses': 'Expenses',
  'nav.salaries': 'Salaries',
  'nav.reports': 'Reports',
  'nav.report': 'Report',
  'nav.admins': 'Staff',
  'nav.finance': 'Finance',
  'nav.analytics': 'Analytics',
  'nav.stats': 'Statistics',
  'nav.tax': 'Taxes',
  'nav.taxNdss': 'VAT 20%',
  'nav.taxSocNalog': 'Social Tax 10%',
  'nav.taxOtzyvnoyNalog': 'Turnover Tax 1.5%',
  'nav.taxTotal': 'Total Taxes',
  'nav.taxOrg': 'Organization',
  'nav.allStudents': 'All students',
  'nav.allGroups': 'All groups',
  'nav.attendance': 'Attendance',
  'nav.more': 'More',
  'nav.discipline': 'Discipline',
  'nav.announcements': 'Announcements',
  'nav.reminders': 'Reminders',
  'nav.audit': 'Audit',
  'nav.features': 'Features',
  'nav.billing': 'Billing',
  'nav.methodics': 'Methodics',
  'nav.shopCatalog': 'Shop Catalog',
  'nav.settings': 'Settings',
  'nav.students': 'Students',
  'nav.groups': 'Groups',
  'nav.mentors': 'Mentors',
  'nav.chat': 'Chat',
  'nav.payments': 'Payments',
  'nav.branch': 'Branch',
  'nav.branches': 'Branches',
  'nav.allBranches': 'All branches',
  'nav.noBranches': 'No branches',
  'nav.noGroups': 'No groups',
  'nav.methodistTypes': 'Training types',
  'nav.people': 'People & clients',
  'nav.clientBase': 'Client base',
  'nav.myStudents': 'My students',
  'nav.participantBase': 'Participant base',
  'nav.schedule': 'Schedule',
  'nav.main': 'main',
  'nav.collapse': 'Collapse',
  'nav.pin': 'Pin',
  'nav.collapsePanel': 'Collapse panel',
  'nav.pinPanel': 'Pin panel',

  // common
  'common.total': 'Total',
  'common.amount': 'Amount',
  'common.search': 'Search...',
  'common.profile': 'Profile',
  'common.logout': 'Logout',
  'common.myProfile': 'My profile',
  'common.exit': 'Exit',
  'common.branch': 'Branch',
  'common.allBranches': 'All branches',
  'common.status': 'Status',
  'common.actions': 'Actions',
  'common.date': 'Date',
  'common.time': 'Time',
  'common.phone': 'Phone',
  'common.email': 'Email',
  'common.name': 'Name',
  'common.fullName': 'Full Name',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.create': 'Create',
  'common.details': 'Details',
  'common.view': 'View',
  'common.back': 'Back',
  'common.next': 'Next',
  'common.loading': 'Loading...',
  'common.error': 'An error occurred',
  'common.success': 'Success',
  'common.filter': 'Filter',
  'common.all': 'All',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.frozen': 'Frozen',
  'common.archived': 'Archived',
  'common.export': 'Export',
  'common.download': 'Download',
  'common.upload': 'Upload',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.empty': 'No data found',
  'common.reload': 'Reload',
  'common.month': 'Month',
  'common.period': 'Period',
  'common.notes': 'Notes',
  'common.description': 'Description',
  'common.accountMenu': 'Account menu',
  'common.yesterday': 'Yesterday',

  // mentor/*
  'mentor.noGroupsTitle': 'You don’t have any groups yet',
  'mentor.noGroupsHint': 'Once a group is assigned, it will appear in the list on the left.',
  'mentor.groupNotFoundTitle': 'Group not found',
  'mentor.groupNotFoundHint': 'It may be archived or removed.',
  'mentor.toHome': 'Go home',
  'mentor.back': 'Back',
  'mentor.archived': 'Archived',
  'mentor.direction': 'Direction',
  'mentor.subject': 'Subject',
  'mentor.lessonTime': 'Lesson time',
  'mentor.students': 'Students',
  'mentor.totalCoins': 'Total coins',
  'mentor.groupSections': 'Group sections',
  'mentor.tab.attendance': 'Attendance',
  'mentor.tab.tests': 'Tests',
  'mentor.tab.stats': 'Statistics',
  'mentor.search': 'Search...',
  'mentor.selectGroup': 'Group',
  'mentor.chooseGroup': 'Choose a group',
  'mentor.close': 'Close',
  'mentor.dash.lessonInProgress': '{{group}} — lesson in progress',
  'mentor.dash.attendanceNotMarked': 'attendance not marked',
  'mentor.dash.markAttendance': 'Mark attendance',
  'mentor.dash.groups': 'Groups',
  'mentor.dash.active': 'active',
  'mentor.dash.students': 'Students',
  'mentor.dash.total': 'total',
  'mentor.dash.todayLessons': 'Today’s lessons',
  'mentor.dash.bySchedule': 'by schedule',
  'mentor.dash.todaySchedule': 'Today’s schedule',
  'mentor.dash.myGroups': 'My groups',
  'mentor.dash.noLessonsTitle': 'No lessons scheduled for today',
  'mentor.dash.noLessonsHint': 'Even if a group has no lesson time set, you can mark attendance manually.',
  'mentor.dash.goToAttendance': 'Go to attendance',
  'mentor.dash.studentsCount': '{{count}} students',
  'mentor.dash.now': 'Now',
  'mentor.dash.done': 'Done',
  'mentor.dash.attendance': 'Attendance',
  'mentor.chat.colleagues': 'Colleagues',
  'mentor.chat.notFound': 'Not found',
  'mentor.chat.noMentors': 'No mentors',
  'mentor.chat.online': 'Online',
  'mentor.chat.offline': 'Offline',
  'mentor.chat.noMessagesTitle': 'No messages',
  'mentor.chat.noMessagesHint': 'Write the first message',
  'mentor.chat.placeholder': 'Type a message...',
  'mentor.chat.selectContactTitle': 'Select a contact',
  'mentor.chat.selectContactHint': 'Pick a colleague from the left panel',
  'mentor.students.statusActive': 'Active',
  'mentor.students.statusFrozen': 'Frozen',
  'mentor.students.statusDropped': 'Dropped',
  'mentor.students.msgStudent': 'Message student',
  'mentor.students.msgParent': 'Message parent',
  'mentor.students.noParent': 'No parent linked',
  'mentor.students.viewStats': 'View statistics',
  'mentor.students.students': 'Students',
  'mentor.students.groups': 'Groups',
  'mentor.students.totalCoins': 'Total coins',
  'mentor.students.allMyStudents': 'All my students',
  'mentor.students.allGroups': 'All groups',
  'mentor.students.searchPlaceholder': 'Name, phone or ID...',
  'mentor.students.noStudentsTitle': 'No students yet',
  'mentor.students.nothingFoundTitle': 'Nothing found',
  'mentor.students.noStudentsHint': 'Once students are added to your groups, they’ll show up here.',
  'mentor.students.nothingFoundHint': 'Try changing your search or group filter.',
  'mentor.students.colStudent': 'Student',
  'mentor.students.colGroup': 'Group',
  'mentor.students.colPhone': 'Phone',
  'mentor.students.colStatus': 'Status',
  'mentor.students.colCoins': 'Coins',
  'mentor.students.shownCount': 'Showing {{shown}} / {{total}} students',
  'mentor.students.viewByGroups': 'View by group',
  'mentor.profile.gradeNotSet': 'Grade not set',
  'mentor.profile.noSkills': 'No skills added yet',
  'mentor.profile.removeSkill': '{{skill}} — remove',
  'mentor.profile.skillPlaceholder': 'E.g. IELTS, Grammar...',
  'mentor.profile.add': 'Add',
  'mentor.profile.skillsHint': '{{count}}/{{max}} · Press Enter or comma to add',
  'mentor.profile.groupsLabel': 'Groups',
  'mentor.profile.studentsLabel': 'Students',
  'mentor.profile.email': 'Email',
  'mentor.profile.phone': 'Phone',
  'mentor.profile.branch': 'Branch',
  'mentor.profile.registered': 'Registered',
  'mentor.profile.personalData': 'Personal data',
  'mentor.profile.personalDataHint': 'Parents and the administrator can see this data.',
  'mentor.profile.firstName': 'First name',
  'mentor.profile.lastName': 'Last name',
  'mentor.profile.emailHint': 'You sign in with this email; the password reset code is also sent to this address.',
  'mentor.profile.professionalInfo': 'Professional info',
  'mentor.profile.professionalHint': 'This is shown to parents to introduce you.',
  'mentor.profile.about': 'About',
  'mentor.profile.aboutPlaceholder': 'Your experience, teaching style, achievements...',
  'mentor.profile.skills': 'Skills',
  'mentor.profile.grade': 'Grade',
  'mentor.profile.gradeHint': 'The administrator sets the grade — you can’t change it yourself.',
  'mentor.profile.saved': 'Saved',
  'mentor.profile.unsavedChanges': 'There are unsaved changes',
  'mentor.profile.cancel': 'Cancel',
  'mentor.profile.save': 'Save',
  'mentor.profile.security': 'Security',
  'mentor.profile.password': 'Password',
  'mentor.profile.passwordHint': 'For security, the password is not changed here — it is restored via a confirmation code sent to your email.',
  'mentor.profile.resetPassword': 'Reset password',
  'mentor.profile.endSession': 'End session',
  'mentor.profile.endSessionHint': 'You will be signed out on this device.',
  'mentor.profile.logout': 'Sign out',
  'mentor.profile.enterFirstName': 'Enter a first name',
  'mentor.profile.enterLastName': 'Enter a last name',
  'mentor.profile.invalidEmail': 'Invalid email',
  'mentor.profile.saveFailed': 'Failed to save',
  'mentor.sd.months': 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',
  'mentor.sd.hw.graded': 'Graded',
  'mentor.sd.hw.submitted': 'Submitted',
  'mentor.sd.hw.late': 'Submitted late',
  'mentor.sd.hw.missed': 'Not submitted',
  'mentor.sd.hw.pending': 'Not due yet',
  'mentor.sd.att.present': 'Present',
  'mentor.sd.att.late': 'Late',
  'mentor.sd.att.absent': 'Absent',
  'mentor.sd.att.excused': 'Excused',
  'mentor.sd.homeworkKind': 'Homework',
  'mentor.sd.testKind': 'Test',
  'mentor.sd.noChange': 'no change',
  'mentor.sd.vsPrevMonth': 'vs last mo.',
  'mentor.sd.studentNotFoundTitle': 'Student not found',
  'mentor.sd.studentNotFoundHint': 'They may have been dropped from your group.',
  'mentor.sd.toStudentsList': 'To student list',
  'mentor.sd.allStudents': 'All students',
  'mentor.sd.frozen': 'Frozen',
  'mentor.sd.coins': 'Coins',
  'mentor.sd.stats': 'Statistics',
  'mentor.sd.missedTasks': '{{count}} assignments not completed',
  'mentor.sd.tabOverall': 'Overview',
  'mentor.sd.tabAttendance': 'Attendance',
  'mentor.sd.tabTests': 'Tests',
  'mentor.sd.tabHomework': 'Homework',
  'mentor.sd.attendanceRing': 'Attendance',
  'mentor.sd.lessonsCount': '{{n}} / {{total}} lessons',
  'mentor.sd.homeworkRing': 'Homework',
  'mentor.sd.submittedCount': '{{n}} / {{total}} submitted',
  'mentor.sd.testsRing': 'Tests',
  'mentor.sd.takenCount': '{{n}} / {{total}} taken',
  'mentor.sd.last6Months': 'Last 6 months',
  'mentor.sd.avgGrade': 'Avg. grade',
  'mentor.sd.gapNote': 'A gap in the line means no data for that month (no lessons or assignments).',
  'mentor.sd.wellLearned': 'Well learned',
  'mentor.sd.noGradedWorks': 'No graded work',
  'mentor.sd.hasDifficulties': 'Has difficulties',
  'mentor.sd.noWeakTopics': 'No weak topics — all work is above 80%',
  'mentor.sd.byMonth': 'By month',
  'mentor.sd.recentLessons': 'Recent lessons',
  'mentor.sd.attendanceNotMarked': 'Attendance not marked',
  'mentor.sd.totalLessons': '{{n}} lessons',
  'mentor.sd.avgScore': 'Average score',
  'mentor.sd.allTests': 'All tests',
  'mentor.sd.noTests': 'No tests',
  'mentor.sd.notTaken': 'Not taken',
  'mentor.sd.avgGradeByMonth': 'Avg. grade — by month',
  'mentor.sd.tasks': 'Tasks',
  'mentor.sd.notSubmittedCount': 'Not submitted ({{count}})',
  'mentor.sd.submittedCountFilter': 'Submitted ({{count}})',
  'mentor.sd.all': 'All',
  'mentor.sd.allTasksDone': 'All tasks completed',
  'mentor.sd.noTasks': 'No tasks',
  'mentor.sd.until': 'by',
  'mentor.sd.doneCount': '{{n}} / {{total}} submitted',
  'mentor.sd.noDataTooltip': 'no data',

  // people/Directory.jsx
  'people.title': 'People & clients',
  'people.subtitle': 'A single directory of staff, parents and students, scoped to your role',
  'people.searchPlaceholder': 'Name, phone or email',
  'people.allRoles': 'All roles',
  'people.loading': 'Loading directory…',
  'people.loadError': 'Failed to load the directory',
  'people.emptyFilter': 'No one matches your filter',
  'people.inSelection': 'People in selection',
  'people.students': 'Students',
  'people.debt': 'Invoice debt',
  'people.overdue': 'Overdue',
  'people.person': 'Person',
  'people.role': 'Role',
  'people.branch': 'Branch',
  'people.status': 'Status',
  'people.paid': 'Paid',
  'people.noContact': 'No contact listed',
  'people.platform': 'Platform',
  'people.childrenCount': 'Children: {{count}}',

  // status (format.js: ORG_STATUS/USER_STATUS/ADMIN_STATUS/LEAD_STATUS)
  'status.active': 'Active',
  'status.trial': 'Trial',
  'status.frozen': 'Frozen',
  'status.dropped': 'Dropped',
  'status.new': 'New',
  'status.contacted': 'Contacted',
  'status.onboarded': 'Onboarded',
  'status.rejected': 'Rejected',

  // roles
  'role.seo': 'SEO (Head)',
  'role.admin': 'Administrator',
  'role.branch_manager': 'Branch Manager',
  'role.finance_manager': 'Finance Manager',
  'role.mentor': 'Mentor',
  'role.methodist': 'Methodist',
  'role.student': 'Student',
  'role.parent': 'Parent',
  'role.employee': 'Employee',

  // notifications
  'notifications.title': 'Notifications',
  'notifications.empty': 'No new notifications',
  'notifications.emptyDesc': 'Unread messages will appear here.',
  'notifications.new': 'new',
  'notifications.allMessages': 'All messages',
  'notifications.newMessage': 'New message',
  'notifications.soundOn': 'Sound enabled',
  'notifications.soundOff': 'Sound muted',
  'notifications.muteSound': 'Mute sound',
  'notifications.unmuteSound': 'Unmute sound',

  // kpi & dashboard
  'kpi.income': 'Monthly income',
  'kpi.expenses': 'Monthly expenses',
  'kpi.salaries': 'Monthly salaries',
  'kpi.profit': 'Net profit',
  'kpi.netProfit': 'Net profit',
  'kpi.orgIncome': 'Org income',
  'kpi.orgExpenses': 'Org expenses',
  'kpi.orgProfit': 'Org profit',
  'kpi.students': 'Total students',
  'kpi.groups': 'Total groups',
  'kpi.mentors': 'Total mentors',
  'kpi.debt': 'Outstanding debt',
  'kpi.attendance': 'Attendance rate',

  // dashboard details
  'dash.branchStats': 'Branch Metrics',
  'dash.activeStudents': 'Active Students',
  'dash.groups': 'Groups',
  'dash.overdueInvoices': 'Overdue Invoices',
  'dash.recentPayments': 'Recent Payments',
  'dash.noPayments': 'No payments yet',
  'dash.student': 'Student',
  'dash.reminders': 'Reminders',
  'dash.overduePaymentsTitle': 'Overdue Payments',
  'dash.overduePaymentsDesc': 'Currently {{count}} invoices are overdue. Monitor payments.',
  'dash.activeStudentsTitle': 'Active Students',
  'dash.activeStudentsDesc': '{{count}} active students are studying at the branch.',
  'dash.thisMonth': 'This Month',
  'dash.income': 'Income',
  'dash.expenses': 'Expenses',
  'dash.profit': 'Profit',
  'dash.loadError': 'Loading error',
  'dash.title': 'Dashboard',
  'dash.welcome': 'Welcome',
  'dash.bmSubtitle': 'branch general overview',
  'dash.incomeThisMonth': 'Income this month',
  'dash.expensesThisMonth': 'Expenses this month',
  'dash.debtDesc': 'overdue payments',
  'dash.profitFormula': 'income − expenses',
  'dash.vsPrevMonth': 'compared to last month',
  'dash.mainBranch': 'Main branch',
  'dash.addressNotSet': 'Address not specified',
  'dash.phoneNotSet': 'Phone not specified',
  'dash.workHoursNotSet': 'Working hours not specified',
  'dash.staff': 'Staff',
  'dash.recentBranchPayments': 'Recent Payments',
  'dash.noPaymentsYet': 'No payments yet',
  'dash.last6Months': 'Last 6 months: income vs expenses',

  // branch details
  'branch.about': 'About branch',
  'branch.locationStats': 'location & statistics',
  'branch.contacts': 'Contacts',
  'branch.address': 'Address',
  'branch.phone': 'Phone',
  'branch.financeTotal': 'Finance (total)',
  'branch.tgCardTitle': 'Parent group (Telegram)',
  'branch.tgConnected': 'Group connected',
  'branch.tgDisconnect': 'Disconnect',
  'branch.tgDesc': 'Attendance and performance updates will automatically be sent to this group. First add the bot to the group, then generate the connection code.',
  'branch.tgGetCode': 'Get connection code',
  'branch.tgStep1': 'Add bot to group',
  'branch.tgStep2': 'Send the following command in the group',
  'branch.tgCodeValid': 'Code is valid for {{min}} minutes.',
  'branch.notFound': 'Branch data not found',
  'branch.unlinkConfirm': 'Are you sure you want to disconnect the group?',

  // tax
  'tax.title': 'Tax Report',
  'tax.subtitle': 'Tax calculations by branch and organization',
  'tax.export': 'Export CSV',
  'tax.due': 'Total tax due',
  'tax.tableTitle': 'Branch tax overview',
  'tax.netProfit': 'Net profit',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Select language',

  // ---------- finance-manager panel (formerly pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Dashboard',
  'finance.nav.income': 'Income',
  'finance.nav.expenses': 'Expenses',
  'finance.nav.salaries': 'Salaries',
  'finance.nav.reports': 'Reports',
  'finance.nav.report': 'Report',
  'finance.nav.admins': 'Staff',
  'finance.nav.finance': 'Finance',
  'finance.nav.analytics': 'Analytics',
  'finance.nav.stats': 'Statistics',
  'finance.nav.tax': 'Taxes',
  'finance.nav.taxTitle': 'Tax Report',
  'finance.nav.taxNdss': 'VAT 20%',
  'finance.nav.taxSocNalog': 'Social tax 10%',
  'finance.nav.taxOtzyvnoyNalog': 'Profit tax 1.5%',
  'finance.nav.taxTotal': 'Total',
  'finance.nav.taxOrg': 'Organization',
  'finance.nav.allStudents': 'All students',
  'finance.nav.allGroups': 'All groups',
  'finance.nav.attendance': 'Attendance',
  'finance.nav.more': 'More',
  'finance.nav.discipline': 'Discipline',
  'finance.nav.announcements': 'Announcements',
  'finance.nav.reminders': 'Reminders',
  'finance.nav.audit': 'Audit',
  'finance.nav.settings': 'Settings',
  'finance.nav.students': 'Students',
  'finance.nav.groups': 'Groups',
  'finance.nav.mentors': 'Mentors',
  'finance.nav.chat': 'Chat',
  'finance.nav.payments': 'Payments',
  'finance.nav.branch': 'Branch',
  'finance.nav.branches': 'Branches',
  'finance.nav.allBranches': 'All branches',
  'finance.nav.noBranches': 'No branches',
  'finance.nav.noGroups': 'No groups',
  'finance.nav.methodistTypes': 'Training types',
  'finance.nav.main': 'main',
  'finance.nav.collapse': 'Collapse',
  'finance.nav.pin': 'Pin',
  'finance.nav.collapsePanel': 'Collapse panel',
  'finance.nav.pinPanel': 'Pin panel',

  'finance.kpi.income': 'Monthly income',
  'finance.kpi.expenses': 'Monthly expenses',
  'finance.kpi.salaries': 'Monthly payroll',
  'finance.kpi.netProfit': 'Net profit',
  'finance.kpi.orgIncome': 'Org income',
  'finance.kpi.orgExpenses': 'Org expenses',
  'finance.kpi.orgProfit': 'Org profit',

  'finance.common.total': 'Total',
  'finance.common.share': 'Share',
  'finance.common.amount': 'Amount',
  'finance.common.date': 'Date',
  'finance.common.status': 'Status',
  'finance.common.method': 'Method',
  'finance.common.note': 'Note',
  'finance.common.category': 'Category',
  'finance.common.employee': 'Employee',
  'finance.common.position': 'Position',
  'finance.common.branch': 'Branch',
  'finance.common.allBranches': 'All branches',
  'finance.common.month': 'Month',
  'finance.common.period': 'Period',
  'finance.common.vsPrev': 'vs previous month',
  'finance.common.noData': 'No data',
  'finance.common.students': 'Students',
  'finance.common.groups': 'Groups',
  'finance.common.staff': 'Staff',
  'finance.common.loading': 'Loading…',
  'finance.common.page': 'Page',
  'finance.common.save': 'Save',
  'finance.common.cancel': 'Cancel',
  'finance.common.add': 'Add',
  'finance.common.edit': 'Edit',
  'finance.common.delete': 'Delete',
  'finance.common.confirmDelete': 'Delete this record?',

  'finance.dash.title': 'Finance dashboard',
  'finance.dash.subtitle': 'Whole org · by branch and month',
  'finance.dash.trendChart': 'Org income and expenses',
  'finance.dash.profitLine': 'Profit',
  'finance.dash.branchShare': 'Branch share of income',
  'finance.dash.monthlyProfit': 'Net profit for 6 months',
  'finance.dash.viewReports': 'Detailed report',
  'finance.dash.days30Org': 'Last 30 days · whole org',
  'finance.dash.chartSub': 'Actual receipts over 30 days',
  'finance.dash.branches': 'Branches',

  'finance.income.title': 'Income',
  'finance.income.subtitle': 'Payments by branch and month',
  'finance.income.tableTitle': 'Payments',
  'finance.income.student': 'Student',
  'finance.income.group': 'Group',

  'finance.expenses.title': 'Expenses',
  'finance.expenses.subtitle': 'Expenses by branch and category',
  'finance.expenses.catBreakdown': 'By category',
  'finance.expenses.add': 'New expense',
  'finance.expenses.edit': 'Edit expense',
  'finance.expenses.orgWide': 'Whole organization',
  'finance.expenses.categoryPlaceholder': 'E.g. Rent',

  'finance.salaries.title': 'Salaries',
  'finance.salaries.subtitle': 'Payroll by branch',
  'finance.salaries.payroll': 'Monthly payroll',
  'finance.salaries.sheetTitle': 'Payroll sheet',

  'finance.reports.title': 'Reports',
  'finance.reports.subtitle': 'Monthly summary by branch',
  'finance.reports.org': 'Organization',
  'finance.reports.cashFlow': 'Cash flow',
  'finance.reports.branchTable': 'Branches · summary',
  'finance.reports.branchNet': 'Branch net',
  'finance.reports.branchDetail': 'Branch detail',
  'finance.reports.net': 'Net profit',
  'finance.reports.opProfit': 'Operating profit',
  'finance.reports.vsPrevMonth': 'vs previous month',
  'finance.reports.export': 'Export CSV',
  'finance.reports.paymentsThisMonth': 'Payments · this month',
  'finance.reports.byStatus': 'By payment status',
  'finance.reports.byMethod': 'By payment method',
  'finance.reports.overdueAmount': 'Overdue',
  'finance.reports.expensesByCategory': 'Expenses by category',
  'finance.reports.subtitleLive': 'Live backend data · last 30 days',
  'finance.reports.incomeLabel': 'Revenue over 30 days',
  'finance.reports.activeStudents': 'Active students',
  'finance.reports.last30days': 'Last 30 days',
  'finance.reports.debtLabel': 'Debt',
  'finance.reports.incomeDebtByBranch': 'Revenue and debt by branch',
  'finance.reports.methodsSubtitle': 'Completed transactions',
  'finance.reports.noCompletedPayments': 'No completed payments',
  'finance.reports.orgRow': 'ORGANIZATION',
  'finance.method.cash': 'Cash',
  'finance.method.card': 'Card',
  'finance.method.transfer': 'Transfer',
  'finance.method.bankTransfer': 'Bank transfer',
  'finance.salaryStatus.draft': 'Draft',
  'finance.salaryStatus.approved': 'Approved',
  'finance.salaryStatus.paid': 'Paid',

  'finance.settings.title': 'Settings',
  'finance.settings.subtitle': 'Profile and preferences',
  'finance.settings.personal': 'Personal info',
  'finance.settings.personalSub': 'These details are shown in the system and saved to your profile',
  'finance.settings.firstName': 'First name',
  'finance.settings.lastName': 'Last name',
  'finance.settings.phone': 'Phone',
  'finance.settings.city': 'City',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Save',
  'finance.settings.saved': 'Settings saved',
  'finance.settings.lang': 'Interface language',
  'finance.settings.langSub': 'Applied instantly across the whole panel',
  'finance.settings.security': 'Security',
  'finance.settings.securitySub': 'Password change and account details are managed via the main account',
  'methodist.app.name': "Content Studio",
  'methodist.common.loading_error': "Loading error",
  'methodist.common.loading_failed': "Failed to load data",
  'methodist.common.retry': "Retry",
  'methodist.common.no_data': "No data",
  'methodist.common.all': "All",
  'methodist.common.back': "Back",
  'methodist.common.save': "Save",
  'methodist.common.cancel': "Cancel",
  'methodist.common.delete': "Delete",
  'methodist.common.edit': "Edit",
  'methodist.common.add': "Add",
  'methodist.common.create': "Create",
  'methodist.common.close': "Close",
  'methodist.common.copy': "Duplicate",
  'methodist.common.tests_count': "{{count}} tests",
  'methodist.common.attempts_count': "{{count}} attempts",
  'methodist.kpi.types': "Training types",
  'methodist.kpi.topics': "Total topics",
  'methodist.kpi.tests': "Tests",
  'methodist.kpi.hw': "Homework",
  'methodist.dashboard.subtitle': "Create and manage learning materials",
  'methodist.dashboard.topics_count': "{{count}} topics",
  'methodist.dashboard.avg_score': "Average test score",
  'methodist.dashboard.great': "Great",
  'methodist.dashboard.good': "Good",
  'methodist.dashboard.need_work': "Needs work",
  'methodist.dashboard.types_section': "Training types",
  'methodist.dashboard.all_types': "All types",
  'methodist.dashboard.no_types': "No training types",
  'methodist.dashboard.no_types_hint': "Create the first type to start",
  'methodist.dashboard.create_type': "Create type",
  'methodist.analytics.title': "Performance Analytics",
  'methodist.analytics.subtitle': "Difficulty statistics by subjects and tests",
  'methodist.analytics.donut_aria': "Overall average score {{num}}%",
  'methodist.analytics.total_tests': "Total tests",
  'methodist.analytics.total_attempts': "Total attempts",
  'methodist.analytics.overall_avg': "Overall average",
  'methodist.analytics.performance': "Performance",
  'methodist.analytics.score_good': "Good",
  'methodist.analytics.score_avg': "Average",
  'methodist.analytics.score_hard': "Hard",
  'methodist.analytics.subject_difficulty': "Subject difficulty",
  'methodist.analytics.by_avg_score': "By average score",
  'methodist.analytics.low_tests': "Tests with low results",
  'methodist.analytics.top5': "Top 5 by difficulty",
  'methodist.analytics.all_tests': "All tests",
  'methodist.analytics.full_table': "Full results table",
  'methodist.analytics.col_title': "Title",
  'methodist.analytics.col_group': "Group",
  'methodist.analytics.col_branch': "Branch",
  'methodist.analytics.col_attempts': "Attempts",
  'methodist.analytics.col_avg': "Avg. score",
  'methodist.analytics.general_subject': "General",
  'methodist.types.title': "Training types",
  'methodist.types.subtitle': "Directions: Backend, Frontend, Python, etc.",
  'methodist.types.add': "Add type",
  'methodist.types.no_types': "No training types",
  'methodist.types.no_types_hint': "Create the first type to start adding content",
  'methodist.types.create_first': "Create first type",
  'methodist.types.topics_count': "{{count}} topics",
  'methodist.types.description_short': "description",
  'methodist.types.archive_tooltip': "Archive",
  'methodist.types.open_topics': "Open topics",
  'methodist.types.archive_confirm': "Archive type?",
  'methodist.types.archive_hidden': "«{{name}}» will be hidden",
  'methodist.types.archive': "Archive",
  'methodist.types.new_title': "New training type",
  'methodist.types.new_hint': "Create a training direction",
  'methodist.types.name_label': "Name *",
  'methodist.types.name_placeholder': "e.g. Backend",
  'methodist.types.name_required': "Name is required",
  'methodist.types.description_label': "Description",
  'methodist.types.description_placeholder': "Briefly about the direction...",
  'methodist.types.icon_label': "Icon (emoji)",
  'methodist.types.ai_review_label': "Smart review (AI)",
  'methodist.types.ai_review_hint': "AI will review student code on practical tasks for this course. Enable only where practice is real readable code (HTML/CSS/JS), not for courses with many files.",
  'methodist.topics.breadcrumb_types': "Training types",
  'methodist.topics.breadcrumb_topics': "Topics",
  'methodist.topics.title': "Topics",
  'methodist.topics.subtitle': "Lessons and tests within the direction",
  'methodist.topics.add': "Add topic",
  'methodist.topics.create': "Create topic",
  'methodist.topics.no_topics': "No topics",
  'methodist.topics.no_topics_hint': "Create the first topic in this direction",
  'methodist.topics.lessons_count': "{{count}} lessons",
  'methodist.topics.description_short': "description",
  'methodist.topics.edit_tooltip': "Edit",
  'methodist.topics.delete_tooltip': "Delete",
  'methodist.topics.archive_tooltip': "Archive",
  'methodist.topics.lessons_and_tests': "Lessons and tests",
  'methodist.topics.archive_confirm': "Archive topic?",
  'methodist.topics.archive_hidden': "«{{name}}» will be hidden",
  'methodist.topics.archive': "Archive",
  'methodist.topics.new_title': "New topic",
  'methodist.topics.new_hint': "Add a topic to the direction",
  'methodist.topics.name_label': "Name *",
  'methodist.topics.name_placeholder': "e.g. React Hooks",
  'methodist.topics.name_required': "Name is required",
  'methodist.topics.description_label': "Description",
  'methodist.topics.description_placeholder': "What is this topic about...",
  'methodist.topics.description': "Description",
  'methodist.topics.video_label': "Topic video",
  'methodist.topics.video_mode_url': "Link",
  'methodist.topics.video_mode_file': "File",
  'methodist.topics.video_url_placeholder': "YouTube link",
  'methodist.topics.video_upload_hint': "or drag and drop a video here",
  'methodist.topics.video_no_file': "No video uploaded",
  'methodist.topics.video_remove': "Remove video",
  'methodist.topics.coin_reward_label': "Coins for watching the video",
  'methodist.topics.coin_reward_hint': "Awarded once, in full, when the student watches the video to the end",
  'methodist.topics.video_after_create_hint': "File upload becomes available after the topic is created — save first",
  'methodist.lessons.breadcrumb_types': "Types",
  'methodist.lessons.breadcrumb_topics': "Topics",
  'methodist.lessons.breadcrumb_lessons': "Lessons",
  'methodist.lessons.title': "Lessons",
  'methodist.lessons.subtitle': "Tests and practical tasks within the topic",
  'methodist.lessons.create': "Create lesson",
  'methodist.lessons.badge_test': "Test",
  'methodist.lessons.badge_practical': "Practice",
  'methodist.lessons.no_lessons': "No lessons",
  'methodist.lessons.no_lessons_hint': "Create the first test or practical task",
  'methodist.lessons.questions_count': "{{count}} questions",
  'methodist.lessons.requirements_count': "{{count}} requirements",
  'methodist.lessons.copy_tooltip': "Copy lesson",
  'methodist.lessons.archive_tooltip': "Archive",
  'methodist.lessons.edit_tooltip': "Edit",
  'methodist.lessons.archive_confirm': "Archive lesson?",
  'methodist.lessons.archive': "Archive",
  'methodist.lessons.new_title': "New lesson",
  'methodist.lessons.new_hint': "Create a test or practical task",
  'methodist.lessons.field_title': "Name *",
  'methodist.lessons.title_placeholder': "e.g. HTML Tags",
  'methodist.lessons.title_required': "Name is required",
  'methodist.lessons.lesson_type_label': "Lesson type",
  'methodist.lessons.type_test': "Test (A/B/C/D)",
  'methodist.lessons.type_practical': "Practical task",
  'methodist.lessons.desc_label': "Task description",
  'methodist.lessons.desc_placeholder': "Describe the task for the student...",
  'methodist.lessons.instruction_label': "Instruction / Explanation",
  'methodist.lessons.instruction_placeholder': "Brief topic explanation...",
  'methodist.lessons.coin_label': "Reward (coins)",
  'methodist.lessons.create_and_edit': "Create and edit",
  'methodist.editor.title': "Lesson editor",
  'methodist.editor.subtitle': "Test or practical task",
  'methodist.editor.settings_tooltip': "Lesson settings",
  'methodist.editor.test_count': "Test · {{count}} questions",
  'methodist.editor.type_practical': "Practical task",
  'methodist.editor.requirements_title': "Mandatory requirements",
  'methodist.editor.requirements_hint': "What the student must complete in the task",
  'methodist.editor.requirement_text': "Requirement *",
  'methodist.editor.requirement_points': "Points",
  'methodist.editor.add_requirement': "Add requirement",
  'methodist.editor.save_requirements': "Save requirements",
  'methodist.editor.requirements_total': "Total {{points}} points",
  'methodist.editor.no_requirements': "No requirements yet. Add the first one.",
  'methodist.editor.video_label': "Video material:",
  'methodist.editor.task_desc': "Task description",
  'methodist.editor.attachment_label': "Attached file to the task:",
  'methodist.editor.no_file': "No file attached",
  'methodist.editor.upload_drop_hint': "or drag and drop a file here",
  'methodist.editor.instruction': "Instruction / Explanation",
  'methodist.editor.edit_question': "Edit question",
  'methodist.editor.add_question': "Add question",
  'methodist.editor.question_type': "Question type",
  'methodist.editor.question_text': "Question text *",
  'methodist.editor.question_placeholder': "Which tag is used for the heading?",
  'methodist.editor.option_label': "Option {{letter}}",
  'methodist.editor.correct_answer': "Correct answer *",
  'methodist.editor.batch_title': "Quick create",
  'methodist.editor.empty_questions': "empty questions",
  'methodist.editor.questions': "Questions",
  'methodist.editor.no_questions': "No questions. Add the first question above.",
  'methodist.editor.delete_confirm': "Delete question?",
  'methodist.editor.settings_title': "Lesson settings",
  'methodist.editor.settings_name': "Name *",
  'methodist.editor.video_url_label': "Video lesson (YouTube/S3 link)",
  'methodist.editor.coin_label': "Reward (coins)",
  'methodist.editor.question_required': "Question is required",
  'methodist.editor.option_required': "Option {{letter}} is required",
  'methodist.editor.correct_answer_required': "Correct answer is required",
  'methodist.editor.title_required': "Name is required",
  'methodist.editor.invalid_url': "Invalid link",
  'methodist.editor.description_required_practical': "Description is required for practical lessons — AI review relies on it",
  'methodist.editor.question_prefix': "Question",
  'methodist.editor.type_choice': "Options",
  'methodist.editor.type_riddle': "Riddle",
  'methodist.editor.type_open': "Question and answer",
  'methodist.profile.role_methodist': "Methodist",
  'methodist.profile.email': "Email",
  'methodist.profile.branch': "Branch",
  'methodist.profile.registered': "Registered",
  'methodist.profile.load_error': "Error loading profile",
  'methodist.profile.personal_data': "Personal data",
  'methodist.profile.personal_data_hint': "The organization administrator sees this data.",
  'methodist.profile.first_name': "First name",
  'methodist.profile.last_name': "Last name",
  'methodist.profile.email_hint': "You sign in with this email; the password reset code is also sent to this address.",
  'methodist.profile.saved': "Saved",
  'methodist.profile.dirty': "There are unsaved changes",
  'methodist.profile.enter_name': "Enter a first name",
  'methodist.profile.enter_last': "Enter a last name",
  'methodist.profile.invalid_email': "Invalid email",
  'methodist.profile.save_failed': "Failed to save",
  'methodist.profile.security': "Security",
  'methodist.profile.password': "Password",
  'methodist.profile.password_hint': "For security, the password is not changed here — it is restored via a confirmation code sent to your email.",
  'methodist.profile.reset_password': "Reset password",
  'methodist.profile.end_session': "End session",
  'methodist.profile.session_hint': "You will be signed out on this device.",
  'methodist.profile.logout': "Sign out",
};

export default en;
