const ru = {
  // nav
  'nav.dashboard': 'Дашборд',
  'nav.income': 'Доходы',
  'nav.expenses': 'Расходы',
  'nav.salaries': 'Зарплаты',
  'nav.reports': 'Отчёты',
  'nav.report': 'Отчёт',
  'nav.admins': 'Сотрудники',
  'nav.finance': 'Финансы',
  'nav.analytics': 'Аналитика',
  'nav.stats': 'Статистика',
  'nav.tax': 'Налоги',
  'nav.taxNdss': 'НДС 20%',
  'nav.taxSocNalog': 'Соцналог 10%',
  'nav.taxOtzyvnoyNalog': 'Оборотный налог 1.5%',
  'nav.taxTotal': 'Итого налогов',
  'nav.taxOrg': 'Организация',
  'nav.allStudents': 'Все ученики',
  'nav.allGroups': 'Все группы',
  'nav.attendance': 'Посещаемость',
  'nav.more': 'Ещё',
  'nav.discipline': 'Дисциплина',
  'nav.announcements': 'Объявления',
  'nav.reminders': 'Напоминания',
  'nav.audit': 'Аудит',
  'nav.features': 'Фичи',
  'nav.billing': 'Оплата',
  'nav.methodics': 'Методики',
  'nav.shopCatalog': 'Магазин',
  'nav.settings': 'Настройки',
  'nav.students': 'Студенты',
  'nav.groups': 'Группы',
  'nav.mentors': 'Менторы',
  'nav.chat': 'Чат',
  'nav.payments': 'Платежи',
  'nav.branch': 'Филиал',
  'nav.branches': 'Филиалы',
  'nav.allBranches': 'Все филиалы',
  'nav.noBranches': 'Филиалов нет',
  'nav.noGroups': 'Групп нет',
  'nav.methodistTypes': 'Типы обучения',
  'nav.people': 'Люди и клиенты',
  'nav.clientBase': 'База клиентов',
  'nav.myStudents': 'Мои ученики',
  'nav.participantBase': 'База участников',
  'nav.schedule': 'Расписание',
  'nav.main': 'осн',
  'nav.collapse': 'Свернуть',
  'nav.pin': 'Закрепить',
  'nav.collapsePanel': 'Свернуть панель',
  'nav.pinPanel': 'Закрепить панель',

  // common
  'common.total': 'Итого',
  'common.amount': 'Сумма',
  'common.search': 'Поиск...',
  'common.profile': 'Профиль',
  'common.logout': 'Выйти',
  'common.myProfile': 'Мой профиль',
  'common.exit': 'Выйти',
  'common.branch': 'Филиал',
  'common.allBranches': 'Все филиалы',
  'common.status': 'Статус',
  'common.actions': 'Действия',
  'common.date': 'Дата',
  'common.time': 'Время',
  'common.phone': 'Телефон',
  'common.email': 'Email',
  'common.name': 'Название',
  'common.fullName': 'ФИО',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.edit': 'Редактировать',
  'common.add': 'Добавить',
  'common.create': 'Создать',
  'common.details': 'Подробнее',
  'common.view': 'Просмотр',
  'common.back': 'Назад',
  'common.next': 'Далее',
  'common.loading': 'Загрузка...',
  'common.error': 'Произошла ошибка',
  'common.success': 'Успешно',
  'common.filter': 'Фильтр',
  'common.all': 'Все',
  'common.active': 'Активен',
  'common.inactive': 'Неактивен',
  'common.frozen': 'Заморожен',
  'common.archived': 'Архивирован',
  'common.export': 'Экспорт',
  'common.download': 'Скачать',
  'common.upload': 'Загрузить',
  'common.close': 'Закрыть',
  'common.confirm': 'Подтвердить',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.empty': 'Данные не найдены',
  'common.reload': 'Обновить',
  'common.month': 'Месяц',
  'common.period': 'Период',
  'common.notes': 'Примечания',
  'common.description': 'Описание',
  'common.accountMenu': 'Меню аккаунта',
  'common.yesterday': 'Вчера',

  // mentor/*
  'mentor.noGroupsTitle': 'У вас пока нет групп',
  'mentor.noGroupsHint': 'Когда группа будет назначена, она появится в списке слева.',
  'mentor.groupNotFoundTitle': 'Группа не найдена',
  'mentor.groupNotFoundHint': 'Возможно, она в архиве или была отобрана.',
  'mentor.toHome': 'На главную',
  'mentor.back': 'Назад',
  'mentor.archived': 'В архиве',
  'mentor.direction': 'Направление',
  'mentor.subject': 'Предмет',
  'mentor.lessonTime': 'Время урока',
  'mentor.students': 'Ученики',
  'mentor.totalCoins': 'Всего коинов',
  'mentor.groupSections': 'Разделы группы',
  'mentor.tab.attendance': 'Посещаемость',
  'mentor.tab.tests': 'Тесты',
  'mentor.tab.stats': 'Статистика',
  'mentor.search': 'Поиск...',
  'mentor.selectGroup': 'Группа',
  'mentor.chooseGroup': 'Выберите группу',
  'mentor.close': 'Закрыть',
  'mentor.dash.lessonInProgress': '{{group}} — идёт урок',
  'mentor.dash.attendanceNotMarked': 'посещаемость не отмечена',
  'mentor.dash.markAttendance': 'Отметить посещаемость',
  'mentor.dash.groups': 'Группы',
  'mentor.dash.active': 'активных',
  'mentor.dash.students': 'Ученики',
  'mentor.dash.total': 'всего',
  'mentor.dash.todayLessons': 'Сегодняшние уроки',
  'mentor.dash.bySchedule': 'по расписанию',
  'mentor.dash.todaySchedule': 'Расписание на сегодня',
  'mentor.dash.myGroups': 'Мои группы',
  'mentor.dash.noLessonsTitle': 'Сегодня уроков нет в расписании',
  'mentor.dash.noLessonsHint': 'Даже если для группы не установлено время урока, вы можете отметить посещаемость вручную.',
  'mentor.dash.goToAttendance': 'Перейти к посещаемости',
  'mentor.dash.studentsCount': '{{count}} учеников',
  'mentor.dash.now': 'Идёт',
  'mentor.dash.done': 'Завершено',
  'mentor.dash.attendance': 'Посещаемость',
  'mentor.chat.colleagues': 'Коллеги',
  'mentor.chat.notFound': 'Не найдено',
  'mentor.chat.noMentors': 'Менторов нет',
  'mentor.chat.online': 'Онлайн',
  'mentor.chat.offline': 'Оффлайн',
  'mentor.chat.noMessagesTitle': 'Сообщений нет',
  'mentor.chat.noMessagesHint': 'Напишите первым',
  'mentor.chat.placeholder': 'Напишите сообщение...',
  'mentor.chat.selectContactTitle': 'Выберите собеседника',
  'mentor.chat.selectContactHint': 'Выберите коллегу в левой панели',
  'mentor.students.statusActive': 'Активен',
  'mentor.students.statusFrozen': 'Заморожен',
  'mentor.students.statusDropped': 'Отчислен',
  'mentor.students.msgStudent': 'Написать ученику',
  'mentor.students.msgParent': 'Написать родителю',
  'mentor.students.noParent': 'Родитель не привязан',
  'mentor.students.viewStats': 'Посмотреть статистику',
  'mentor.students.students': 'Ученики',
  'mentor.students.groups': 'Группы',
  'mentor.students.totalCoins': 'Всего коинов',
  'mentor.students.allMyStudents': 'Все мои ученики',
  'mentor.students.allGroups': 'Все группы',
  'mentor.students.searchPlaceholder': 'Имя, телефон или ID...',
  'mentor.students.noStudentsTitle': 'Пока нет учеников',
  'mentor.students.nothingFoundTitle': 'Ничего не найдено',
  'mentor.students.noStudentsHint': 'Когда ученики будут добавлены в ваши группы, они появятся здесь.',
  'mentor.students.nothingFoundHint': 'Измените поиск или фильтр группы.',
  'mentor.students.colStudent': 'Ученик',
  'mentor.students.colGroup': 'Группа',
  'mentor.students.colPhone': 'Телефон',
  'mentor.students.colStatus': 'Статус',
  'mentor.students.colCoins': 'Коины',
  'mentor.students.shownCount': '{{shown}} / {{total}} учеников отображается',
  'mentor.students.viewByGroups': 'Посмотреть по группам',
  'mentor.profile.gradeNotSet': 'Уровень не установлен',
  'mentor.profile.noSkills': 'Навыки пока не добавлены',
  'mentor.profile.removeSkill': '{{skill}} — удалить',
  'mentor.profile.skillPlaceholder': 'Например: IELTS, Грамматика...',
  'mentor.profile.add': 'Добавить',
  'mentor.profile.skillsHint': '{{count}}/{{max}} · Нажмите Enter или запятую для добавления',
  'mentor.profile.groupsLabel': 'Групп',
  'mentor.profile.studentsLabel': 'Учеников',
  'mentor.profile.email': 'Email',
  'mentor.profile.phone': 'Телефон',
  'mentor.profile.branch': 'Филиал',
  'mentor.profile.registered': 'Зарегистрирован',
  'mentor.profile.personalData': 'Личные данные',
  'mentor.profile.personalDataHint': 'Эти данные видят родители и администратор.',
  'mentor.profile.firstName': 'Имя',
  'mentor.profile.lastName': 'Фамилия',
  'mentor.profile.emailHint': 'Вы входите в систему с этим email, код восстановления пароля также приходит на этот адрес.',
  'mentor.profile.professionalInfo': 'Профессиональная информация',
  'mentor.profile.professionalHint': 'Эти данные показываются родителям для знакомства с вами.',
  'mentor.profile.about': 'О себе',
  'mentor.profile.aboutPlaceholder': 'Ваш опыт, стиль преподавания, достижения...',
  'mentor.profile.skills': 'Навыки',
  'mentor.profile.grade': 'Уровень',
  'mentor.profile.gradeHint': 'Уровень устанавливает администратор — вы не можете изменить его самостоятельно.',
  'mentor.profile.saved': 'Сохранено',
  'mentor.profile.unsavedChanges': 'Есть несохранённые изменения',
  'mentor.profile.cancel': 'Отмена',
  'mentor.profile.save': 'Сохранить',
  'mentor.profile.security': 'Безопасность',
  'mentor.profile.password': 'Пароль',
  'mentor.profile.passwordHint': 'В целях безопасности пароль не изменяется здесь — он восстанавливается через код подтверждения, отправляемый на ваш email.',
  'mentor.profile.resetPassword': 'Восстановить пароль',
  'mentor.profile.endSession': 'Завершить сеанс',
  'mentor.profile.endSessionHint': 'Вы выйдете из аккаунта на этом устройстве.',
  'mentor.profile.logout': 'Выйти',
  'mentor.profile.enterFirstName': 'Введите имя',
  'mentor.profile.enterLastName': 'Введите фамилию',
  'mentor.profile.invalidEmail': 'Некорректный email',
  'mentor.profile.saveFailed': 'Не удалось сохранить',
  'mentor.sd.months': 'Янв,Фев,Мар,Апр,Май,Июн,Июл,Авг,Сен,Окт,Ноя,Дек',
  'mentor.sd.hw.graded': 'Оценено',
  'mentor.sd.hw.submitted': 'Сдано',
  'mentor.sd.hw.late': 'Сдано с опозданием',
  'mentor.sd.hw.missed': 'Не сдано',
  'mentor.sd.hw.pending': 'Срок не наступил',
  'mentor.sd.att.present': 'Присутствует',
  'mentor.sd.att.late': 'Опоздал',
  'mentor.sd.att.absent': 'Отсутствует',
  'mentor.sd.att.excused': 'По уважит.',
  'mentor.sd.homeworkKind': 'Домашнее задание',
  'mentor.sd.testKind': 'Тест',
  'mentor.sd.noChange': 'без изменений',
  'mentor.sd.vsPrevMonth': 'к прошлому мес.',
  'mentor.sd.studentNotFoundTitle': 'Ученик не найден',
  'mentor.sd.studentNotFoundHint': 'Возможно, он был отчислен из вашей группы.',
  'mentor.sd.toStudentsList': 'К списку учеников',
  'mentor.sd.allStudents': 'Все ученики',
  'mentor.sd.frozen': 'Заморожен',
  'mentor.sd.coins': 'Коины',
  'mentor.sd.stats': 'Статистика',
  'mentor.sd.missedTasks': '{{count}} заданий не выполнено',
  'mentor.sd.tabOverall': 'Общее',
  'mentor.sd.tabAttendance': 'Посещаемость',
  'mentor.sd.tabTests': 'Тесты',
  'mentor.sd.tabHomework': 'Домашнее задание',
  'mentor.sd.attendanceRing': 'Посещаемость',
  'mentor.sd.lessonsCount': '{{n}} / {{total}} уроков',
  'mentor.sd.homeworkRing': 'Домашнее задание',
  'mentor.sd.submittedCount': '{{n}} / {{total}} сдано',
  'mentor.sd.testsRing': 'Тесты',
  'mentor.sd.takenCount': '{{n}} / {{total}} пройдено',
  'mentor.sd.last6Months': 'Последние 6 мес.',
  'mentor.sd.avgGrade': 'Ср. оценка',
  'mentor.sd.gapNote': 'Разрыв линии — нет данных за этот месяц (не было уроков или заданий).',
  'mentor.sd.wellLearned': 'Хорошо усвоено',
  'mentor.sd.noGradedWorks': 'Нет оцененных работ',
  'mentor.sd.hasDifficulties': 'Есть сложности',
  'mentor.sd.noWeakTopics': 'Слабых тем нет — все работы выше 80%',
  'mentor.sd.byMonth': 'По месяцам',
  'mentor.sd.recentLessons': 'Последние уроки',
  'mentor.sd.attendanceNotMarked': 'Посещаемость не отмечена',
  'mentor.sd.totalLessons': '{{n}} уроков',
  'mentor.sd.avgScore': 'Средний балл',
  'mentor.sd.allTests': 'Все тесты',
  'mentor.sd.noTests': 'Нет тестов',
  'mentor.sd.notTaken': 'Не пройден',
  'mentor.sd.avgGradeByMonth': 'Ср. оценка — по месяцам',
  'mentor.sd.tasks': 'Задания',
  'mentor.sd.notSubmittedCount': 'Не сдано ({{count}})',
  'mentor.sd.submittedCountFilter': 'Сдано ({{count}})',
  'mentor.sd.all': 'Все',
  'mentor.sd.allTasksDone': 'Все задания выполнены',
  'mentor.sd.noTasks': 'Нет заданий',
  'mentor.sd.until': 'до',
  'mentor.sd.doneCount': '{{n}} / {{total}} сдано',
  'mentor.sd.noDataTooltip': 'нет данных',
  'mentor.coins.students': 'Ученики',
  'mentor.coins.nobodyFound': 'Никто не найден',
  'mentor.coins.noStudentsInGroup': 'В группе нет учеников',
  'mentor.coins.selectStudentTitle': 'Выберите ученика',
  'mentor.coins.selectStudentHint': 'Выберите ученика в списке слева для начисления или списания коинов.',
  'mentor.coins.operation': 'Операция с коинами',
  'mentor.coins.balance': 'Баланс',
  'mentor.coins.operationType': 'Тип операции',
  'mentor.coins.grant': 'Начислить',
  'mentor.coins.deduct': 'Списать',
  'mentor.coins.amount': 'Сумма',
  'mentor.coins.reason': 'Причина',
  'mentor.coins.reasonPlaceholder': 'За что?',
  'mentor.coins.genericError': 'Произошла ошибка',
  'mentor.coins.history': 'История операций',
  'mentor.coins.noOperations': 'Пока нет операций',
  'mentor.stats.bandWeak': 'Слабый',
  'mentor.stats.bandMid': 'Средний',
  'mentor.stats.bandGood': 'Хороший',
  'mentor.stats.bandTop': 'Отличный',
  'mentor.stats.studentsCount': '{{count}} ta',
  'mentor.stats.bandTitle': '{{band}}: {{count}} ученик(ов)',
  'mentor.stats.overallNote': 'Общий балл — посещаемость, домашние задания и тесты (среднее). Всего {{total}} ученик(ов).',
  'mentor.stats.overall': 'Общий балл',
  'mentor.stats.attendance': 'Посещаемость',
  'mentor.stats.homework': 'Домашние задания',
  'mentor.stats.tests': 'Тесты',
  'mentor.stats.noStudentsInGroup': 'В группе нет учеников',
  'mentor.stats.distribution': 'Распределение успеваемости',
  'mentor.stats.topStudents': 'Лучшие по успеваемости',
  'mentor.stats.needsAttention': 'Требуют внимания',
  'mentor.stats.noRiskStudents': 'Нет учеников с баллом ниже 60%',
  'mentor.stats.tasksAttendance': '{{done}}/{{total}} заданий · посещаемость {{rate}}%',
  'mentor.stats.allStudents': 'Все ученики',
  'mentor.stats.colStudent': 'Ученик',
  'mentor.stats.colAttendance': 'Посещаемость',
  'mentor.stats.colHomework': 'Домашние задания',
  'mentor.stats.colTests': 'Тесты',
  'mentor.stats.colOverall': 'Общий',
  'mentor.stats.frozen': 'Заморожен',
  'mentor.stats.doneCount': '{{done}}/{{total}} сдано',
  'mentor.stats.takenCount': '{{taken}}/{{total}} пройдено',
  'mentor.tests.questionN': 'ВОПРОС {{n}}',
  'mentor.tests.removeQuestion': 'Удалить вопрос {{n}}',
  'mentor.tests.questionText': 'Текст вопроса',
  'mentor.tests.markCorrect': 'Отметить как правильный ответ',
  'mentor.tests.optionCorrect': 'Вариант {{n}} — правильный',
  'mentor.tests.optionN': '{{n}}-вариант',
  'mentor.tests.removeOption': 'Удалить вариант {{n}}',
  'mentor.tests.addOption': 'Добавить вариант',
  'mentor.tests.results': 'Результаты',
  'mentor.tests.close': 'Закрыть',
  'mentor.tests.nobodyTookTest': 'Пока никто не проходил тест',
  'mentor.tests.passed': 'Прошли',
  'mentor.tests.avgScore': 'Средний балл',
  'mentor.tests.notPassed': 'Не прошёл',
  'mentor.tests.enterTitle': 'Введите название теста',
  'mentor.tests.enterDuration': 'Введите продолжительность (минуты)',
  'mentor.tests.needOneQuestion': 'Нужен хотя бы один вопрос',
  'mentor.tests.questionEmpty': 'Вопрос {{n}}: текст пустой',
  'mentor.tests.needTwoOptions': 'Вопрос {{n}}: нужно минимум 2 варианта',
  'mentor.tests.emptyOption': 'Вопрос {{n}}: есть пустой вариант',
  'mentor.tests.correctNotChosen': 'Вопрос {{n}}: правильный ответ не выбран',
  'mentor.tests.saveFailed': 'Не удалось сохранить тест',
  'mentor.tests.tests': 'Тесты',
  'mentor.tests.newTest': 'Новый тест',
  'mentor.tests.noTestsInGroup': 'В этой группе пока нет тестов',
  'mentor.tests.noTestsHint': 'Нажмите кнопку «Новый тест», чтобы создать первый.',
  'mentor.tests.questionsCount': '{{count}} вопрос(ов)',
  'mentor.tests.minutes': '{{n}} мин',
  'mentor.tests.testTitle': 'Название теста',
  'mentor.tests.titlePlaceholder': 'Например: Present Simple',
  'mentor.tests.duration': 'Длительность (мин)',
  'mentor.tests.coinReward': 'Награда коинами',
  'mentor.tests.addQuestion': 'Добавить вопрос',
  'mentor.tests.cancel': 'Отмена',
  'mentor.tests.save': 'Сохранить',

  // mentor/group/AttendanceTab.jsx
  'mentor.att.notSaved': 'Не сохранено — попробовать снова',
  'mentor.att.saving': 'Сохранение...',
  'mentor.att.saved': 'Сохранено',
  'mentor.att.saveFailed': 'Не сохранено — проверьте подключение',
  'mentor.att.lessonReason': 'Урок',
  'mentor.att.present': 'Был',
  'mentor.att.absent': 'Не был',
  'mentor.att.unmarked': 'Не отмечено',
  'mentor.att.correctedByAdmin': 'Исправлено администратором',
  'mentor.att.markAllPresentToday': 'Сегодня все были',
  'mentor.att.emptyStudentsTitle': 'В этой группе нет учеников',
  'mentor.att.studentCol': 'Ученик',
  'mentor.att.todayCol': 'Сегодня',
  'mentor.att.totalCol': 'Всего',
  'mentor.att.budgetTooltip': 'На месяц: {{allocated}} коинов ({{students}} учеников × {{perStudent}}). Потрачено: {{spent}}',
  'mentor.att.dayNumber': '{{day}}-е число',
  'mentor.att.cannotEditSuffix': '(нельзя изменить)',
  'mentor.att.editOnlyToday': 'Отмечать можно только текущий день',
  'mentor.att.creditedToday': 'Начислено сегодня',
  'mentor.att.totalBalance': 'Общий баланс',
  'mentor.att.coinAmountFor': 'Количество коинов для {{name}}',
  'mentor.att.grantCoinsAria': 'Начислить коины: {{name}}',
  'mentor.att.grantCoinsTitle': 'Начислить коины',

  // people/Directory.jsx
  'people.title': 'Люди и клиенты',
  'people.subtitle': 'Единая база сотрудников, родителей и учеников с доступом по вашей роли',
  'people.searchPlaceholder': 'Имя, телефон или email',
  'people.allRoles': 'Все роли',
  'people.loading': 'Загрузка базы…',
  'people.loadError': 'Не удалось загрузить базу',
  'people.emptyFilter': 'По вашему фильтру никого нет',
  'people.inSelection': 'Людей в выборке',
  'people.students': 'Учеников',
  'people.debt': 'Долг по счетам',
  'people.overdue': 'Просрочено',
  'people.person': 'Человек',
  'people.role': 'Роль',
  'people.branch': 'Филиал',
  'people.status': 'Статус',
  'people.paid': 'Оплачено',
  'people.noContact': 'Контакт не указан',
  'people.platform': 'Платформа',
  'people.childrenCount': 'Детей: {{count}}',

  // status (format.js: ORG_STATUS/USER_STATUS/ADMIN_STATUS/LEAD_STATUS)
  'status.active': 'Активен',
  'status.trial': 'Триал',
  'status.frozen': 'Заморожен',
  'status.dropped': 'Удалён',
  'status.new': 'Новая',
  'status.contacted': 'Связались',
  'status.onboarded': 'Онбординг',
  'status.rejected': 'Отклонена',

  // roles
  'role.seo': 'SEO (Руководитель)',
  'role.admin': 'Администратор',
  'role.branch_manager': 'Управляющий филиалом',
  'role.finance_manager': 'Финансовый менеджер',
  'role.mentor': 'Преподаватель',
  'role.methodist': 'Методист',
  'role.student': 'Ученик',
  'role.parent': 'Родитель',
  'role.employee': 'Сотрудник',

  // notifications
  'notifications.title': 'Уведомления',
  'notifications.empty': 'Нет новых уведомлений',
  'notifications.emptyDesc': 'Непрочитанные сообщения появятся здесь.',
  'notifications.new': 'новых',
  'notifications.allMessages': 'Все сообщения',
  'notifications.newMessage': 'Новое сообщение',
  'notifications.soundOn': 'Звук включён',
  'notifications.soundOff': 'Звук выключен',
  'notifications.muteSound': 'Выключить звук',
  'notifications.unmuteSound': 'Включить звук',

  // kpi & dashboard
  'kpi.income': 'Доход за месяц',
  'kpi.expenses': 'Расход за месяц',
  'kpi.salaries': 'Зарплаты за месяц',
  'kpi.profit': 'Чистая прибыль',
  'kpi.netProfit': 'Чистая прибыль',
  'kpi.orgIncome': 'Доход организации',
  'kpi.orgExpenses': 'Расход организации',
  'kpi.orgProfit': 'Прибыль организации',
  'kpi.students': 'Студенты',
  'kpi.groups': 'Группы',
  'kpi.mentors': 'Менторы',
  'kpi.debt': 'Задолженность',
  'kpi.attendance': 'Посещаемость',

  // dashboard details
  'dash.branchStats': 'Показатели филиала',
  'dash.activeStudents': 'Активные студенты',
  'dash.groups': 'Группы',
  'dash.overdueInvoices': 'Просроченные счета',
  'dash.recentPayments': 'Последние оплаты',
  'dash.noPayments': 'Пока нет оплат',
  'dash.student': 'Студент',
  'dash.reminders': 'Напоминания',
  'dash.overduePaymentsTitle': 'Просроченные платежи',
  'dash.overduePaymentsDesc': 'В данный момент {{count}} счетов просрочены. Контролируйте оплаты.',
  'dash.activeStudentsTitle': 'Активные ученики',
  'dash.activeStudentsDesc': 'В филиале обучается {{count}} активных учеников.',
  'dash.thisMonth': 'За этот месяц',
  'dash.income': 'Доход',
  'dash.expenses': 'Расход',
  'dash.profit': 'Прибыль',
  'dash.loadError': 'Ошибка загрузки',
  'dash.title': 'Панель управления',
  'dash.welcome': 'Добро пожаловать',
  'dash.bmSubtitle': 'общее состояние филиала',
  'dash.incomeThisMonth': 'Доход за этот месяц',
  'dash.expensesThisMonth': 'Расход за этот месяц',
  'dash.debtDesc': 'просроченные платежи',
  'dash.profitFormula': 'доход − расход',
  'dash.vsPrevMonth': 'по сравнению с прошлым месяцем',
  'dash.mainBranch': 'Главный филиал',
  'dash.addressNotSet': 'Адрес не указан',
  'dash.phoneNotSet': 'Телефон не указан',
  'dash.workHoursNotSet': 'Время работы не указано',
  'dash.staff': 'Сотрудники',
  'dash.recentBranchPayments': 'Последние платежи',
  'dash.noPaymentsYet': 'Пока нет платежей',
  'dash.last6Months': 'Последние 6 месяцев: доход vs расход',

  // branch details
  'branch.about': 'О филиале',
  'branch.locationStats': 'расположение и статистика',
  'branch.contacts': 'Контакты',
  'branch.address': 'Адрес',
  'branch.phone': 'Телефон',
  'branch.financeTotal': 'Финансы (итого)',
  'branch.tgCardTitle': 'Группа родителей (Telegram)',
  'branch.tgConnected': 'Группа подключена',
  'branch.tgDisconnect': 'Отключить',
  'branch.tgDesc': 'Сообщения о посещаемости и успеваемости будут автоматически отправляться в эту группу. Сначала добавьте бота в группу, затем получите код для подключения.',
  'branch.tgGetCode': 'Получить код подключения',
  'branch.tgStep1': 'Добавьте бота в группу',
  'branch.tgStep2': 'Отправьте следующую команду в саму группу',
  'branch.tgCodeValid': 'Код действителен {{min}} минут.',
  'branch.notFound': 'Данные филиала не найдены',
  'branch.unlinkConfirm': 'Вы действительно хотите отключить группу?',

  // tax
  'tax.title': 'Налоговый отчёт',
  'tax.subtitle': 'Налоговые начисления по филиалам и организации',
  'tax.export': 'Экспорт CSV',
  'tax.due': 'Итого к уплате',
  'tax.tableTitle': 'Налоги по филиалам',
  'tax.netProfit': 'Чистая прибыль',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Выберите язык',

  // ---------- finance-manager panel (ранее pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Дашборд',
  'finance.nav.income': 'Доходы',
  'finance.nav.expenses': 'Расходы',
  'finance.nav.salaries': 'Зарплаты',
  'finance.nav.reports': 'Отчёты',
  'finance.nav.report': 'Отчёт',
  'finance.nav.admins': 'Сотрудники',
  'finance.nav.finance': 'Финансы',
  'finance.nav.analytics': 'Аналитика',
  'finance.nav.stats': 'Статистика',
  'finance.nav.tax': 'Налоги',
  'finance.nav.taxTitle': 'Налоговый отчёт',
  'finance.nav.taxNdss': 'НДС 20%',
  'finance.nav.taxSocNalog': 'Соцналог 10%',
  'finance.nav.taxOtzyvnoyNalog': 'Оборотный налог 1.5%',
  'finance.nav.taxTotal': 'Итого',
  'finance.nav.taxOrg': 'Организация',
  'finance.nav.allStudents': 'Все ученики',
  'finance.nav.allGroups': 'Все группы',
  'finance.nav.attendance': 'Посещаемость',
  'finance.nav.more': 'Ещё',
  'finance.nav.discipline': 'Дисциплина',
  'finance.nav.announcements': 'Объявления',
  'finance.nav.reminders': 'Напоминания',
  'finance.nav.audit': 'Аудит',
  'finance.nav.settings': 'Настройки',
  'finance.nav.students': 'Студенты',
  'finance.nav.groups': 'Группы',
  'finance.nav.mentors': 'Менторы',
  'finance.nav.chat': 'Чат',
  'finance.nav.payments': 'Платежи',
  'finance.nav.branch': 'Филиал',
  'finance.nav.branches': 'Филиалы',
  'finance.nav.allBranches': 'Все филиалы',
  'finance.nav.noBranches': 'Филиалов нет',
  'finance.nav.noGroups': 'Групп нет',
  'finance.nav.methodistTypes': 'Типы обучения',
  'finance.nav.main': 'осн',
  'finance.nav.collapse': 'Свернуть',
  'finance.nav.pin': 'Закрепить',
  'finance.nav.collapsePanel': 'Свернуть панель',
  'finance.nav.pinPanel': 'Закрепить панель',

  'finance.kpi.income': 'Доход за месяц',
  'finance.kpi.expenses': 'Расход за месяц',
  'finance.kpi.salaries': 'Зарплаты за месяц',
  'finance.kpi.netProfit': 'Чистая прибыль',
  'finance.kpi.orgIncome': 'Доход организации',
  'finance.kpi.orgExpenses': 'Расход организации',
  'finance.kpi.orgProfit': 'Прибыль организации',

  'finance.common.total': 'Итого',
  'finance.common.share': 'Доля',
  'finance.common.amount': 'Сумма',
  'finance.common.date': 'Дата',
  'finance.common.status': 'Статус',
  'finance.common.method': 'Метод',
  'finance.common.note': 'Примечание',
  'finance.common.category': 'Категория',
  'finance.common.employee': 'Сотрудник',
  'finance.common.position': 'Должность',
  'finance.common.branch': 'Филиал',
  'finance.common.allBranches': 'Все филиалы',
  'finance.common.month': 'Месяц',
  'finance.common.period': 'Период',
  'finance.common.vsPrev': 'к прошлому месяцу',
  'finance.common.noData': 'Нет данных',
  'finance.common.students': 'Ученики',
  'finance.common.groups': 'Группы',
  'finance.common.staff': 'Сотрудники',
  'finance.common.loading': 'Загрузка…',
  'finance.common.page': 'Стр.',
  'finance.common.save': 'Сохранить',
  'finance.common.cancel': 'Отмена',
  'finance.common.add': 'Добавить',
  'finance.common.edit': 'Изменить',
  'finance.common.delete': 'Удалить',
  'finance.common.confirmDelete': 'Удалить эту запись?',

  'finance.dash.title': 'Финансовый дашборд',
  'finance.dash.subtitle': 'Вся организация · по филиалам и месяцам',
  'finance.dash.trendChart': 'Доходы и расходы организации',
  'finance.dash.profitLine': 'Прибыль',
  'finance.dash.branchShare': 'Доля филиалов в доходе',
  'finance.dash.monthlyProfit': 'Чистая прибыль за 6 месяцев',
  'finance.dash.viewReports': 'Подробный отчёт',
  'finance.dash.days30Org': 'Последние 30 дней · вся организация',
  'finance.dash.chartSub': 'Фактические поступления за 30 дней',
  'finance.dash.branches': 'Филиалы',

  'finance.income.title': 'Доходы',
  'finance.income.subtitle': 'Поступления по филиалам и месяцам',
  'finance.income.tableTitle': 'Платежи',
  'finance.income.student': 'Ученик',
  'finance.income.group': 'Группа',

  'finance.expenses.title': 'Расходы',
  'finance.expenses.subtitle': 'Расходы по филиалам и категориям',
  'finance.expenses.catBreakdown': 'По категориям',
  'finance.expenses.add': 'Новый расход',
  'finance.expenses.edit': 'Изменить расход',
  'finance.expenses.orgWide': 'На всю организацию',
  'finance.expenses.categoryPlaceholder': 'Например: Аренда',

  'finance.salaries.title': 'Зарплаты',
  'finance.salaries.subtitle': 'Фонд оплаты труда по филиалам',
  'finance.salaries.payroll': 'ФОТ за месяц',
  'finance.salaries.sheetTitle': 'Ведомость',

  'finance.reports.title': 'Отчёты',
  'finance.reports.subtitle': 'Сводка по филиалам за месяц',
  'finance.reports.org': 'Организация',
  'finance.reports.cashFlow': 'Денежный поток',
  'finance.reports.branchTable': 'Филиалы · сводка',
  'finance.reports.branchNet': 'Нетто по филиалам',
  'finance.reports.branchDetail': 'Детализация по филиалам',
  'finance.reports.net': 'Чистая прибыль',
  'finance.reports.opProfit': 'Операционная прибыль',
  'finance.reports.vsPrevMonth': 'к прошлому месяцу',
  'finance.reports.export': 'Экспорт CSV',
  'finance.reports.paymentsThisMonth': 'Платежи · этот месяц',
  'finance.reports.byStatus': 'По статусу оплаты',
  'finance.reports.byMethod': 'По способу оплаты',
  'finance.reports.overdueAmount': 'Просрочено',
  'finance.reports.expensesByCategory': 'Расходы по категориям',
  'finance.reports.subtitleLive': 'Реальные данные backend · последние 30 дней',
  'finance.reports.incomeLabel': 'Поступления за 30 дней',
  'finance.reports.activeStudents': 'Активные ученики',
  'finance.reports.last30days': 'Последние 30 дней',
  'finance.reports.debtLabel': 'Долг',
  'finance.reports.incomeDebtByBranch': 'Поступления и долги по филиалам',
  'finance.reports.methodsSubtitle': 'Завершённые транзакции',
  'finance.reports.noCompletedPayments': 'Нет завершённых платежей',
  'finance.reports.orgRow': 'ОРГАНИЗАЦИЯ',
  'finance.method.cash': 'Наличные',
  'finance.method.card': 'Карта',
  'finance.method.transfer': 'Перевод',
  'finance.method.bankTransfer': 'Банковский перевод',
  'finance.salaryStatus.draft': 'Черновик',
  'finance.salaryStatus.approved': 'Утверждена',
  'finance.salaryStatus.paid': 'Выплачена',

  'finance.settings.title': 'Настройки',
  'finance.settings.subtitle': 'Профиль и предпочтения',
  'finance.settings.personal': 'Личные данные',
  'finance.settings.personalSub': 'Эти данные отображаются в системе и сохраняются в вашем профиле',
  'finance.settings.firstName': 'Имя',
  'finance.settings.lastName': 'Фамилия',
  'finance.settings.phone': 'Телефон',
  'finance.settings.city': 'Город',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Сохранить',
  'finance.settings.saved': 'Настройки сохранены',
  'finance.settings.lang': 'Язык интерфейса',
  'finance.settings.langSub': 'Применяется сразу, на весь интерфейс панели',
  'finance.settings.security': 'Безопасность',
  'finance.settings.securitySub': 'Смена пароля и данные учётной записи управляются через основную учётную запись',
  'methodist.app.name': "Контент-студия",
  'methodist.common.loading_error': "Ошибка загрузки",
  'methodist.common.loading_failed': "Не удалось загрузить данные",
  'methodist.common.retry': "Повторить",
  'methodist.common.no_data': "Нет данных",
  'methodist.common.all': "Все",
  'methodist.common.back': "Назад",
  'methodist.common.save': "Сохранить",
  'methodist.common.cancel': "Отмена",
  'methodist.common.delete': "Удалить",
  'methodist.common.edit': "Изменить",
  'methodist.common.add': "Добавить",
  'methodist.common.create': "Создать",
  'methodist.common.close': "Закрыть",
  'methodist.common.copy': "Дублировать",
  'methodist.common.tests_count': "{{count}} тестов",
  'methodist.common.attempts_count': "{{count}} попыток",
  'methodist.kpi.types': "Типы обучения",
  'methodist.kpi.topics': "Всего тем",
  'methodist.kpi.tests': "Тестов",
  'methodist.kpi.hw': "Домашние задания",
  'methodist.dashboard.subtitle': "Создавайте и управляйте учебными материалами",
  'methodist.dashboard.topics_count': "{{count}} тем",
  'methodist.dashboard.avg_score': "Средний балл по тестам",
  'methodist.dashboard.great': "Отлично",
  'methodist.dashboard.good': "Хорошо",
  'methodist.dashboard.need_work': "Нужна работа",
  'methodist.dashboard.types_section': "Типы обучения",
  'methodist.dashboard.all_types': "Все типы",
  'methodist.dashboard.no_types': "Нет типов обучения",
  'methodist.dashboard.no_types_hint': "Создайте первый тип, чтобы начать",
  'methodist.dashboard.create_type': "Создать тип",
  'methodist.analytics.title': "Аналитика успеваемости",
  'methodist.analytics.subtitle': "Статистика сложностей по предметам и тестам",
  'methodist.analytics.donut_aria': "Общий средний балл {{num}}%",
  'methodist.analytics.total_tests': "Всего тестов",
  'methodist.analytics.total_attempts': "Всего попыток",
  'methodist.analytics.overall_avg': "Общий средний",
  'methodist.analytics.performance': "Успеваемость",
  'methodist.analytics.score_good': "Хорошо",
  'methodist.analytics.score_avg': "Средне",
  'methodist.analytics.score_hard': "Сложно",
  'methodist.analytics.subject_difficulty': "Сложность предметов",
  'methodist.analytics.by_avg_score': "По среднему баллу",
  'methodist.analytics.low_tests': "Тесты с низкими результатами",
  'methodist.analytics.top5': "Топ-5 по сложности",
  'methodist.analytics.all_tests': "Все тесты",
  'methodist.analytics.full_table': "Полная таблица результатов",
  'methodist.analytics.col_title': "Название",
  'methodist.analytics.col_group': "Группа",
  'methodist.analytics.col_branch': "Филиал",
  'methodist.analytics.col_attempts': "Попытки",
  'methodist.analytics.col_avg': "Средний балл",
  'methodist.analytics.general_subject': "Общее",
  'methodist.types.title': "Типы обучения",
  'methodist.types.subtitle': "Направления подготовки: Backend, Frontend, Python и др.",
  'methodist.types.add': "Добавить тип",
  'methodist.types.no_types': "Нет типов обучения",
  'methodist.types.no_types_hint': "Создайте первый тип, чтобы начать наполнять контентом",
  'methodist.types.create_first': "Создать первый тип",
  'methodist.types.topics_count': "{{count}} тем",
  'methodist.types.description_short': "описание",
  'methodist.types.archive_tooltip': "Архивировать",
  'methodist.types.open_topics': "Открыть темы",
  'methodist.types.archive_confirm': "Архивировать тип?",
  'methodist.types.archive_hidden': "«{{name}}» будет скрыт",
  'methodist.types.archive': "Архивировать",
  'methodist.types.new_title': "Новый тип обучения",
  'methodist.types.new_hint': "Создайте направление подготовки",
  'methodist.types.name_label': "Название *",
  'methodist.types.name_placeholder': "Например: Backend",
  'methodist.types.name_required': "Название обязательно",
  'methodist.types.description_label': "Описание",
  'methodist.types.description_placeholder': "Кратко о направлении...",
  'methodist.types.icon_label': "Иконка (emoji)",
  'methodist.types.ai_review_label': "Умный разбор (AI)",
  'methodist.types.ai_review_hint': "AI будет разбирать код учеников по практическим заданиям этого курса. Включайте только там, где практика — реальный читаемый код (HTML/CSS/JS), не для курсов с большим числом файлов.",
  'methodist.topics.breadcrumb_types': "Типы обучения",
  'methodist.topics.breadcrumb_topics': "Темы",
  'methodist.topics.title': "Темы",
  'methodist.topics.subtitle': "Уроки и тесты внутри направления",
  'methodist.topics.add': "Добавить тему",
  'methodist.topics.create': "Создать тему",
  'methodist.topics.no_topics': "Нет тем",
  'methodist.topics.no_topics_hint': "Создайте первую тему в этом направлении",
  'methodist.topics.lessons_count': "{{count}} уроков",
  'methodist.topics.description_short': "описание",
  'methodist.topics.edit_tooltip': "Редактировать",
  'methodist.topics.delete_tooltip': "Удалить",
  'methodist.topics.archive_tooltip': "Архивировать",
  'methodist.topics.lessons_and_tests': "Уроки и тесты",
  'methodist.topics.archive_confirm': "Архивировать тему?",
  'methodist.topics.archive_hidden': "«{{name}}» будет скрыта",
  'methodist.topics.archive': "Архивировать",
  'methodist.topics.new_title': "Новая тема",
  'methodist.topics.new_hint': "Добавьте тему в направление",
  'methodist.topics.name_label': "Название *",
  'methodist.topics.name_placeholder': "Например: React Hooks",
  'methodist.topics.name_required': "Название обязательно",
  'methodist.topics.description_label': "Описание",
  'methodist.topics.description_placeholder': "О чём эта тема...",
  'methodist.topics.description': "Описание",
  'methodist.topics.video_label': "Видео темы",
  'methodist.topics.video_mode_url': "Ссылка",
  'methodist.topics.video_mode_file': "Файл",
  'methodist.topics.video_url_placeholder': "Ссылка на YouTube",
  'methodist.topics.video_upload_hint': "или перетащите видео сюда",
  'methodist.topics.video_no_file': "Видео не загружено",
  'methodist.topics.video_remove': "Удалить видео",
  'methodist.topics.coin_reward_label': "Монет за просмотр видео",
  'methodist.topics.coin_reward_hint': "Начисляются студенту целиком, один раз, когда видео досмотрено до конца",
  'methodist.topics.video_after_create_hint': "Загрузка файлом станет доступна после создания темы — сначала сохраните",
  'methodist.lessons.breadcrumb_types': "Типы",
  'methodist.lessons.breadcrumb_topics': "Темы",
  'methodist.lessons.breadcrumb_lessons': "Уроки",
  'methodist.lessons.title': "Уроки",
  'methodist.lessons.subtitle': "Тесты и практические задания внутри темы",
  'methodist.lessons.create': "Создать урок",
  'methodist.lessons.badge_test': "Тест",
  'methodist.lessons.badge_practical': "Практика",
  'methodist.lessons.no_lessons': "Нет уроков",
  'methodist.lessons.no_lessons_hint': "Создайте первый тест или практическое задание",
  'methodist.lessons.questions_count': "{{count}} вопросов",
  'methodist.lessons.requirements_count': "{{count}} требований",
  'methodist.lessons.copy_tooltip': "Копировать урок",
  'methodist.lessons.archive_tooltip': "Архивировать",
  'methodist.lessons.edit_tooltip': "Редактировать",
  'methodist.lessons.archive_confirm': "Архивировать урок?",
  'methodist.lessons.archive': "Архивировать",
  'methodist.lessons.new_title': "Новый урок",
  'methodist.lessons.new_hint': "Создайте тест или практическое задание",
  'methodist.lessons.field_title': "Название *",
  'methodist.lessons.title_placeholder': "Например: HTML Теги",
  'methodist.lessons.title_required': "Название обязательно",
  'methodist.lessons.lesson_type_label': "Тип урока",
  'methodist.lessons.type_test': "Тест (A/B/C/D)",
  'methodist.lessons.type_practical': "Практическое задание",
  'methodist.lessons.desc_label': "Описание задания",
  'methodist.lessons.desc_placeholder': "Опишите задание для студента...",
  'methodist.lessons.instruction_label': "Инструкция / Объяснение",
  'methodist.lessons.instruction_placeholder': "Краткое объяснение темы...",
  'methodist.lessons.coin_label': "Награда (коины)",
  'methodist.lessons.create_and_edit': "Создать и редактировать",
  'methodist.editor.title': "Редактор урока",
  'methodist.editor.subtitle': "Тест или практическое задание",
  'methodist.editor.settings_tooltip': "Параметры урока",
  'methodist.editor.test_count': "Тест · {{count}} вопросов",
  'methodist.editor.type_practical': "Практическое задание",
  'methodist.editor.requirements_title': "Обязательные требования",
  'methodist.editor.requirements_hint': "Что студент должен выполнить в задании",
  'methodist.editor.requirement_text': "Требование / условие *",
  'methodist.editor.requirement_points': "Баллы",
  'methodist.editor.add_requirement': "Добавить требование",
  'methodist.editor.save_requirements': "Сохранить требования",
  'methodist.editor.requirements_total': "Итого {{points}} баллов",
  'methodist.editor.no_requirements': "Требований пока нет. Добавьте первое.",
  'methodist.editor.video_label': "Видео-материал:",
  'methodist.editor.task_desc': "Описание задания",
  'methodist.editor.attachment_label': "Вложенный файл к заданию:",
  'methodist.editor.no_file': "Файл не прикреплен",
  'methodist.editor.upload_drop_hint': "или перетащите файл сюда",
  'methodist.editor.instruction': "Инструкция / Объяснение",
  'methodist.editor.edit_question': "Редактировать вопрос",
  'methodist.editor.add_question': "Добавить вопрос",
  'methodist.editor.question_type': "Тип вопроса",
  'methodist.editor.question_text': "Текст вопроса *",
  'methodist.editor.question_placeholder': "Какой тег используется для заголовка?",
  'methodist.editor.option_label': "Вариант {{letter}}",
  'methodist.editor.correct_answer': "Правильный ответ *",
  'methodist.editor.batch_title': "Быстрое создание",
  'methodist.editor.empty_questions': "пустых вопросов",
  'methodist.editor.questions': "Вопросы",
  'methodist.editor.no_questions': "Нет вопросов. Добавьте первый вопрос выше.",
  'methodist.editor.delete_confirm': "Удалить вопрос?",
  'methodist.editor.settings_title': "Параметры урока",
  'methodist.editor.settings_name': "Название *",
  'methodist.editor.video_url_label': "Видео-урок (YouTube/S3 ссылка)",
  'methodist.editor.coin_label': "Награда (коины)",
  'methodist.editor.question_required': "Вопрос обязателен",
  'methodist.editor.option_required': "Вариант {{letter}} обязателен",
  'methodist.editor.correct_answer_required': "Правильный ответ обязателен",
  'methodist.editor.title_required': "Название обязательно",
  'methodist.editor.invalid_url': "Некорректная ссылка",
  'methodist.editor.description_required_practical': "Для практического задания описание обязательно — AI-разбор опирается именно на него",
  'methodist.editor.question_prefix': "Вопрос",
  'methodist.editor.type_choice': "Варианты",
  'methodist.editor.type_riddle': "Загадка",
  'methodist.editor.type_open': "Вопрос и ответ",
  'methodist.profile.role_methodist': "Методист",
  'methodist.profile.email': "Email",
  'methodist.profile.branch': "Филиал",
  'methodist.profile.registered': "Зарегистрирован",
  'methodist.profile.load_error': "Ошибка загрузки профиля",
  'methodist.profile.personal_data': "Личные данные",
  'methodist.profile.personal_data_hint': "Эти данные видит администратор организации.",
  'methodist.profile.first_name': "Имя",
  'methodist.profile.last_name': "Фамилия",
  'methodist.profile.email_hint': "Вы входите в систему с этим email, код восстановления пароля также приходит на этот адрес.",
  'methodist.profile.saved': "Сохранено",
  'methodist.profile.dirty': "Есть несохранённые изменения",
  'methodist.profile.enter_name': "Введите имя",
  'methodist.profile.enter_last': "Введите фамилию",
  'methodist.profile.invalid_email': "Некорректный email",
  'methodist.profile.save_failed': "Не удалось сохранить",
  'methodist.profile.security': "Безопасность",
  'methodist.profile.password': "Пароль",
  'methodist.profile.password_hint': "В целях безопасности пароль не изменяется здесь — он восстанавливается через код подтверждения, отправляемый на ваш email.",
  'methodist.profile.reset_password': "Восстановить пароль",
  'methodist.profile.end_session': "Завершить сеанс",
  'methodist.profile.session_hint': "Вы выйдете из аккаунта на этом устройстве.",
  'methodist.profile.logout': "Выйти",

  // admin/Dashboard.jsx
  'admin.dash.title': 'Дашборд',
  'admin.dash.loadError': 'Ошибка загрузки: {{message}}',
  'admin.dash.subtitle': 'Сегодня {{today}} · обзор вашего филиала',
  'admin.dash.branchStats': 'Показатели филиала',
  'admin.dash.activeStudents': 'Активные студенты',
  'admin.dash.groups': 'Группы',
  'admin.dash.overdueInvoices': 'Просроченные счета',
  'admin.dash.recentPayments': 'Последние оплаты',
  'admin.dash.noPayments': 'Пока нет оплат',
  'admin.dash.student': 'Студент',
  'admin.dash.thisMonth': 'За этот месяц',
  'admin.dash.revenue': 'Доход',
  'admin.dash.expenses': 'Расход',
  'admin.dash.profit': 'Прибыль',
  'admin.dash.studentsThisMonth': 'Ученики за этот месяц',
  'admin.dash.arrived': 'Пришло',
  'admin.dash.left': 'Ушло (архив)',
  'admin.dash.netGrowth': 'Чистый прирост',

  // admin/Shop.jsx
  'admin.shop.statusPending': 'Ожидает',
  'admin.shop.statusFulfilled': 'Выдан',
  'admin.shop.statusCancelled': 'Отменён',
  'admin.shop.fromSeo': 'От SEO',
  'admin.shop.branchItem': 'Товар филиала',
  'admin.shop.archived': 'В архиве',
  'admin.shop.coinsPrice': '{{price}} коинов',
  'admin.shop.stockLeft': 'Остаток: {{count}} шт.',
  'admin.shop.newStock': 'Новый остаток',
  'admin.shop.update': 'Обновить',
  'admin.shop.orderCoins': '{{name}} · {{price}} коинов',
  'admin.shop.fulfill': 'Выдать',
  'admin.shop.cancel': 'Отменить',
  'admin.shop.restockFailed': 'Не удалось обновить остаток',
  'admin.shop.createFailed': 'Не удалось добавить товар',
  'admin.shop.fulfillFailed': 'Не удалось отметить выдачу',
  'admin.shop.cancelFailed': 'Не удалось отменить заказ',
  'admin.shop.confirmCancel': 'Отменить заказ? Коины вернутся студенту, товар вернётся на склад.',
  'admin.shop.title': 'Магазин',
  'admin.shop.subtitle': 'Общие товары SEO и локальные товары вашего филиала.',
  'admin.shop.newItem': 'Новый товар',
  'admin.shop.itemsCount': 'Товаров',
  'admin.shop.ordersCount': 'Заказов',
  'admin.shop.pendingFulfillment': 'Ожидают выдачи',
  'admin.shop.tabItems': 'Товары',
  'admin.shop.tabOrders': 'Заказы',
  'admin.shop.noItemsTitle': 'Пока нет товаров',
  'admin.shop.noItemsHint': 'SEO ещё не завёл товары для этого филиала',
  'admin.shop.noOrdersTitle': 'Пока нет заказов',
  'admin.shop.noOrdersHint': 'Студенты ещё не покупали товары',
  'admin.shop.newBranchItem': 'Новый товар филиала',
  'admin.shop.newBranchItemHint': 'Будет доступен только в вашем филиале',
  'admin.shop.namePlaceholder': 'Название',
  'admin.shop.imagePlaceholder': 'Ссылка на фото (необязательно)',
  'admin.shop.pricePlaceholder': 'Цена',
  'admin.shop.stockPlaceholder': 'Остаток',
  'admin.shop.cancelBtn': 'Отмена',
  'admin.shop.add': 'Добавить',

  // admin/Mentors.jsx
  'admin.mentors.gradeNotSet': 'Не задан',
  'admin.mentors.gradeTooltip': 'Грейд назначает SEO',
  'admin.mentors.edit': 'Изменить',
  'admin.mentors.chatTooltip': 'Написать в чат',
  'admin.mentors.title': 'Менторы',
  'admin.mentors.subtitle': 'Преподаватели филиала',
  'admin.mentors.export': 'Экспорт',
  'admin.mentors.addMentor': 'Добавить ментора',
  'admin.mentors.total': 'Всего',
  'admin.mentors.active': 'Активные',
  'admin.mentors.frozen': 'Заморожены',
  'admin.mentors.loadError': 'Ошибка загрузки: {{message}}',
  'admin.mentors.emptyTitle': 'Нет менторов',
  'admin.mentors.emptyHint': 'Добавьте первого преподавателя',
  'admin.mentors.editTitle': 'Изменить ментора',
  'admin.mentors.newTitle': 'Новый ментор',
  'admin.mentors.firstNamePlaceholder': 'Имя',
  'admin.mentors.lastNamePlaceholder': 'Фамилия',
  'admin.mentors.emailPlaceholder': 'Email (для входа)',
  'admin.mentors.genericError': 'Ошибка',
  'admin.mentors.cancel': 'Отмена',
  'admin.mentors.save': 'Сохранить',
  'admin.mentors.createdTitle': 'Ментор создан',
  'admin.mentors.createdHint': 'Пароль показывается один раз — передайте его ментору сейчас.',
  'admin.mentors.emailLabel': 'Email',
  'admin.mentors.passwordLabel': 'Пароль',
  'admin.mentors.done': 'Готово',

  // admin/Schedule.jsx
  'admin.schedule.oddDays': 'Нечётные дни',
  'admin.schedule.evenDays': 'Чётные дни',
  'admin.schedule.otherDays': 'Остальные',
  'admin.schedule.otherSubject': 'Другие',
  'admin.schedule.selectDay': 'Выберите хотя бы один день',
  'admin.schedule.saveFailed': 'Не удалось сохранить',
  'admin.schedule.timeSubtitle': 'Дни и время начала занятий',
  'admin.schedule.cancel': 'Отмена',
  'admin.schedule.save': 'Сохранить',
  'admin.schedule.title': 'Расписание',
  'admin.schedule.subtitle': 'Кабинеты по строкам, время занятий по столбцам.',
  'admin.schedule.room': 'Кабинет',
  'admin.schedule.emptyTitle': 'Пока нет кабинетов и групп',
  'admin.schedule.emptyHint': 'Создайте кабинет — группы появятся на временной сетке',
  'admin.schedule.searchPlaceholder': 'Группа или ментор',
  'admin.schedule.emptySlots': 'Пустые слоты',
  'admin.schedule.slots': 'Слоты',
  'admin.schedule.confirmDeleteRoom': 'Удалить кабинет «{{name}}»?',
  'admin.schedule.deleteRoomFailed': 'Не удалось удалить кабинет',
  'admin.schedule.createRoomFailed': 'Не удалось создать кабинет',
  'admin.schedule.moveGroupFailed': 'Не удалось перенести группу',
  'admin.schedule.newRoom': 'Новый кабинет',
  'admin.schedule.roomNamePlaceholder': 'Название (например A1)',
  'admin.schedule.capacityPlaceholder': 'Вместимость',
  'admin.schedule.create': 'Создать',

  // admin/Profile.jsx
  'admin.profile.loadErrorPrefix': 'Не удалось загрузить профиль: {{message}}. Показаны данные из сессии.',
  'admin.profile.retry': 'Повторить',
  'admin.profile.emailLabel': 'Email',
  'admin.profile.phoneLabel': 'Телефон',
  'admin.profile.registeredLabel': 'Зарегистрирован',
  'admin.profile.personalData': 'Личные данные',
  'admin.profile.personalDataHint': 'Эти данные видит администратор организации.',
  'admin.profile.firstNameLabel': 'Имя',
  'admin.profile.lastNameLabel': 'Фамилия',
  'admin.profile.emailHint': 'Вы входите в систему с этим email, код восстановления пароля также приходит на этот адрес.',
  'admin.profile.saved': 'Сохранено',
  'admin.profile.dirty': 'Есть несохранённые изменения',
  'admin.profile.cancel': 'Отмена',
  'admin.profile.save': 'Сохранить',
  'admin.profile.security': 'Безопасность',
  'admin.profile.password': 'Пароль',
  'admin.profile.passwordHint': 'В целях безопасности пароль не изменяется здесь — он восстанавливается через код подтверждения, отправляемый на ваш email.',
  'admin.profile.resetPassword': 'Восстановить пароль',
  'admin.profile.endSession': 'Завершить сеанс',
  'admin.profile.sessionHint': 'Вы выйдете из аккаунта на этом устройстве.',
  'admin.profile.logout': 'Выйти',
  'admin.profile.enterName': 'Введите имя',
  'admin.profile.enterLast': 'Введите фамилию',
  'admin.profile.invalidEmail': 'Некорректный email',
  'admin.profile.saveFailed': 'Не удалось сохранить',

  // admin/MentorDetail.jsx
  'admin.mentorDetail.currency': 'сум',
  'admin.mentorDetail.backToMentors': 'К менторам',
  'admin.mentorDetail.gradeTooltip': 'Уровень ментора',
  'admin.mentorDetail.emailLabel': 'Email',
  'admin.mentorDetail.phoneLabel': 'Телефон',
  'admin.mentorDetail.notSpecified': 'Не указан',
  'admin.mentorDetail.skills': 'Навыки',
  'admin.mentorDetail.freeze': 'Заморозить',
  'admin.mentorDetail.unfreeze': 'Разморозить',
  'admin.mentorDetail.edit': 'Изменить',
  'admin.mentorDetail.chat': 'Чат',
  'admin.mentorDetail.archive': 'Архивировать',
  'admin.mentorDetail.groups': 'Группы',
  'admin.mentorDetail.students': 'Ученики',
  'admin.mentorDetail.noGroups': 'Нет групп',
  'admin.mentorDetail.studentsShort': '{{count}} уч.',
  'admin.mentorDetail.editTitle': 'Редактирование ментора',
  'admin.mentorDetail.firstNameLabel': 'Имя',
  'admin.mentorDetail.lastNameLabel': 'Фамилия',
  'admin.mentorDetail.cancel': 'Отмена',
  'admin.mentorDetail.save': 'Сохранить',
  'admin.mentorDetail.freezeTitle': 'Заморозить ментора',
  'admin.mentorDetail.freezeConfirm': 'Вы уверены, что хотите заморозить {{name}}?',
  'admin.mentorDetail.freezeHint': 'Преподаватель не сможет входить в систему, но данные сохранятся. Укажите причину.',
  'admin.mentorDetail.freezeReasonPlaceholder': 'Причина заморозки…',
  'admin.mentorDetail.archiveTitle': 'Архивировать ментора',
  'admin.mentorDetail.archiveConfirm': 'Вы уверены, что хотите архивировать {{name}}?',
  'admin.mentorDetail.archiveHint': 'Ментор будет скрыт из активного списка. Это действие нельзя отменить через интерфейс.',
  'admin.mentorDetail.notFound': 'Ментор не найден',

  // admin/Reports.jsx
  'admin.reports.title': 'Отчёты',
  'admin.reports.loading': 'Загрузка...',
  'admin.reports.loadError': 'Ошибка загрузки: {{message}}',
  'admin.reports.retry': 'Повторить',
  'admin.reports.subtitle': 'Анализ доходов и долгов по группам',
  'admin.reports.export': 'Экспорт',
  'admin.reports.searchPlaceholder': 'Поиск по названию группы...',
  'admin.reports.period': 'Период:',
  'admin.reports.reset': 'Сбросить',
  'admin.reports.totalRevenue': 'Общий доход',
  'admin.reports.totalDebt': 'Общий долг',
  'admin.reports.groupsCount': '{{count}} группа(-ы)',
  'admin.reports.students': 'Ученики',
  'admin.reports.avgRevenue': 'Средний доход',
  'admin.reports.revenueByGroup': 'Доход по группам',
  'admin.reports.revenueShare': 'Доля дохода',
  'admin.reports.noData': 'Данные отсутствуют',
  'admin.reports.revenue': 'Доход',
  'admin.reports.debt': 'Долг',
  'admin.reports.colGroup': 'Группа',
  'admin.reports.colStudents': 'Ученики',
  'admin.reports.colRevenue': 'Доход',
  'admin.reports.colDebt': 'Долг',
  'admin.reports.colRatio': 'Соотношение',
  'admin.reports.nothingFound': 'Ничего не найдено',
  'admin.reports.tryAnotherQuery': 'Попробуйте другой запрос',
  'admin.reports.noReportData': 'Пока нет данных по отчётам',
  'admin.reports.totalRevenueColon': 'Общий доход:',
  'admin.reports.totalDebtColon': 'Общий долг:',

  // admin/Students.jsx
  'admin.students.archiveConfirm': 'Архивировать студента {{name}}?\n\nСтудент будет скрыт из списка, но данные сохранятся.',
  'admin.students.title': 'Студенты',
  'admin.students.subtitle': 'Учёт студентов филиала',
  'admin.students.add': 'Добавить студента',
  'admin.students.searchPlaceholder': 'Поиск по имени, фамилии или телефону…',
  'admin.students.filterAll': 'Все',
  'admin.students.filterDebt': 'Задолжен',
  'admin.students.emptySearchTitle': 'Попробуйте изменить запрос',
  'admin.students.emptyTitle': 'Нет студентов',
  'admin.students.emptyHint': 'Добавьте первого студента',
  'admin.students.addShort': 'Добавить',
  'admin.students.colStudent': 'Студент',
  'admin.students.colPhone': 'Телефон',
  'admin.students.colMentor': 'Ментор',
  'admin.students.colGroup': 'Группа',
  'admin.students.colDirection': 'Направление',
  'admin.students.newTitle': 'Новый студент',
  'admin.students.newSubtitle': 'Заполните данные — логин и пароль сгенерируются автоматически',
  'admin.students.firstNameLabel': 'Имя *',
  'admin.students.lastNameLabel': 'Фамилия *',
  'admin.students.genderLabel': 'Пол',
  'admin.students.male': 'Мужской',
  'admin.students.female': 'Женский',
  'admin.students.birthDateLabel': 'Дата рождения',
  'admin.students.phoneLabel': 'Телефон *',
  'admin.students.phoneOwnerLabel': 'Кому принадлежит',
  'admin.students.phoneOwnerPlaceholder': 'Студенту',
  'admin.students.parentNameLabel': 'Имя родителя *',
  'admin.students.parentPhoneLabel': 'Телефон родителя *',
  'admin.students.parentPhoneOwnerPlaceholder': 'Родителю',
  'admin.students.extraPhoneLabel': 'Доп. телефон',
  'admin.students.groupLabel': 'Группа',
  'admin.students.noGroup': 'Без группы',
  'admin.students.languageLabel': 'Язык обучения',
  'admin.students.langRu': 'Русский',
  'admin.students.sourceLabel': 'Источник',
  'admin.students.sourceReferral': 'По рекомендации',
  'admin.students.sourceWalkIn': 'Пришёл сам',
  'admin.students.schoolLabel': 'Номер школы',
  'admin.students.addressLabel': 'Адрес',
  'admin.students.commentLabel': 'Комментарий для преподавателя',
  'admin.students.hasLaptop': 'Есть ноутбук',
  'admin.students.offerSigned': 'Оферта подписана',
  'admin.students.parentNote': 'Если заполнены имя, фамилия и телефон родителя слева — ему тоже создастся отдельный вход.',
  'admin.students.cancel': 'Отмена',
  'admin.students.create': 'Создать',
  'admin.students.credsTitle': 'Данные для входа',
  'admin.students.credsHint': 'Передайте студенту. Пароль показывается один раз.',
  'admin.students.loginCode': 'Логин-код',
  'admin.students.password': 'Пароль',
  'admin.students.parentLabel': 'Родитель ({{firstName}} {{lastName}})',
  'admin.students.gotIt': 'Понятно',
};

export default ru;
