const ru = {
  // nav
  'nav.dashboard': 'Дашборд',
  'nav.income': 'Доходы',
  'nav.expenses': 'Расходы',
  'nav.salaries': 'Зарплаты',
  'nav.reports': 'Отчёты',
  'nav.report': 'Отчёт',
  'nav.admins': 'Сотрудники',
  'nav.finance': 'Финансы',
  'nav.analytics': 'Аналитика',
  'nav.stats': 'Статистика',
  'nav.tax': 'Налоги',
  'nav.taxNdss': 'НДС 20%',
  'nav.taxSocNalog': 'Соцналог 10%',
  'nav.taxOtzyvnoyNalog': 'Оборотный налог 1.5%',
  'nav.taxTotal': 'Итого налогов',
  'nav.taxOrg': 'Организация',
  'nav.allStudents': 'Все ученики',
  'nav.allGroups': 'Все группы',
  'nav.attendance': 'Посещаемость',
  'nav.more': 'Ещё',
  'nav.discipline': 'Дисциплина',
  'nav.announcements': 'Объявления',
  'nav.reminders': 'Напоминания',
  'nav.audit': 'Аудит',
  'nav.features': 'Фичи',
  'nav.billing': 'Оплата',
  'nav.methodics': 'Методики',
  'nav.shopCatalog': 'Магазин',
  'nav.settings': 'Настройки',
  'nav.students': 'Студенты',
  'nav.groups': 'Группы',
  'nav.mentors': 'Менторы',
  'nav.chat': 'Чат',
  'nav.payments': 'Платежи',
  'nav.branch': 'Филиал',
  'nav.branches': 'Филиалы',
  'nav.allBranches': 'Все филиалы',
  'nav.noBranches': 'Филиалов нет',
  'nav.noGroups': 'Групп нет',
  'nav.methodistTypes': 'Типы обучения',
  'nav.people': 'Люди и клиенты',
  'nav.clientBase': 'База клиентов',
  'nav.myStudents': 'Мои ученики',
  'nav.participantBase': 'База участников',
  'nav.schedule': 'Расписание',
  'nav.main': 'осн',
  'nav.collapse': 'Свернуть',
  'nav.pin': 'Закрепить',
  'nav.collapsePanel': 'Свернуть панель',
  'nav.pinPanel': 'Закрепить панель',

  // common
  'common.total': 'Итого',
  'common.amount': 'Сумма',
  'common.search': 'Поиск...',
  'common.profile': 'Профиль',
  'common.logout': 'Выйти',
  'common.myProfile': 'Мой профиль',
  'common.exit': 'Выйти',
  'common.branch': 'Филиал',
  'common.allBranches': 'Все филиалы',
  'common.status': 'Статус',
  'common.actions': 'Действия',
  'common.date': 'Дата',
  'common.time': 'Время',
  'common.phone': 'Телефон',
  'common.email': 'Email',
  'common.name': 'Название',
  'common.fullName': 'ФИО',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.edit': 'Редактировать',
  'common.add': 'Добавить',
  'common.create': 'Создать',
  'common.details': 'Подробнее',
  'common.view': 'Просмотр',
  'common.back': 'Назад',
  'common.next': 'Далее',
  'common.loading': 'Загрузка...',
  'common.error': 'Произошла ошибка',
  'common.success': 'Успешно',
  'common.filter': 'Фильтр',
  'common.all': 'Все',
  'common.active': 'Активен',
  'common.inactive': 'Неактивен',
  'common.frozen': 'Заморожен',
  'common.archived': 'Архивирован',
  'common.export': 'Экспорт',
  'common.download': 'Скачать',
  'common.upload': 'Загрузить',
  'common.close': 'Закрыть',
  'common.confirm': 'Подтвердить',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.empty': 'Данные не найдены',
  'common.reload': 'Обновить',
  'common.month': 'Месяц',
  'common.period': 'Период',
  'common.notes': 'Примечания',
  'common.description': 'Описание',
  'common.accountMenu': 'Меню аккаунта',
  'common.yesterday': 'Вчера',

  // roles
  'role.seo': 'SEO (Руководитель)',
  'role.admin': 'Администратор',
  'role.branch_manager': 'Управляющий филиалом',
  'role.finance_manager': 'Финансовый менеджер',
  'role.mentor': 'Преподаватель',
  'role.methodist': 'Методист',
  'role.student': 'Ученик',
  'role.parent': 'Родитель',
  'role.employee': 'Сотрудник',

  // notifications
  'notifications.title': 'Уведомления',
  'notifications.empty': 'Нет новых уведомлений',
  'notifications.emptyDesc': 'Непрочитанные сообщения появятся здесь.',
  'notifications.new': 'новых',
  'notifications.allMessages': 'Все сообщения',
  'notifications.newMessage': 'Новое сообщение',
  'notifications.soundOn': 'Звук включён',
  'notifications.soundOff': 'Звук выключен',
  'notifications.muteSound': 'Выключить звук',
  'notifications.unmuteSound': 'Включить звук',

  // kpi & dashboard
  'kpi.income': 'Доход за месяц',
  'kpi.expenses': 'Расход за месяц',
  'kpi.salaries': 'Зарплаты за месяц',
  'kpi.profit': 'Чистая прибыль',
  'kpi.netProfit': 'Чистая прибыль',
  'kpi.orgIncome': 'Доход организации',
  'kpi.orgExpenses': 'Расход организации',
  'kpi.orgProfit': 'Прибыль организации',
  'kpi.students': 'Студенты',
  'kpi.groups': 'Группы',
  'kpi.mentors': 'Менторы',
  'kpi.debt': 'Задолженность',
  'kpi.attendance': 'Посещаемость',

  // dashboard details
  'dash.branchStats': 'Показатели филиала',
  'dash.activeStudents': 'Активные студенты',
  'dash.groups': 'Группы',
  'dash.overdueInvoices': 'Просроченные счета',
  'dash.recentPayments': 'Последние оплаты',
  'dash.noPayments': 'Пока нет оплат',
  'dash.student': 'Студент',
  'dash.reminders': 'Напоминания',
  'dash.overduePaymentsTitle': 'Просроченные платежи',
  'dash.overduePaymentsDesc': 'В данный момент {{count}} счетов просрочены. Контролируйте оплаты.',
  'dash.activeStudentsTitle': 'Активные ученики',
  'dash.activeStudentsDesc': 'В филиале обучается {{count}} активных учеников.',
  'dash.thisMonth': 'За этот месяц',
  'dash.income': 'Доход',
  'dash.expenses': 'Расход',
  'dash.profit': 'Прибыль',
  'dash.loadError': 'Ошибка загрузки',
  'dash.title': 'Панель управления',
  'dash.welcome': 'Добро пожаловать',
  'dash.bmSubtitle': 'общее состояние филиала',
  'dash.incomeThisMonth': 'Доход за этот месяц',
  'dash.expensesThisMonth': 'Расход за этот месяц',
  'dash.debtDesc': 'просроченные платежи',
  'dash.profitFormula': 'доход − расход',
  'dash.vsPrevMonth': 'по сравнению с прошлым месяцем',
  'dash.mainBranch': 'Главный филиал',
  'dash.addressNotSet': 'Адрес не указан',
  'dash.phoneNotSet': 'Телефон не указан',
  'dash.workHoursNotSet': 'Время работы не указано',
  'dash.staff': 'Сотрудники',
  'dash.recentBranchPayments': 'Последние платежи',
  'dash.noPaymentsYet': 'Пока нет платежей',
  'dash.last6Months': 'Последние 6 месяцев: доход vs расход',

  // branch details
  'branch.about': 'О филиале',
  'branch.locationStats': 'расположение и статистика',
  'branch.contacts': 'Контакты',
  'branch.address': 'Адрес',
  'branch.phone': 'Телефон',
  'branch.financeTotal': 'Финансы (итого)',
  'branch.tgCardTitle': 'Группа родителей (Telegram)',
  'branch.tgConnected': 'Группа подключена',
  'branch.tgDisconnect': 'Отключить',
  'branch.tgDesc': 'Сообщения о посещаемости и успеваемости будут автоматически отправляться в эту группу. Сначала добавьте бота в группу, затем получите код для подключения.',
  'branch.tgGetCode': 'Получить код подключения',
  'branch.tgStep1': 'Добавьте бота в группу',
  'branch.tgStep2': 'Отправьте следующую команду в саму группу',
  'branch.tgCodeValid': 'Код действителен {{min}} минут.',
  'branch.notFound': 'Данные филиала не найдены',
  'branch.unlinkConfirm': 'Вы действительно хотите отключить группу?',

  // tax
  'tax.title': 'Налоговый отчёт',
  'tax.subtitle': 'Налоговые начисления по филиалам и организации',
  'tax.export': 'Экспорт CSV',
  'tax.due': 'Итого к уплате',
  'tax.tableTitle': 'Налоги по филиалам',
  'tax.netProfit': 'Чистая прибыль',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Выберите язык',

  // ---------- finance-manager panel (ранее pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Дашборд',
  'finance.nav.income': 'Доходы',
  'finance.nav.expenses': 'Расходы',
  'finance.nav.salaries': 'Зарплаты',
  'finance.nav.reports': 'Отчёты',
  'finance.nav.report': 'Отчёт',
  'finance.nav.admins': 'Сотрудники',
  'finance.nav.finance': 'Финансы',
  'finance.nav.analytics': 'Аналитика',
  'finance.nav.stats': 'Статистика',
  'finance.nav.tax': 'Налоги',
  'finance.nav.taxTitle': 'Налоговый отчёт',
  'finance.nav.taxNdss': 'НДС 20%',
  'finance.nav.taxSocNalog': 'Соцналог 10%',
  'finance.nav.taxOtzyvnoyNalog': 'Оборотный налог 1.5%',
  'finance.nav.taxTotal': 'Итого',
  'finance.nav.taxOrg': 'Организация',
  'finance.nav.allStudents': 'Все ученики',
  'finance.nav.allGroups': 'Все группы',
  'finance.nav.attendance': 'Посещаемость',
  'finance.nav.more': 'Ещё',
  'finance.nav.discipline': 'Дисциплина',
  'finance.nav.announcements': 'Объявления',
  'finance.nav.reminders': 'Напоминания',
  'finance.nav.audit': 'Аудит',
  'finance.nav.settings': 'Настройки',
  'finance.nav.students': 'Студенты',
  'finance.nav.groups': 'Группы',
  'finance.nav.mentors': 'Менторы',
  'finance.nav.chat': 'Чат',
  'finance.nav.payments': 'Платежи',
  'finance.nav.branch': 'Филиал',
  'finance.nav.branches': 'Филиалы',
  'finance.nav.allBranches': 'Все филиалы',
  'finance.nav.noBranches': 'Филиалов нет',
  'finance.nav.noGroups': 'Групп нет',
  'finance.nav.methodistTypes': 'Типы обучения',
  'finance.nav.main': 'осн',
  'finance.nav.collapse': 'Свернуть',
  'finance.nav.pin': 'Закрепить',
  'finance.nav.collapsePanel': 'Свернуть панель',
  'finance.nav.pinPanel': 'Закрепить панель',

  'finance.kpi.income': 'Доход за месяц',
  'finance.kpi.expenses': 'Расход за месяц',
  'finance.kpi.salaries': 'Зарплаты за месяц',
  'finance.kpi.netProfit': 'Чистая прибыль',
  'finance.kpi.orgIncome': 'Доход организации',
  'finance.kpi.orgExpenses': 'Расход организации',
  'finance.kpi.orgProfit': 'Прибыль организации',

  'finance.common.total': 'Итого',
  'finance.common.share': 'Доля',
  'finance.common.amount': 'Сумма',
  'finance.common.date': 'Дата',
  'finance.common.status': 'Статус',
  'finance.common.method': 'Метод',
  'finance.common.note': 'Примечание',
  'finance.common.category': 'Категория',
  'finance.common.employee': 'Сотрудник',
  'finance.common.position': 'Должность',
  'finance.common.branch': 'Филиал',
  'finance.common.allBranches': 'Все филиалы',
  'finance.common.month': 'Месяц',
  'finance.common.period': 'Период',
  'finance.common.vsPrev': 'к прошлому месяцу',
  'finance.common.noData': 'Нет данных',
  'finance.common.students': 'Ученики',
  'finance.common.groups': 'Группы',
  'finance.common.staff': 'Сотрудники',
  'finance.common.loading': 'Загрузка…',
  'finance.common.page': 'Стр.',
  'finance.common.save': 'Сохранить',
  'finance.common.cancel': 'Отмена',
  'finance.common.add': 'Добавить',
  'finance.common.edit': 'Изменить',
  'finance.common.delete': 'Удалить',
  'finance.common.confirmDelete': 'Удалить эту запись?',

  'finance.dash.title': 'Финансовый дашборд',
  'finance.dash.subtitle': 'Вся организация · по филиалам и месяцам',
  'finance.dash.trendChart': 'Доходы и расходы организации',
  'finance.dash.profitLine': 'Прибыль',
  'finance.dash.branchShare': 'Доля филиалов в доходе',
  'finance.dash.monthlyProfit': 'Чистая прибыль за 6 месяцев',
  'finance.dash.viewReports': 'Подробный отчёт',
  'finance.dash.days30Org': 'Последние 30 дней · вся организация',
  'finance.dash.chartSub': 'Фактические поступления за 30 дней',
  'finance.dash.branches': 'Филиалы',

  'finance.income.title': 'Доходы',
  'finance.income.subtitle': 'Поступления по филиалам и месяцам',
  'finance.income.tableTitle': 'Платежи',
  'finance.income.student': 'Ученик',
  'finance.income.group': 'Группа',

  'finance.expenses.title': 'Расходы',
  'finance.expenses.subtitle': 'Расходы по филиалам и категориям',
  'finance.expenses.catBreakdown': 'По категориям',
  'finance.expenses.add': 'Новый расход',
  'finance.expenses.edit': 'Изменить расход',
  'finance.expenses.orgWide': 'На всю организацию',
  'finance.expenses.categoryPlaceholder': 'Например: Аренда',

  'finance.salaries.title': 'Зарплаты',
  'finance.salaries.subtitle': 'Фонд оплаты труда по филиалам',
  'finance.salaries.payroll': 'ФОТ за месяц',
  'finance.salaries.sheetTitle': 'Ведомость',

  'finance.reports.title': 'Отчёты',
  'finance.reports.subtitle': 'Сводка по филиалам за месяц',
  'finance.reports.org': 'Организация',
  'finance.reports.cashFlow': 'Денежный поток',
  'finance.reports.branchTable': 'Филиалы · сводка',
  'finance.reports.branchNet': 'Нетто по филиалам',
  'finance.reports.branchDetail': 'Детализация по филиалам',
  'finance.reports.net': 'Чистая прибыль',
  'finance.reports.opProfit': 'Операционная прибыль',
  'finance.reports.vsPrevMonth': 'к прошлому месяцу',
  'finance.reports.export': 'Экспорт CSV',
  'finance.reports.paymentsThisMonth': 'Платежи · этот месяц',
  'finance.reports.byStatus': 'По статусу оплаты',
  'finance.reports.byMethod': 'По способу оплаты',
  'finance.reports.overdueAmount': 'Просрочено',
  'finance.reports.expensesByCategory': 'Расходы по категориям',
  'finance.reports.subtitleLive': 'Реальные данные backend · последние 30 дней',
  'finance.reports.incomeLabel': 'Поступления за 30 дней',
  'finance.reports.activeStudents': 'Активные ученики',
  'finance.reports.last30days': 'Последние 30 дней',
  'finance.reports.debtLabel': 'Долг',
  'finance.reports.incomeDebtByBranch': 'Поступления и долги по филиалам',
  'finance.reports.methodsSubtitle': 'Завершённые транзакции',
  'finance.reports.noCompletedPayments': 'Нет завершённых платежей',
  'finance.reports.orgRow': 'ОРГАНИЗАЦИЯ',
  'finance.method.cash': 'Наличные',
  'finance.method.card': 'Карта',
  'finance.method.transfer': 'Перевод',
  'finance.method.bankTransfer': 'Банковский перевод',
  'finance.salaryStatus.draft': 'Черновик',
  'finance.salaryStatus.approved': 'Утверждена',
  'finance.salaryStatus.paid': 'Выплачена',

  'finance.settings.title': 'Настройки',
  'finance.settings.subtitle': 'Профиль и предпочтения',
  'finance.settings.personal': 'Личные данные',
  'finance.settings.personalSub': 'Эти данные отображаются в системе и сохраняются в вашем профиле',
  'finance.settings.firstName': 'Имя',
  'finance.settings.lastName': 'Фамилия',
  'finance.settings.phone': 'Телефон',
  'finance.settings.city': 'Город',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Сохранить',
  'finance.settings.saved': 'Настройки сохранены',
  'finance.settings.lang': 'Язык интерфейса',
  'finance.settings.langSub': 'Применяется сразу, на весь интерфейс панели',
  'finance.settings.security': 'Безопасность',
  'finance.settings.securitySub': 'Смена пароля и данные учётной записи управляются через основную учётную запись',
};

export default ru;
