const ru = {
  // nav
  'nav.dashboard': 'Дашборд',
  'nav.income': 'Доходы',
  'nav.expenses': 'Расходы',
  'nav.salaries': 'Зарплаты',
  'nav.reports': 'Отчёты',
  'nav.report': 'Отчёт',
  'nav.admins': 'Сотрудники',
  'nav.finance': 'Финансы',
  'nav.analytics': 'Аналитика',
  'nav.stats': 'Статистика',
  'nav.tax': 'Налоги',
  'nav.taxNdss': 'НДС 20%',
  'nav.taxSocNalog': 'Соцналог 10%',
  'nav.taxOtzyvnoyNalog': 'Оборотный налог 1.5%',
  'nav.taxTotal': 'Итого налогов',
  'nav.taxOrg': 'Организация',
  'nav.allStudents': 'Все ученики',
  'nav.allGroups': 'Все группы',
  'nav.attendance': 'Посещаемость',
  'nav.more': 'Ещё',
  'nav.discipline': 'Дисциплина',
  'nav.announcements': 'Объявления',
  'nav.reminders': 'Напоминания',
  'nav.audit': 'Аудит',
  'nav.features': 'Фичи',
  'nav.billing': 'Оплата',
  'nav.methodics': 'Методики',
  'nav.shopCatalog': 'Магазин',
  'nav.settings': 'Настройки',
  'nav.students': 'Студенты',
  'nav.groups': 'Группы',
  'nav.mentors': 'Менторы',
  'nav.chat': 'Чат',
  'nav.payments': 'Платежи',
  'nav.branch': 'Филиал',
  'nav.branches': 'Филиалы',
  'nav.allBranches': 'Все филиалы',
  'nav.noBranches': 'Филиалов нет',
  'nav.noGroups': 'Групп нет',
  'nav.methodistTypes': 'Типы обучения',
  'nav.main': 'осн',
  'nav.collapse': 'Свернуть',
  'nav.pin': 'Закрепить',
  'nav.collapsePanel': 'Свернуть панель',
  'nav.pinPanel': 'Закрепить панель',

  // common
  'common.total': 'Итого',
  'common.amount': 'Сумма',
  'common.search': 'Поиск...',
  'common.profile': 'Профиль',
  'common.logout': 'Выйти',
  'common.myProfile': 'Мой профиль',
  'common.exit': 'Выйти',
  'common.branch': 'Филиал',
  'common.allBranches': 'Все филиалы',
  'common.status': 'Статус',
  'common.actions': 'Действия',
  'common.date': 'Дата',
  'common.time': 'Время',
  'common.phone': 'Телефон',
  'common.email': 'Email',
  'common.name': 'Название',
  'common.fullName': 'ФИО',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.delete': 'Удалить',
  'common.edit': 'Редактировать',
  'common.add': 'Добавить',
  'common.create': 'Создать',
  'common.details': 'Подробнее',
  'common.view': 'Просмотр',
  'common.back': 'Назад',
  'common.next': 'Далее',
  'common.loading': 'Загрузка...',
  'common.error': 'Произошла ошибка',
  'common.success': 'Успешно',
  'common.filter': 'Фильтр',
  'common.all': 'Все',
  'common.active': 'Активен',
  'common.inactive': 'Неактивен',
  'common.frozen': 'Заморожен',
  'common.archived': 'Архивирован',
  'common.export': 'Экспорт',
  'common.download': 'Скачать',
  'common.upload': 'Загрузить',
  'common.close': 'Закрыть',
  'common.confirm': 'Подтвердить',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.empty': 'Данные не найдены',
  'common.reload': 'Обновить',
  'common.month': 'Месяц',
  'common.period': 'Период',
  'common.notes': 'Примечания',
  'common.description': 'Описание',

  // roles
  'role.seo': 'SEO (Руководитель)',
  'role.admin': 'Администратор',
  'role.branch_manager': 'Управляющий филиалом',
  'role.finance_manager': 'Финансовый менеджер',
  'role.mentor': 'Преподаватель',
  'role.methodist': 'Методист',
  'role.student': 'Ученик',
  'role.parent': 'Родитель',

  // notifications
  'notifications.title': 'Уведомления',
  'notifications.empty': 'Нет новых уведомлений',
  'notifications.emptyDesc': 'Непрочитанные сообщения появятся здесь.',
  'notifications.new': 'новых',
  'notifications.allMessages': 'Все сообщения',
  'notifications.soundOn': 'Звук включён',
  'notifications.soundOff': 'Звук выключен',

  // kpi & dashboard
  'kpi.income': 'Доход за месяц',
  'kpi.expenses': 'Расход за месяц',
  'kpi.salaries': 'Зарплаты за месяц',
  'kpi.profit': 'Чистая прибыль',
  'kpi.netProfit': 'Чистая прибыль',
  'kpi.orgIncome': 'Доход организации',
  'kpi.orgExpenses': 'Расход организации',
  'kpi.orgProfit': 'Прибыль организации',
  'kpi.students': 'Студенты',
  'kpi.groups': 'Группы',
  'kpi.mentors': 'Менторы',
  'kpi.debt': 'Задолженность',
  'kpi.attendance': 'Посещаемость',

  // dashboard details
  'dash.branchStats': 'Показатели филиала',
  'dash.activeStudents': 'Активные студенты',
  'dash.groups': 'Группы',
  'dash.overdueInvoices': 'Просроченные счета',
  'dash.recentPayments': 'Последние оплаты',
  'dash.noPayments': 'Пока нет оплат',
  'dash.student': 'Студент',
  'dash.reminders': 'Напоминания',
  'dash.overduePaymentsTitle': 'Просроченные платежи',
  'dash.overduePaymentsDesc': 'В данный момент {{count}} счетов просрочены. Контролируйте оплаты.',
  'dash.activeStudentsTitle': 'Активные ученики',
  'dash.activeStudentsDesc': 'В филиале обучается {{count}} активных учеников.',
  'dash.thisMonth': 'За этот месяц',
  'dash.income': 'Доход',
  'dash.expenses': 'Расход',
  'dash.profit': 'Прибыль',
  'dash.loadError': 'Ошибка загрузки',
  'dash.title': 'Панель управления',
  'dash.welcome': 'Добро пожаловать',
  'dash.bmSubtitle': 'общее состояние филиала',
  'dash.incomeThisMonth': 'Доход за этот месяц',
  'dash.expensesThisMonth': 'Расход за этот месяц',
  'dash.debtDesc': 'просроченные платежи',
  'dash.profitFormula': 'доход − расход',
  'dash.vsPrevMonth': 'по сравнению с прошлым месяцем',
  'dash.mainBranch': 'Главный филиал',
  'dash.addressNotSet': 'Адрес не указан',
  'dash.phoneNotSet': 'Телефон не указан',
  'dash.workHoursNotSet': 'Время работы не указано',
  'dash.staff': 'Сотрудники',
  'dash.recentBranchPayments': 'Последние платежи',
  'dash.noPaymentsYet': 'Пока нет платежей',
  'dash.last6Months': 'Последние 6 месяцев: доход vs расход',

  // branch details
  'branch.about': 'О филиале',
  'branch.locationStats': 'расположение и статистика',
  'branch.contacts': 'Контакты',
  'branch.address': 'Адрес',
  'branch.phone': 'Телефон',
  'branch.financeTotal': 'Финансы (итого)',
  'branch.tgCardTitle': 'Группа родителей (Telegram)',
  'branch.tgConnected': 'Группа подключена',
  'branch.tgDisconnect': 'Отключить',
  'branch.tgDesc': 'Сообщения о посещаемости и успеваемости будут автоматически отправляться в эту группу. Сначала добавьте бота в группу, затем получите код для подключения.',
  'branch.tgGetCode': 'Получить код подключения',
  'branch.tgStep1': 'Добавьте бота в группу',
  'branch.tgStep2': 'Отправьте следующую команду в саму группу',
  'branch.tgCodeValid': 'Код действителен {{min}} минут.',
  'branch.notFound': 'Данные филиала не найдены',
  'branch.unlinkConfirm': 'Вы действительно хотите отключить группу?',

  // tax
  'tax.title': 'Налоговый отчёт',
  'tax.subtitle': 'Налоговые начисления по филиалам и организации',
  'tax.export': 'Экспорт CSV',
  'tax.due': 'Итого к уплате',
  'tax.tableTitle': 'Налоги по филиалам',
  'tax.netProfit': 'Чистая прибыль',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Выберите язык',
};

export default ru;
