const uz = {
  // nav
  'nav.dashboard': 'Boshqaruv',
  'nav.income': 'Daromad',
  'nav.expenses': 'Xarajatlar',
  'nav.salaries': 'Maoshlar',
  'nav.reports': 'Hisobotlar',
  'nav.report': 'Hisobot',
  'nav.admins': 'Xodimlar',
  'nav.finance': 'Moliya',
  'nav.analytics': 'Analitika',
  'nav.stats': 'Statistika',
  'nav.tax': 'Soliqlar',
  'nav.taxNdss': 'QQS 20%',
  'nav.taxSocNalog': 'Ijtimoiy soliq 10%',
  'nav.taxOtzyvnoyNalog': 'Aylanma soliq 1.5%',
  'nav.taxTotal': 'Jami soliqlar',
  'nav.taxOrg': 'Tashkilot',
  'nav.allStudents': "Barcha o'quvchilar",
  'nav.allGroups': 'Barcha guruhlar',
  'nav.attendance': 'Davomat',
  'nav.more': 'Yana',
  'nav.discipline': 'Intizom',
  'nav.announcements': "E'lonlar",
  'nav.reminders': 'Eslatmalar',
  'nav.audit': 'Audit',
  'nav.features': 'Imkoniyatlar',
  'nav.billing': "To'lovlar",
  'nav.methodics': 'Metodikalar',
  'nav.shopCatalog': "Do'kon katalogi",
  'nav.settings': 'Sozlamalar',
  'nav.students': "O'quvchilar",
  'nav.groups': 'Guruhlar',
  'nav.mentors': 'Mentorlar',
  'nav.chat': 'Chat',
  'nav.payments': "To'lovlar",
  'nav.branch': 'Filial',
  'nav.branches': 'Filiallar',
  'nav.allBranches': 'Barcha filiallar',
  'nav.noBranches': "Filiallar yo'q",
  'nav.noGroups': "Guruhlar yo'q",
  'nav.methodistTypes': "Ta'lim turlari",
  'nav.people': "Odamlar va mijozlar",
  'nav.clientBase': 'Mijozlar bazasi',
  'nav.myStudents': "Mening o'quvchilarim",
  'nav.participantBase': 'Ishtirokchilar bazasi',
  'nav.schedule': 'Jadval',
  'nav.main': 'asosiy',
  'nav.collapse': "Yig'ish",
  'nav.pin': 'Qotirish',
  'nav.collapsePanel': "Panelni yig'ish",
  'nav.pinPanel': 'Panelni qotirish',

  // common
  'common.total': 'Jami',
  'common.amount': 'Summa',
  'common.search': 'Qidiruv...',
  'common.profile': 'Profil',
  'common.logout': 'Chiqish',
  'common.myProfile': 'Mening profilim',
  'common.exit': 'Chiqish',
  'common.branch': 'Filial',
  'common.allBranches': 'Barcha filiallar',
  'common.status': 'Holat',
  'common.actions': 'Amallar',
  'common.date': 'Sana',
  'common.time': 'Vaqt',
  'common.phone': 'Telefon',
  'common.email': 'Email',
  'common.name': 'Nomi',
  'common.fullName': "To'liq ismi",
  'common.save': 'Saqlash',
  'common.cancel': 'Bekor qilish',
  'common.delete': "O'chirish",
  'common.edit': 'Tahrirlash',
  'common.add': "Qo'shish",
  'common.create': 'Yaratish',
  'common.details': 'Batafsil',
  'common.view': "Ko'rish",
  'common.back': 'Orqaga',
  'common.next': 'Keyingisi',
  'common.loading': 'Yuklanmoqda...',
  'common.error': 'Xatolik yuz berdi',
  'common.success': 'Muvaffaqiyatli',
  'common.filter': 'Filtr',
  'common.all': 'Barchasi',
  'common.active': 'Faol',
  'common.inactive': 'Nofaol',
  'common.frozen': 'Muzlatilgan',
  'common.archived': 'Arxivlangan',
  'common.export': 'Eksport',
  'common.download': 'Yuklab olish',
  'common.upload': 'Yuklash',
  'common.close': 'Yopish',
  'common.confirm': 'Tasdiqlash',
  'common.yes': 'Ha',
  'common.no': "Yo'q",
  'common.empty': "Ma'lumot topilmadi",
  'common.reload': 'Qayta yuklash',
  'common.month': 'Oy',
  'common.period': 'Davr',
  'common.notes': 'Izohlar',
  'common.description': 'Tavsif',
  'common.accountMenu': 'Hisob menyusi',
  'common.yesterday': 'Kecha',

  // mentor/*
  'mentor.noGroupsTitle': 'Sizda hali guruhlar yo‘q',
  'mentor.noGroupsHint': 'Guruh biriktirilganda, u chapdagi ro‘yxatda paydo bo‘ladi.',
  'mentor.groupNotFoundTitle': 'Guruh topilmadi',
  'mentor.groupNotFoundHint': 'Ehtimol, u arxivda yoki olib tashlangan.',
  'mentor.toHome': 'Bosh sahifaga',
  'mentor.back': 'Orqaga',
  'mentor.archived': 'Arxivda',
  'mentor.direction': 'Yo‘nalish',
  'mentor.subject': 'Fan',
  'mentor.lessonTime': 'Dars vaqti',
  'mentor.students': 'O‘quvchilar',
  'mentor.totalCoins': 'Jami tangalar',
  'mentor.groupSections': 'Guruh bo‘limlari',
  'mentor.tab.attendance': 'Davomat',
  'mentor.tab.tests': 'Testlar',
  'mentor.tab.stats': 'Statistika',
  'mentor.search': 'Qidirish...',
  'mentor.selectGroup': 'Guruh',
  'mentor.chooseGroup': 'Guruhni tanlang',
  'mentor.close': 'Yopish',
  'mentor.dash.lessonInProgress': '{{group}} — dars ketmoqda',
  'mentor.dash.attendanceNotMarked': 'davomat belgilanmagan',
  'mentor.dash.markAttendance': 'Davomatni belgilash',
  'mentor.dash.groups': 'Guruhlar',
  'mentor.dash.active': 'faol',
  'mentor.dash.students': 'O‘quvchilar',
  'mentor.dash.total': 'jami',
  'mentor.dash.todayLessons': 'Bugungi darslar',
  'mentor.dash.bySchedule': 'jadval bo‘yicha',
  'mentor.dash.todaySchedule': 'Bugungi jadval',
  'mentor.dash.myGroups': 'Mening guruhlarim',
  'mentor.dash.noLessonsTitle': 'Bugun jadvalda dars yo‘q',
  'mentor.dash.noLessonsHint': 'Guruh uchun dars vaqti belgilanmagan bo‘lsa ham, davomatni qo‘lda belgilashingiz mumkin.',
  'mentor.dash.goToAttendance': 'Davomatga o‘tish',
  'mentor.dash.studentsCount': '{{count}} o‘quvchi',
  'mentor.dash.now': 'Ketmoqda',
  'mentor.dash.done': 'Tugadi',
  'mentor.dash.attendance': 'Davomat',
  'mentor.chat.colleagues': 'Hamkasblar',
  'mentor.chat.notFound': 'Topilmadi',
  'mentor.chat.noMentors': "Mentorlar yo'q",
  'mentor.chat.online': 'Online',
  'mentor.chat.offline': 'Offline',
  'mentor.chat.noMessagesTitle': "Xabarlar yo'q",
  'mentor.chat.noMessagesHint': "Birinchi bo'lib xabar yuboring",
  'mentor.chat.placeholder': 'Xabar yozing...',
  'mentor.chat.selectContactTitle': 'Suhbatdoshni tanlang',
  'mentor.chat.selectContactHint': 'Chap paneldan hamkasbni tanlang',
  'mentor.students.statusActive': 'Faol',
  'mentor.students.statusFrozen': 'Muzlatilgan',
  'mentor.students.statusDropped': 'Chetlashtirilgan',
  'mentor.students.msgStudent': "O'quvchiga yozish",
  'mentor.students.msgParent': 'Ota-onaga yozish',
  'mentor.students.noParent': "Ota-ona biriktirilmagan",
  'mentor.students.viewStats': "Statistikani ko'rish",
  'mentor.students.students': "O'quvchilar",
  'mentor.students.groups': 'Guruhlar',
  'mentor.students.totalCoins': 'Jami tangalar',
  'mentor.students.allMyStudents': "Mening barcha o'quvchilarim",
  'mentor.students.allGroups': 'Barcha guruhlar',
  'mentor.students.searchPlaceholder': 'Ism, telefon yoki ID...',
  'mentor.students.noStudentsTitle': "Hozircha o'quvchilar yo'q",
  'mentor.students.nothingFoundTitle': 'Hech narsa topilmadi',
  'mentor.students.noStudentsHint': "O'quvchilar guruhlaringizga qo'shilganda, ular shu yerda paydo bo'ladi.",
  'mentor.students.nothingFoundHint': "Qidiruv yoki guruh filtrini o'zgartiring.",
  'mentor.students.colStudent': "O'quvchi",
  'mentor.students.colGroup': 'Guruh',
  'mentor.students.colPhone': 'Telefon',
  'mentor.students.colStatus': 'Holat',
  'mentor.students.colCoins': 'Tangalar',
  'mentor.students.shownCount': '{{shown}} / {{total}} ta o‘quvchi ko‘rsatilmoqda',
  'mentor.students.viewByGroups': "Guruhlar bo'yicha ko'rish",
  'mentor.profile.gradeNotSet': "Daraja belgilanmagan",
  'mentor.profile.noSkills': "Ko'nikmalar hali qo'shilmagan",
  'mentor.profile.removeSkill': "{{skill}} — o'chirish",
  'mentor.profile.skillPlaceholder': 'Masalan: IELTS, Grammatika...',
  'mentor.profile.add': "Qo'shish",
  'mentor.profile.skillsHint': "{{count}}/{{max}} · Qo'shish uchun Enter yoki vergul bosing",
  'mentor.profile.groupsLabel': 'Guruhlar',
  'mentor.profile.studentsLabel': "O'quvchilar",
  'mentor.profile.email': 'Email',
  'mentor.profile.phone': 'Telefon',
  'mentor.profile.branch': 'Filial',
  'mentor.profile.registered': "Ro'yxatdan o'tgan",
  'mentor.profile.personalData': "Shaxsiy ma'lumotlar",
  'mentor.profile.personalDataHint': "Bu ma'lumotlarni ota-onalar va administrator ko'radi.",
  'mentor.profile.firstName': 'Ism',
  'mentor.profile.lastName': 'Familiya',
  'mentor.profile.emailHint': 'Siz tizimga shu email orqali kirasiz, parolni tiklash kodi ham shu manzilga keladi.',
  'mentor.profile.professionalInfo': "Kasbiy ma'lumot",
  'mentor.profile.professionalHint': 'Bu ma\'lumotlar ota-onalarga siz bilan tanishish uchun ko\'rsatiladi.',
  'mentor.profile.about': "O'zim haqimda",
  'mentor.profile.aboutPlaceholder': "Tajribangiz, o'qitish uslubingiz, yutuqlaringiz...",
  'mentor.profile.skills': "Ko'nikmalar",
  'mentor.profile.grade': 'Daraja',
  'mentor.profile.gradeHint': "Darajani administrator belgilaydi — siz uni o'zingiz o'zgartira olmaysiz.",
  'mentor.profile.saved': 'Saqlandi',
  'mentor.profile.unsavedChanges': "Saqlanmagan o'zgarishlar bor",
  'mentor.profile.cancel': 'Bekor qilish',
  'mentor.profile.save': 'Saqlash',
  'mentor.profile.security': 'Xavfsizlik',
  'mentor.profile.password': 'Parol',
  'mentor.profile.passwordHint': "Xavfsizlik maqsadida parol bu yerda o'zgartirilmaydi — u emailingizga yuboriladigan tasdiqlash kodi orqali tiklanadi.",
  'mentor.profile.resetPassword': 'Parolni tiklash',
  'mentor.profile.endSession': 'Seansni yakunlash',
  'mentor.profile.endSessionHint': 'Siz bu qurilmadagi akkauntdan chiqasiz.',
  'mentor.profile.logout': 'Chiqish',
  'mentor.profile.enterFirstName': 'Ism kiriting',
  'mentor.profile.enterLastName': 'Familiya kiriting',
  'mentor.profile.invalidEmail': "Noto'g'ri email",
  'mentor.profile.saveFailed': "Saqlab bo'lmadi",
  'mentor.sd.months': 'Yan,Fev,Mar,Apr,May,Iyun,Iyul,Avg,Sen,Okt,Noy,Dek',
  'mentor.sd.hw.graded': 'Baholandi',
  'mentor.sd.hw.submitted': 'Topshirildi',
  'mentor.sd.hw.late': 'Kech topshirildi',
  'mentor.sd.hw.missed': 'Topshirilmadi',
  'mentor.sd.hw.pending': 'Muddati kelmagan',
  'mentor.sd.att.present': 'Kelgan',
  'mentor.sd.att.late': 'Kechikkan',
  'mentor.sd.att.absent': 'Kelmagan',
  'mentor.sd.att.excused': 'Sababli',
  'mentor.sd.homeworkKind': 'Uy vazifasi',
  'mentor.sd.testKind': 'Test',
  'mentor.sd.noChange': "o'zgarishsiz",
  'mentor.sd.vsPrevMonth': "o'tgan oyga",
  'mentor.sd.studentNotFoundTitle': "O'quvchi topilmadi",
  'mentor.sd.studentNotFoundHint': 'Ehtimol, u guruhingizdan chetlashtirilgan.',
  'mentor.sd.toStudentsList': "O'quvchilar ro'yxatiga",
  'mentor.sd.allStudents': "Barcha o'quvchilar",
  'mentor.sd.frozen': 'Muzlatilgan',
  'mentor.sd.coins': 'Tangalar',
  'mentor.sd.stats': 'Statistika',
  'mentor.sd.missedTasks': '{{count}} ta topshiriq bajarilmagan',
  'mentor.sd.tabOverall': 'Umumiy',
  'mentor.sd.tabAttendance': 'Davomat',
  'mentor.sd.tabTests': 'Testlar',
  'mentor.sd.tabHomework': 'Uy vazifasi',
  'mentor.sd.attendanceRing': 'Davomat',
  'mentor.sd.lessonsCount': '{{n}} / {{total}} dars',
  'mentor.sd.homeworkRing': 'Uy vazifasi',
  'mentor.sd.submittedCount': '{{n}} / {{total}} topshirilgan',
  'mentor.sd.testsRing': 'Testlar',
  'mentor.sd.takenCount': '{{n}} / {{total}} topshirilgan',
  'mentor.sd.last6Months': "So'nggi 6 oy",
  'mentor.sd.avgGrade': "O'rt. baho",
  'mentor.sd.gapNote': "Chiziqdagi uzilish — bu oyda ma'lumot yo'q (dars yoki topshiriq bo'lmagan).",
  'mentor.sd.wellLearned': "Yaxshi o'zlashtirilgan",
  'mentor.sd.noGradedWorks': "Baholangan ishlar yo'q",
  'mentor.sd.hasDifficulties': 'Qiyinchiliklar bor',
  'mentor.sd.noWeakTopics': "Zaif mavzular yo'q — barcha ishlar 80% dan yuqori",
  'mentor.sd.byMonth': 'Oylar bo‘yicha',
  'mentor.sd.recentLessons': "So'nggi darslar",
  'mentor.sd.attendanceNotMarked': 'Davomat belgilanmagan',
  'mentor.sd.totalLessons': '{{n}} dars',
  'mentor.sd.avgScore': "O'rtacha ball",
  'mentor.sd.allTests': 'Barcha testlar',
  'mentor.sd.noTests': "Testlar yo'q",
  'mentor.sd.notTaken': 'Topshirilmagan',
  'mentor.sd.avgGradeByMonth': "O'rt. baho — oylar bo'yicha",
  'mentor.sd.tasks': 'Topshiriqlar',
  'mentor.sd.notSubmittedCount': 'Topshirilmagan ({{count}})',
  'mentor.sd.submittedCountFilter': 'Topshirilgan ({{count}})',
  'mentor.sd.all': 'Barchasi',
  'mentor.sd.allTasksDone': 'Barcha topshiriqlar bajarilgan',
  'mentor.sd.noTasks': "Topshiriqlar yo'q",
  'mentor.sd.until': 'gacha',
  'mentor.sd.doneCount': '{{n}} / {{total}} topshirilgan',
  'mentor.sd.noDataTooltip': "ma'lumot yo'q",
  'mentor.coins.students': "O'quvchilar",
  'mentor.coins.nobodyFound': 'Hech kim topilmadi',
  'mentor.coins.noStudentsInGroup': "Guruhda o'quvchilar yo'q",
  'mentor.coins.selectStudentTitle': "O'quvchini tanlang",
  'mentor.coins.selectStudentHint': "Tanga berish yoki ayirish uchun chapdagi ro'yxatdan o'quvchini tanlang.",
  'mentor.coins.operation': 'Tanga bilan operatsiya',
  'mentor.coins.balance': 'Balans',
  'mentor.coins.operationType': 'Operatsiya turi',
  'mentor.coins.grant': 'Berish',
  'mentor.coins.deduct': 'Ayirish',
  'mentor.coins.amount': 'Miqdor',
  'mentor.coins.reason': 'Sabab',
  'mentor.coins.reasonPlaceholder': 'Nima uchun?',
  'mentor.coins.genericError': 'Xatolik yuz berdi',
  'mentor.coins.history': 'Operatsiyalar tarixi',
  'mentor.coins.noOperations': "Hozircha operatsiyalar yo'q",
  'mentor.stats.bandWeak': 'Zaif',
  'mentor.stats.bandMid': "O'rtacha",
  'mentor.stats.bandGood': 'Yaxshi',
  'mentor.stats.bandTop': 'Ajoyib',
  'mentor.stats.studentsCount': '{{count}} ta',
  'mentor.stats.bandTitle': '{{band}}: {{count}} o‘quvchi',
  'mentor.stats.overallNote': "Umumiy ball — davomat, uy vazifalari va testlar (o'rtacha). Jami {{total}} o'quvchi.",
  'mentor.stats.overall': 'Umumiy ball',
  'mentor.stats.attendance': 'Davomat',
  'mentor.stats.homework': 'Uy vazifalari',
  'mentor.stats.tests': 'Testlar',
  'mentor.stats.noStudentsInGroup': "Guruhda o'quvchilar yo'q",
  'mentor.stats.distribution': "O'zlashtirish taqsimoti",
  'mentor.stats.topStudents': "O'zlashtirish bo'yicha eng yaxshilar",
  'mentor.stats.needsAttention': "E'tibor talab qiladi",
  'mentor.stats.noRiskStudents': "60% dan past ballli o'quvchilar yo'q",
  'mentor.stats.tasksAttendance': '{{done}}/{{total}} topshiriq · davomat {{rate}}%',
  'mentor.stats.allStudents': "Barcha o'quvchilar",
  'mentor.stats.colStudent': "O'quvchi",
  'mentor.stats.colAttendance': 'Davomat',
  'mentor.stats.colHomework': 'Uy vazifalari',
  'mentor.stats.colTests': 'Testlar',
  'mentor.stats.colOverall': 'Umumiy',
  'mentor.stats.frozen': 'Muzlatilgan',
  'mentor.stats.doneCount': '{{done}}/{{total}} topshirilgan',
  'mentor.stats.takenCount': '{{taken}}/{{total}} topshirilgan',
  'mentor.tests.questionN': 'SAVOL {{n}}',
  'mentor.tests.removeQuestion': "{{n}}-savolni o'chirish",
  'mentor.tests.questionText': 'Savol matni',
  'mentor.tests.markCorrect': "To'g'ri javob sifatida belgilash",
  'mentor.tests.optionCorrect': "{{n}}-variant — to'g'ri",
  'mentor.tests.optionN': '{{n}}-variant',
  'mentor.tests.removeOption': "{{n}}-variantni o'chirish",
  'mentor.tests.addOption': "Variant qo'shish",
  'mentor.tests.results': 'Natijalar',
  'mentor.tests.close': 'Yopish',
  'mentor.tests.nobodyTookTest': 'Hozircha hech kim testni topshirmagan',
  'mentor.tests.passed': 'Topshirdi',
  'mentor.tests.avgScore': "O'rtacha ball",
  'mentor.tests.notPassed': 'Topshirmadi',
  'mentor.tests.enterTitle': 'Test nomini kiriting',
  'mentor.tests.enterDuration': "Davomiylikni kiriting (daqiqa)",
  'mentor.tests.needOneQuestion': 'Kamida bitta savol kerak',
  'mentor.tests.questionEmpty': '{{n}}-savol: matn bo‘sh',
  'mentor.tests.needTwoOptions': '{{n}}-savol: kamida 2 variant kerak',
  'mentor.tests.emptyOption': '{{n}}-savol: bo‘sh variant bor',
  'mentor.tests.correctNotChosen': "{{n}}-savol: to'g'ri javob tanlanmagan",
  'mentor.tests.saveFailed': "Testni saqlab bo'lmadi",
  'mentor.tests.tests': 'Testlar',
  'mentor.tests.newTest': 'Yangi test',
  'mentor.tests.noTestsInGroup': "Bu guruhda hali testlar yo'q",
  'mentor.tests.noTestsHint': '«Yangi test» tugmasini bosib, birinchisini yarating.',
  'mentor.tests.questionsCount': '{{count}} ta savol',
  'mentor.tests.minutes': '{{n}} daq',
  'mentor.tests.testTitle': 'Test nomi',
  'mentor.tests.titlePlaceholder': 'Masalan: Present Simple',
  'mentor.tests.duration': 'Davomiylik (daq)',
  'mentor.tests.coinReward': 'Tanga mukofoti',
  'mentor.tests.addQuestion': "Savol qo'shish",
  'mentor.tests.cancel': 'Bekor qilish',
  'mentor.tests.save': 'Saqlash',

  // mentor/group/AttendanceTab.jsx
  'mentor.att.notSaved': "Saqlanmadi — qayta urinib ko'ring",
  'mentor.att.saving': 'Saqlanmoqda...',
  'mentor.att.saved': 'Saqlandi',
  'mentor.att.saveFailed': 'Saqlanmadi — ulanishni tekshiring',
  'mentor.att.lessonReason': 'Dars',
  'mentor.att.present': 'Keldi',
  'mentor.att.absent': 'Kelmadi',
  'mentor.att.unmarked': 'Belgilanmagan',
  'mentor.att.correctedByAdmin': 'Administrator tomonidan tuzatilgan',
  'mentor.att.markAllPresentToday': 'Bugun hammasi keldi',
  'mentor.att.emptyStudentsTitle': "Bu guruhda o'quvchilar yo'q",
  'mentor.att.studentCol': "O'quvchi",
  'mentor.att.todayCol': 'Bugun',
  'mentor.att.totalCol': 'Jami',
  'mentor.att.budgetTooltip': "Oyiga: {{allocated}} coin ({{students}} o'quvchi × {{perStudent}}). Sarflandi: {{spent}}",
  'mentor.att.dayNumber': '{{day}}-sana',
  'mentor.att.cannotEditSuffix': "(o'zgartirib bo'lmaydi)",
  'mentor.att.editOnlyToday': 'Faqat bugungi kunni belgilash mumkin',
  'mentor.att.creditedToday': 'Bugun berildi',
  'mentor.att.totalBalance': 'Umumiy balans',
  'mentor.att.coinAmountFor': '{{name}} uchun coin miqdori',
  'mentor.att.grantCoinsAria': 'Coin berish: {{name}}',
  'mentor.att.grantCoinsTitle': 'Coin berish',

  // people/Directory.jsx
  'people.title': 'Odamlar va mijozlar',
  'people.subtitle': "Rolingizga qarab kirish huquqi bilan xodimlar, ota-onalar va o'quvchilarning yagona bazasi",
  'people.searchPlaceholder': 'Ism, telefon yoki email',
  'people.allRoles': 'Barcha rollar',
  'people.loading': 'Baza yuklanmoqda…',
  'people.loadError': "Bazani yuklab bo'lmadi",
  'people.emptyFilter': "Filtringiz bo'yicha hech kim topilmadi",
  'people.inSelection': 'Tanlovdagi odamlar',
  'people.students': "O'quvchilar",
  'people.debt': 'Hisob bo‘yicha qarz',
  'people.overdue': "Muddati o'tgan",
  'people.person': 'Inson',
  'people.role': 'Rol',
  'people.branch': 'Filial',
  'people.status': 'Holat',
  'people.paid': "To'langan",
  'people.noContact': "Kontakt ko'rsatilmagan",
  'people.platform': 'Platforma',
  'people.childrenCount': 'Farzandlar: {{count}}',

  // status (format.js: ORG_STATUS/USER_STATUS/ADMIN_STATUS/LEAD_STATUS)
  'status.active': 'Faol',
  'status.trial': 'Sinov',
  'status.frozen': 'Muzlatilgan',
  'status.dropped': "O'chirilgan",
  'status.new': 'Yangi',
  'status.contacted': "Bog'lanildi",
  'status.onboarded': 'Onboarding',
  'status.rejected': 'Rad etilgan',

  // roles
  'role.seo': 'SEO (Rahbar)',
  'role.admin': 'Administrator',
  'role.branch_manager': 'Filial Boshqaruvchisi',
  'role.finance_manager': 'Moliya Menejeri',
  'role.mentor': 'Mentor',
  'role.methodist': 'Metodist',
  'role.student': "O'quvchi",
  'role.parent': 'Ota-ona',
  'role.employee': 'Xodim',

  // notifications
  'notifications.title': 'Bildirishnomalar',
  'notifications.empty': "Yangi bildirishnomalar yo'q",
  'notifications.emptyDesc': "O'qilmagan xabarlar shu yerda paydo bo'ladi.",
  'notifications.new': 'yangi',
  'notifications.allMessages': 'Barcha xabarlar',
  'notifications.newMessage': 'Yangi xabar',
  'notifications.soundOn': 'Ovoz yoqilgan',
  'notifications.soundOff': "Ovoz o'chirilgan",
  'notifications.muteSound': "Ovozni o'chirish",
  'notifications.unmuteSound': 'Ovozni yoqish',

  // kpi & dashboard
  'kpi.income': 'Oylik daromad',
  'kpi.expenses': 'Oylik xarajat',
  'kpi.salaries': 'Oylik maoshlar',
  'kpi.profit': 'Sof foyda',
  'kpi.netProfit': 'Sof foyda',
  'kpi.orgIncome': 'Tashkilot daromadi',
  'kpi.orgExpenses': 'Tashkilot xarajati',
  'kpi.orgProfit': 'Tashkilot foydasi',
  'kpi.students': "O'quvchilar soni",
  'kpi.groups': 'Guruhlar soni',
  'kpi.mentors': 'Mentorlar soni',
  'kpi.debt': 'Qarzdorlik',
  'kpi.attendance': "O'rtacha davomat",

  // dashboard details
  'dash.branchStats': 'Filial ko‘rsatkichlari',
  'dash.activeStudents': 'Faol o‘quvchilar',
  'dash.groups': 'Guruhlar',
  'dash.overdueInvoices': 'Muddati o‘tgan hisoblar',
  'dash.recentPayments': 'So‘nggi to‘lovlar',
  'dash.noPayments': 'Hozircha to‘lovlar yo‘q',
  'dash.student': 'O‘quvchi',
  'dash.reminders': 'Eslatmalar',
  'dash.overduePaymentsTitle': 'Muddati o‘tgan to‘lovlar',
  'dash.overduePaymentsDesc': 'Ayni paytda {{count}} ta hisob muddati o‘tgan. To‘lovlarni nazorat qiling.',
  'dash.activeStudentsTitle': 'Faol o‘quvchilar',
  'dash.activeStudentsDesc': 'Filialda {{count}} ta faol o‘quvchi ta’lim olmoqda.',
  'dash.thisMonth': 'Shu oy uchun',
  'dash.income': 'Daromad',
  'dash.expenses': 'Xarajat',
  'dash.profit': 'Foyda',
  'dash.loadError': 'Yuklashda xatolik',
  'dash.title': 'Boshqaruv paneli',
  'dash.welcome': 'Xush kelibsiz',
  'dash.bmSubtitle': 'filialning umumiy holati',
  'dash.incomeThisMonth': 'Shu oy daromadi',
  'dash.expensesThisMonth': 'Shu oy xarajati',
  'dash.debtDesc': 'muddati o‘tgan to‘lovlar',
  'dash.profitFormula': 'daromad − xarajat',
  'dash.vsPrevMonth': 'o‘tgan oyga nisbatan',
  'dash.mainBranch': 'Asosiy filial',
  'dash.addressNotSet': 'Manzil ko‘rsatilmagan',
  'dash.phoneNotSet': 'Telefon ko‘rsatilmagan',
  'dash.workHoursNotSet': 'Ish vaqti ko‘rsatilmagan',
  'dash.staff': 'Xodimlar',
  'dash.recentBranchPayments': 'So‘nggi to‘lovlar',
  'dash.noPaymentsYet': 'Hozircha to‘lovlar yo‘q',
  'dash.last6Months': 'So‘nggi 6 oy: daromad vs xarajat',

  // branch details
  'branch.about': 'Filial haqida',
  'branch.locationStats': 'joylashuv va statistika',
  'branch.contacts': 'Kontaktlar',
  'branch.address': 'Manzil',
  'branch.phone': 'Telefon',
  'branch.financeTotal': 'Moliya (jami)',
  'branch.tgCardTitle': 'Ota-onalar guruhi (Telegram)',
  'branch.tgConnected': 'Guruh ulangan',
  'branch.tgDisconnect': 'O‘chirish',
  'branch.tgDesc': 'Davomat va o‘zlashtirish haqidagi xabarlar avtomatik ushbu guruhga yuboriladi. Avval botni guruhga qo‘shing, so‘ng ulash kodini oling.',
  'branch.tgGetCode': 'Ulash kodini olish',
  'branch.tgStep1': 'Botni guruhga qo‘shing',
  'branch.tgStep2': 'Quyidagi buyruqni guruhga yuboring',
  'branch.tgCodeValid': 'Kod {{min}} daqiqa davomida amal qiladi.',
  'branch.notFound': 'Filial ma’lumotlari topilmadi',
  'branch.unlinkConfirm': 'Haqiqatan ham guruhni uzmoqchimisiz?',

  // tax
  'tax.title': 'Soliq hisoboti',
  'tax.subtitle': 'Filiallar va tashkilot bo‘yicha soliq hisoblari',
  'tax.export': 'CSV eksport',
  'tax.due': 'Jami to‘lanishi kerak',
  'tax.tableTitle': 'Filiallar bo‘yicha soliqlar',
  'tax.netProfit': 'Sof foyda',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Tilni tanlang',

  // ---------- finance-manager panel (avval pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Boshqaruv',
  'finance.nav.income': 'Daromad',
  'finance.nav.expenses': 'Xarajatlar',
  'finance.nav.salaries': 'Maoshlar',
  'finance.nav.reports': 'Hisobotlar',
  'finance.nav.report': 'Hisobot',
  'finance.nav.admins': 'Xodimlar',
  'finance.nav.finance': 'Moliya',
  'finance.nav.analytics': 'Analitika',
  'finance.nav.stats': 'Statistika',
  'finance.nav.allStudents': "Barcha o'quvchilar",
  'finance.nav.allGroups': 'Barcha guruhlar',
  'finance.nav.attendance': 'Davomat',
  'finance.nav.more': 'Yana',
  'finance.nav.discipline': 'Intizom',
  'finance.nav.announcements': "E'lonlar",
  'finance.nav.reminders': 'Eslatmalar',
  'finance.nav.audit': 'Audit',
  'finance.nav.settings': 'Sozlamalar',
  'finance.nav.students': "O'quvchilar",
  'finance.nav.groups': 'Guruhlar',
  'finance.nav.mentors': 'Mentorlar',
  'finance.nav.chat': 'Chat',
  'finance.nav.payments': "To'lovlar",
  'finance.nav.branch': 'Filial',
  'finance.nav.branches': 'Filiallar',
  'finance.nav.allBranches': 'Barcha filiallar',
  'finance.nav.noBranches': "Filiallar yo'q",
  'finance.nav.noGroups': "Guruhlar yo'q",
  'finance.nav.methodistTypes': "Ta'lim turlari",
  'finance.nav.main': 'asosiy',
  'finance.nav.collapse': "Yig'ish",
  'finance.nav.pin': 'Qotirish',
  'finance.nav.collapsePanel': "Panelni yig'ish",
  'finance.nav.pinPanel': 'Panelni qotirish',

  'finance.kpi.income': 'Oy daromadi',
  'finance.kpi.expenses': 'Oy xarajati',
  'finance.kpi.salaries': 'Oy maoshi',
  'finance.kpi.netProfit': 'Sof foyda',
  'finance.kpi.orgIncome': 'Tashkilot daromadi',
  'finance.kpi.orgExpenses': 'Tashkilot xarajati',
  'finance.kpi.orgProfit': 'Tashkilot foydasi',

  'finance.common.total': 'Jami',
  'finance.common.share': 'Ulush',
  'finance.common.amount': 'Summa',
  'finance.common.date': 'Sana',
  'finance.common.status': 'Holat',
  'finance.common.method': 'Usul',
  'finance.common.note': 'Izoh',
  'finance.common.category': 'Kategoriya',
  'finance.common.employee': 'Xodim',
  'finance.common.position': 'Lavozim',
  'finance.common.branch': 'Filial',
  'finance.common.allBranches': 'Barcha filiallar',
  'finance.common.month': 'Oy',
  'finance.common.period': 'Davr',
  'finance.common.vsPrev': "o'tgan oyga nisbatan",
  'finance.common.noData': "Ma'lumot yo'q",
  'finance.common.students': "O'quvchilar",
  'finance.common.groups': 'Guruhlar',
  'finance.common.staff': 'Xodimlar',
  'finance.common.loading': 'Yuklanmoqda…',
  'finance.common.page': 'Bet',
  'finance.common.save': 'Saqlash',
  'finance.common.cancel': 'Bekor qilish',
  'finance.common.add': "Qo'shish",
  'finance.common.edit': "O'zgartirish",
  'finance.common.delete': "O'chirish",
  'finance.common.confirmDelete': "Bu yozuvni o'chirasizmi?",

  'finance.dash.title': 'Moliyaviy boshqaruv',
  'finance.dash.subtitle': 'Butun tashkilot · filiallar va oylar bo‘yicha',
  'finance.dash.trendChart': 'Tashkilot daromadi va xarajati',
  'finance.dash.profitLine': 'Foyda',
  'finance.dash.branchShare': 'Filiallarning daromaddagi ulushi',
  'finance.dash.monthlyProfit': '6 oylik sof foyda',
  'finance.dash.viewReports': 'Batafsil hisobot',
  'finance.dash.days30Org': "So'nggi 30 kun · butun tashkilot",
  'finance.dash.chartSub': '30 kunlik haqiqiy tushum',
  'finance.dash.branches': 'Filiallar',

  'finance.income.title': 'Daromad',
  'finance.income.subtitle': 'Filiallar va oylar bo‘yicha tushumlar',
  'finance.income.tableTitle': "To'lovlar",
  'finance.income.student': "O'quvchi",
  'finance.income.group': 'Guruh',

  'finance.expenses.title': 'Xarajatlar',
  'finance.expenses.subtitle': "Filiallar va kategoriyalar bo'yicha xarajatlar",
  'finance.expenses.catBreakdown': 'Kategoriyalar bo‘yicha',
  'finance.expenses.add': 'Yangi xarajat',
  'finance.expenses.edit': "Xarajatni o'zgartirish",
  'finance.expenses.orgWide': 'Butun tashkilot uchun',
  'finance.expenses.categoryPlaceholder': 'Masalan: Ijara',

  'finance.salaries.title': 'Maoshlar',
  'finance.salaries.subtitle': "Filiallar bo'yicha ish haqi fondi",
  'finance.salaries.payroll': 'Oy uchun IHF',
  'finance.salaries.sheetTitle': 'Vedomost',

  'finance.reports.title': 'Hisobotlar',
  'finance.reports.subtitle': 'Bir oylik filiallar bo‘yicha xulosa',
  'finance.reports.org': 'Tashkilot',
  'finance.reports.cashFlow': 'Pul oqimi',
  'finance.reports.branchTable': 'Filiallar · xulosa',
  'finance.reports.branchNet': 'Filiallar bo‘yicha sof',
  'finance.reports.branchDetail': 'Filiallar bo‘yicha tafsilot',
  'finance.reports.net': 'Sof foyda',
  'finance.reports.opProfit': 'Operatsion foyda',
  'finance.reports.vsPrevMonth': "o'tgan oyga nisbatan",
  'finance.reports.export': 'CSV eksport',
  'finance.reports.paymentsThisMonth': "To'lovlar · shu oy",
  'finance.reports.byStatus': "To'lov holati bo'yicha",
  'finance.reports.byMethod': "To'lov usuli bo'yicha",
  'finance.reports.overdueAmount': "Muddati o'tgan",
  'finance.reports.expensesByCategory': "Xarajatlar toifalar bo'yicha",
  'finance.reports.subtitleLive': "Haqiqiy backend ma'lumotlari · so'nggi 30 kun",
  'finance.reports.incomeLabel': "30 kunlik tushum",
  'finance.reports.activeStudents': "Faol o'quvchilar",
  'finance.reports.last30days': "So'nggi 30 kun",
  'finance.reports.debtLabel': 'Qarz',
  'finance.reports.incomeDebtByBranch': 'Filiallar bo‘yicha tushum va qarzlar',
  'finance.reports.methodsSubtitle': 'Yakunlangan tranzaksiyalar',
  'finance.reports.noCompletedPayments': "Yakunlangan to'lovlar yo'q",
  'finance.reports.orgRow': 'TASHKILOT',
  'finance.method.cash': 'Naqd',
  'finance.method.card': 'Karta',
  'finance.method.transfer': "O'tkazma",
  'finance.method.bankTransfer': 'Bank o‘tkazmasi',
  'finance.salaryStatus.draft': 'Qoralama',
  'finance.salaryStatus.approved': 'Tasdiqlangan',
  'finance.salaryStatus.paid': "To'langan",

  'finance.settings.title': 'Sozlamalar',
  'finance.settings.subtitle': 'Profil va afzalliklar',
  'finance.settings.personal': "Shaxsiy ma'lumotlar",
  'finance.settings.personalSub': "Bu ma'lumotlar tizimda ko'rinadi va profilingizga saqlanadi",
  'finance.settings.firstName': 'Ism',
  'finance.settings.lastName': 'Familiya',
  'finance.settings.phone': 'Telefon',
  'finance.settings.city': 'Shahar',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Saqlash',
  'finance.settings.saved': 'Sozlamalar saqlandi',
  'finance.settings.lang': 'Interfeys tili',
  'finance.settings.langSub': 'Darhol qo‘llaniladi, butun panel uchun',
  'finance.settings.security': 'Xavfsizlik',
  'finance.settings.securitySub': "Parolni o'zgartirish va hisob ma'lumotlari asosiy hisob orqali boshqariladi",
  'methodist.app.name': "Kontent-studiya",
  'methodist.common.loading_error': "Yuklashda xatolik",
  'methodist.common.loading_failed': "Ma'lumotlarni yuklab bo'lmadi",
  'methodist.common.retry': "Qayta urinish",
  'methodist.common.no_data': "Ma'lumot yo'q",
  'methodist.common.all': "Barchasi",
  'methodist.common.back': "Orqaga",
  'methodist.common.save': "Saqlash",
  'methodist.common.cancel': "Bekor qilish",
  'methodist.common.delete': "O'chirish",
  'methodist.common.edit': "Tahrirlash",
  'methodist.common.add': "Qo'shish",
  'methodist.common.create': "Yaratish",
  'methodist.common.close': "Yopish",
  'methodist.common.copy': "Nusxalash",
  'methodist.common.tests_count': "{{count}} ta test",
  'methodist.common.attempts_count': "{{count}} ta urinish",
  'methodist.kpi.types': "O'quv turlari",
  'methodist.kpi.topics': "Jami mavzular",
  'methodist.kpi.tests': "Testlar",
  'methodist.kpi.hw': "Uy vazifalari",
  'methodist.dashboard.subtitle': "O'quv materiallarini yarating va boshqaring",
  'methodist.dashboard.topics_count': "{{count}} ta mavzu",
  'methodist.dashboard.avg_score': "Testlar bo'yicha o'rtacha ball",
  'methodist.dashboard.great': "A'lo",
  'methodist.dashboard.good': "Yaxshi",
  'methodist.dashboard.need_work': "Ishlash kerak",
  'methodist.dashboard.types_section': "O'quv turlari",
  'methodist.dashboard.all_types': "Barcha turlar",
  'methodist.dashboard.no_types': "O'quv turlari yo'q",
  'methodist.dashboard.no_types_hint': "Boshlash uchun birinchi turni yarating",
  'methodist.dashboard.create_type': "Tur yaratish",
  'methodist.analytics.title': "O'zlashtirish tahlili",
  'methodist.analytics.subtitle': "Fanlar va testlar bo'yicha qiyinchilik statistikasi",
  'methodist.analytics.donut_aria': "Umumiy o'rtacha ball {{num}}%",
  'methodist.analytics.total_tests': "Jami testlar",
  'methodist.analytics.total_attempts': "Jami urinishlar",
  'methodist.analytics.overall_avg': "Umumiy o'rtacha",
  'methodist.analytics.performance': "O'zlashtirish",
  'methodist.analytics.score_good': "Yaxshi",
  'methodist.analytics.score_avg': "O'rtacha",
  'methodist.analytics.score_hard': "Qiyin",
  'methodist.analytics.subject_difficulty': "Fanlar qiyinligi",
  'methodist.analytics.by_avg_score': "O'rtacha ball bo'yicha",
  'methodist.analytics.low_tests': "Past natijali testlar",
  'methodist.analytics.top5': "Qiyinlik bo'yicha top-5",
  'methodist.analytics.all_tests': "Barcha testlar",
  'methodist.analytics.full_table': "Natijalarning to'liq jadvali",
  'methodist.analytics.col_title': "Nomi",
  'methodist.analytics.col_group': "Guruh",
  'methodist.analytics.col_branch': "Filial",
  'methodist.analytics.col_attempts': "Urinishlar",
  'methodist.analytics.col_avg': "O'rtacha ball",
  'methodist.analytics.general_subject': "Umumiy",
  'methodist.types.title': "O'quv turlari",
  'methodist.types.subtitle': "Yo'nalishlar: Backend, Frontend, Python va boshqalar",
  'methodist.types.add': "Tur qo'shish",
  'methodist.types.no_types': "O'quv turlari yo'q",
  'methodist.types.no_types_hint': "Kontent bilan to'ldirishni boshlash uchun birinchi turni yarating",
  'methodist.types.create_first': "Birinchi turni yaratish",
  'methodist.types.topics_count': "{{count}} ta mavzu",
  'methodist.types.description_short': "tavsif",
  'methodist.types.archive_tooltip': "Arxivlash",
  'methodist.types.open_topics': "Mavzularni ochish",
  'methodist.types.archive_confirm': "Turni arxivlash?",
  'methodist.types.archive_hidden': "«{{name}}» yashiriladi",
  'methodist.types.archive': "Arxivlash",
  'methodist.types.new_title': "Yangi o'quv turi",
  'methodist.types.new_hint': "Yo'nalish yarating",
  'methodist.types.name_label': "Nomi *",
  'methodist.types.name_placeholder': "Masalan: Backend",
  'methodist.types.name_required': "Nomi kiritilishi shart",
  'methodist.types.description_label': "Tavsif",
  'methodist.types.description_placeholder': "Yo'nalish haqida qisqacha...",
  'methodist.types.icon_label': "Belgi (emoji)",
  'methodist.types.ai_review_label': "Aqlli tahlil (AI)",
  'methodist.types.ai_review_hint': "AI ushbu kurs bo'yicha o'quvchilarning amaliy topshiriqlar kodini tahlil qiladi. Faqat amaliyot haqiqiy o'qiladigan kod bo'lgan joyda yoqing (HTML/CSS/JS), fayllar ko'p bo'lgan kurslar uchun emas.",
  'methodist.topics.breadcrumb_types': "O'quv turlari",
  'methodist.topics.breadcrumb_topics': "Mavzular",
  'methodist.topics.title': "Mavzular",
  'methodist.topics.subtitle': "Yo'nalish ichidagi darslar va testlar",
  'methodist.topics.add': "Mavzu qo'shish",
  'methodist.topics.create': "Mavzu yaratish",
  'methodist.topics.no_topics': "Mavzular yo'q",
  'methodist.topics.no_topics_hint': "Bu yo'nalishda birinchi mavzuni yarating",
  'methodist.topics.lessons_count': "{{count}} ta dars",
  'methodist.topics.description_short': "tavsif",
  'methodist.topics.edit_tooltip': "Tahrirlash",
  'methodist.topics.delete_tooltip': "O'chirish",
  'methodist.topics.archive_tooltip': "Arxivlash",
  'methodist.topics.lessons_and_tests': "Darslar va testlar",
  'methodist.topics.archive_confirm': "Mavzuni arxivlash?",
  'methodist.topics.archive_hidden': "«{{name}}» yashiriladi",
  'methodist.topics.archive': "Arxivlash",
  'methodist.topics.new_title': "Yangi mavzu",
  'methodist.topics.new_hint': "Yo'nalishga mavzu qo'shing",
  'methodist.topics.name_label': "Nomi *",
  'methodist.topics.name_placeholder': "Masalan: React Hooks",
  'methodist.topics.name_required': "Nomi kiritilishi shart",
  'methodist.topics.description_label': "Tavsif",
  'methodist.topics.description_placeholder': "Bu mavzu nima haqida...",
  'methodist.topics.description': "Tavsif",
  'methodist.topics.video_label': "Mavzu videosi",
  'methodist.topics.video_mode_url': "Havola",
  'methodist.topics.video_mode_file': "Fayl",
  'methodist.topics.video_url_placeholder': "YouTube havolasi",
  'methodist.topics.video_upload_hint': "yoki videoni shu yerga tashlang",
  'methodist.topics.video_no_file': "Video yuklanmagan",
  'methodist.topics.video_remove': "Videoni o'chirish",
  'methodist.topics.coin_reward_label': "Video ko'rish uchun tanga",
  'methodist.topics.coin_reward_hint': "Video oxirigacha ko'rilganda talabaga bir marta to'liq beriladi",
  'methodist.topics.video_after_create_hint': "Fayl yuklash mavzu yaratilgandan keyin ochiladi — avval saqlang",
  'methodist.lessons.breadcrumb_types': "Turlar",
  'methodist.lessons.breadcrumb_topics': "Mavzular",
  'methodist.lessons.breadcrumb_lessons': "Darslar",
  'methodist.lessons.title': "Darslar",
  'methodist.lessons.subtitle': "Mavzu ichidagi testlar va amaliy topshiriqlar",
  'methodist.lessons.create': "Dars yaratish",
  'methodist.lessons.badge_test': "Test",
  'methodist.lessons.badge_practical': "Amaliyot",
  'methodist.lessons.no_lessons': "Darslar yo'q",
  'methodist.lessons.no_lessons_hint': "Birinchi test yoki amaliy topshiriq yarating",
  'methodist.lessons.questions_count': "{{count}} ta savol",
  'methodist.lessons.requirements_count': "{{count}} ta talab",
  'methodist.lessons.copy_tooltip': "Darsni nusxalash",
  'methodist.lessons.archive_tooltip': "Arxivlash",
  'methodist.lessons.edit_tooltip': "Tahrirlash",
  'methodist.lessons.archive_confirm': "Darsni arxivlash?",
  'methodist.lessons.archive': "Arxivlash",
  'methodist.lessons.new_title': "Yangi dars",
  'methodist.lessons.new_hint': "Test yoki amaliy topshiriq yarating",
  'methodist.lessons.field_title': "Nomi *",
  'methodist.lessons.title_placeholder': "Masalan: HTML teglar",
  'methodist.lessons.title_required': "Nomi kiritilishi shart",
  'methodist.lessons.lesson_type_label': "Dars turi",
  'methodist.lessons.type_test': "Test (A/B/C/D)",
  'methodist.lessons.type_practical': "Amaliy topshiriq",
  'methodist.lessons.desc_label': "Topshiriq tavsifi",
  'methodist.lessons.desc_placeholder': "Talaba uchun topshiriqni tavsiflang...",
  'methodist.lessons.instruction_label': "Yo'riqnoma / Tushuntirish",
  'methodist.lessons.instruction_placeholder': "Mavzuning qisqacha tushuntirishi...",
  'methodist.lessons.coin_label': "Mukofot (koinlar)",
  'methodist.lessons.create_and_edit': "Yaratish va tahrirlash",
  'methodist.editor.title': "Dars muharriri",
  'methodist.editor.subtitle': "Test yoki amaliy topshiriq",
  'methodist.editor.settings_tooltip': "Dars parametrlari",
  'methodist.editor.test_count': "Test · {{count}} ta savol",
  'methodist.editor.type_practical': "Amaliy topshiriq",
  'methodist.editor.requirements_title': "Majburiy talablar",
  'methodist.editor.requirements_hint': "Talaba vazifada nimani bajarishi kerak",
  'methodist.editor.requirement_text': "Talab / shart *",
  'methodist.editor.requirement_points': "Ball",
  'methodist.editor.add_requirement': "Talab qo'shish",
  'methodist.editor.save_requirements': "Talablarni saqlash",
  'methodist.editor.requirements_total': "Jami {{points}} ball",
  'methodist.editor.no_requirements': "Talablar hozircha yo'q. Birinchisini qo'shing.",
  'methodist.editor.video_label': "Video material:",
  'methodist.editor.task_desc': "Topshiriq tavsifi",
  'methodist.editor.attachment_label': "Topshiriqqa biriktirilgan fayl:",
  'methodist.editor.no_file': "Fayl biriktirilmagan",
  'methodist.editor.upload_drop_hint': "yoki faylni shu yerga tashlang",
  'methodist.editor.instruction': "Yo'riqnoma / Tushuntirish",
  'methodist.editor.edit_question': "Savolni tahrirlash",
  'methodist.editor.add_question': "Savol qo'shish",
  'methodist.editor.question_type': "Savol turi",
  'methodist.editor.question_text': "Savol matni *",
  'methodist.editor.question_placeholder': "Sarlavha uchun qaysi teg ishlatiladi?",
  'methodist.editor.option_label': "Variant {{letter}}",
  'methodist.editor.correct_answer': "To'g'ri javob *",
  'methodist.editor.batch_title': "Tez yaratish",
  'methodist.editor.empty_questions': "ta bo'sh savol",
  'methodist.editor.questions': "Savollar",
  'methodist.editor.no_questions': "Savollar yo'q. Yuqorida birinchi savolni qo'shing.",
  'methodist.editor.delete_confirm': "Savolni o'chirish?",
  'methodist.editor.settings_title': "Dars parametrlari",
  'methodist.editor.settings_name': "Nomi *",
  'methodist.editor.video_url_label': "Video-dars (YouTube/S3 havola)",
  'methodist.editor.coin_label': "Mukofot (koinlar)",
  'methodist.editor.question_required': "Savol kiritilishi shart",
  'methodist.editor.option_required': "Variant {{letter}} kiritilishi shart",
  'methodist.editor.correct_answer_required': "To'g'ri javob kiritilishi shart",
  'methodist.editor.title_required': "Nomi kiritilishi shart",
  'methodist.editor.invalid_url': "Noto'g'ri havola",
  'methodist.editor.description_required_practical': "Amaliy topshiriq uchun tavsif majburiy — AI-tahlil aynan shunga tayanadi",
  'methodist.editor.question_prefix': "Savol",
  'methodist.editor.type_choice': "Variantlar",
  'methodist.editor.type_riddle': "Topishmoq",
  'methodist.editor.type_open': "Savol va javob",
  'methodist.profile.role_methodist': "Metodist",
  'methodist.profile.email': "Email",
  'methodist.profile.branch': "Filial",
  'methodist.profile.registered': "Ro'yxatdan o'tgan",
  'methodist.profile.load_error': "Profilni yuklashda xatolik",
  'methodist.profile.personal_data': "Shaxsiy ma'lumotlar",
  'methodist.profile.personal_data_hint': "Bu ma'lumotlarni tashkilot admini ko'radi.",
  'methodist.profile.first_name': "Ism",
  'methodist.profile.last_name': "Familiya",
  'methodist.profile.email_hint': "Siz tizimga shu email orqali kirasiz, parolni tiklash kodi ham shu manzilga keladi.",
  'methodist.profile.saved': "Saqlangan",
  'methodist.profile.dirty': "Saqlanmagan o'zgarishlar bor",
  'methodist.profile.enter_name': "Ism kiriting",
  'methodist.profile.enter_last': "Familiya kiriting",
  'methodist.profile.invalid_email': "Noto'g'ri email",
  'methodist.profile.save_failed': "Saqlab bo'lmadi",
  'methodist.profile.security': "Xavfsizlik",
  'methodist.profile.password': "Parol",
  'methodist.profile.password_hint': "Xavfsizlik maqsadida parol bu yerda o'zgartirilmaydi — u emailingizga yuboriladigan tasdiqlash kodi orqali tiklanadi.",
  'methodist.profile.reset_password': "Parolni tiklash",
  'methodist.profile.end_session': "Seansni yakunlash",
  'methodist.profile.session_hint': "Siz bu qurilmadagi akkauntdan chiqasiz.",
  'methodist.profile.logout': "Chiqish",

  // admin/Dashboard.jsx
  'admin.dash.title': 'Dashboard',
  'admin.dash.loadError': 'Yuklashda xatolik: {{message}}',
  'admin.dash.subtitle': 'Bugun {{today}} · filialingiz haqida umumiy ma\'lumot',
  'admin.dash.branchStats': 'Filial ko\'rsatkichlari',
  'admin.dash.activeStudents': 'Faol o\'quvchilar',
  'admin.dash.groups': 'Guruhlar',
  'admin.dash.overdueInvoices': 'Muddati o\'tgan hisoblar',
  'admin.dash.recentPayments': 'So\'nggi to\'lovlar',
  'admin.dash.noPayments': 'Hozircha to\'lovlar yo\'q',
  'admin.dash.student': 'O\'quvchi',
  'admin.dash.thisMonth': 'Shu oyda',
  'admin.dash.revenue': 'Daromad',
  'admin.dash.expenses': 'Xarajat',
  'admin.dash.profit': 'Foyda',
  'admin.dash.studentsThisMonth': 'Shu oydagi o\'quvchilar',
  'admin.dash.arrived': 'Kelgan',
  'admin.dash.left': 'Ketgan (arxiv)',
  'admin.dash.netGrowth': 'Sof o\'sish',

  // admin/Shop.jsx
  'admin.shop.statusPending': 'Kutilmoqda',
  'admin.shop.statusFulfilled': 'Berildi',
  'admin.shop.statusCancelled': 'Bekor qilindi',
  'admin.shop.fromSeo': 'SEO dan',
  'admin.shop.branchItem': 'Filial tovari',
  'admin.shop.archived': 'Arxivda',
  'admin.shop.coinsPrice': '{{price}} coin',
  'admin.shop.stockLeft': 'Qoldiq: {{count}} dona',
  'admin.shop.newStock': 'Yangi qoldiq',
  'admin.shop.update': 'Yangilash',
  'admin.shop.orderCoins': '{{name}} · {{price}} coin',
  'admin.shop.fulfill': 'Berish',
  'admin.shop.cancel': 'Bekor qilish',
  'admin.shop.restockFailed': 'Qoldiqni yangilab bo\'lmadi',
  'admin.shop.createFailed': 'Tovarni qo\'shib bo\'lmadi',
  'admin.shop.fulfillFailed': 'Berilganini belgilab bo\'lmadi',
  'admin.shop.cancelFailed': 'Buyurtmani bekor qilib bo\'lmadi',
  'admin.shop.confirmCancel': 'Buyurtmani bekor qilasizmi? Coinlar o\'quvchiga qaytadi, tovar omborga qaytadi.',
  'admin.shop.title': 'Do\'kon',
  'admin.shop.subtitle': 'SEO ning umumiy tovarlari va filialingizning mahalliy tovarlari.',
  'admin.shop.newItem': 'Yangi tovar',
  'admin.shop.itemsCount': 'Tovarlar',
  'admin.shop.ordersCount': 'Buyurtmalar',
  'admin.shop.pendingFulfillment': 'Berilishini kutmoqda',
  'admin.shop.tabItems': 'Tovarlar',
  'admin.shop.tabOrders': 'Buyurtmalar',
  'admin.shop.noItemsTitle': 'Hozircha tovarlar yo\'q',
  'admin.shop.noItemsHint': 'SEO hali bu filial uchun tovar qo\'shmagan',
  'admin.shop.noOrdersTitle': 'Hozircha buyurtmalar yo\'q',
  'admin.shop.noOrdersHint': 'O\'quvchilar hali tovar sotib olishmagan',
  'admin.shop.newBranchItem': 'Yangi filial tovari',
  'admin.shop.newBranchItemHint': 'Faqat sizning filialingizda mavjud bo\'ladi',
  'admin.shop.namePlaceholder': 'Nomi',
  'admin.shop.imagePlaceholder': 'Rasm havolasi (ixtiyoriy)',
  'admin.shop.pricePlaceholder': 'Narxi',
  'admin.shop.stockPlaceholder': 'Qoldiq',
  'admin.shop.cancelBtn': 'Bekor qilish',
  'admin.shop.add': 'Qo\'shish',

  // admin/Mentors.jsx
  'admin.mentors.gradeNotSet': 'Belgilanmagan',
  'admin.mentors.gradeTooltip': 'Grejdni SEO belgilaydi',
  'admin.mentors.edit': 'Tahrirlash',
  'admin.mentors.chatTooltip': 'Chatga yozish',
  'admin.mentors.title': 'Mentorlar',
  'admin.mentors.subtitle': 'Filial o\'qituvchilari',
  'admin.mentors.export': 'Eksport',
  'admin.mentors.addMentor': 'Mentor qo\'shish',
  'admin.mentors.total': 'Jami',
  'admin.mentors.active': 'Faol',
  'admin.mentors.frozen': 'Muzlatilgan',
  'admin.mentors.loadError': 'Yuklashda xatolik: {{message}}',
  'admin.mentors.emptyTitle': 'Mentorlar yo\'q',
  'admin.mentors.emptyHint': 'Birinchi o\'qituvchini qo\'shing',
  'admin.mentors.editTitle': 'Mentorni tahrirlash',
  'admin.mentors.newTitle': 'Yangi mentor',
  'admin.mentors.firstNamePlaceholder': 'Ism',
  'admin.mentors.lastNamePlaceholder': 'Familiya',
  'admin.mentors.emailPlaceholder': 'Email (kirish uchun)',
  'admin.mentors.genericError': 'Xatolik',
  'admin.mentors.cancel': 'Bekor qilish',
  'admin.mentors.save': 'Saqlash',
  'admin.mentors.createdTitle': 'Mentor yaratildi',
  'admin.mentors.createdHint': 'Parol faqat bir marta ko\'rsatiladi — uni hozir mentorga yetkazing.',
  'admin.mentors.emailLabel': 'Email',
  'admin.mentors.passwordLabel': 'Parol',
  'admin.mentors.done': 'Tayyor',

  // admin/Schedule.jsx
  'admin.schedule.oddDays': 'Toq kunlar',
  'admin.schedule.evenDays': 'Juft kunlar',
  'admin.schedule.otherDays': 'Boshqa',
  'admin.schedule.otherSubject': 'Boshqa',
  'admin.schedule.selectDay': 'Kamida bitta kunni tanlang',
  'admin.schedule.saveFailed': 'Saqlab bo\'lmadi',
  'admin.schedule.timeSubtitle': 'Dars kunlari va boshlanish vaqti',
  'admin.schedule.cancel': 'Bekor qilish',
  'admin.schedule.save': 'Saqlash',
  'admin.schedule.title': 'Jadval',
  'admin.schedule.subtitle': 'Xonalar qatorlarda, dars vaqtlari ustunlarda.',
  'admin.schedule.room': 'Xona',
  'admin.schedule.emptyTitle': 'Hozircha xonalar va guruhlar yo\'q',
  'admin.schedule.emptyHint': 'Xona yarating — guruhlar jadvalda paydo bo\'ladi',
  'admin.schedule.searchPlaceholder': 'Guruh yoki mentor',
  'admin.schedule.emptySlots': 'Bo\'sh slotlar',
  'admin.schedule.slots': 'Slotlar',
  'admin.schedule.confirmDeleteRoom': '«{{name}}» xonasini o\'chirasizmi?',
  'admin.schedule.deleteRoomFailed': 'Xonani o\'chirib bo\'lmadi',
  'admin.schedule.createRoomFailed': 'Xona yaratib bo\'lmadi',
  'admin.schedule.moveGroupFailed': 'Guruhni ko\'chirib bo\'lmadi',
  'admin.schedule.newRoom': 'Yangi xona',
  'admin.schedule.roomNamePlaceholder': 'Nomi (masalan A1)',
  'admin.schedule.capacityPlaceholder': 'Sig\'imi',
  'admin.schedule.create': 'Yaratish',

  // admin/Profile.jsx
  'admin.profile.loadErrorPrefix': 'Profilni yuklab bo\'lmadi: {{message}}. Sessiyadagi ma\'lumotlar ko\'rsatilmoqda.',
  'admin.profile.retry': 'Qayta urinish',
  'admin.profile.emailLabel': 'Email',
  'admin.profile.phoneLabel': 'Telefon',
  'admin.profile.registeredLabel': 'Ro\'yxatdan o\'tgan',
  'admin.profile.personalData': 'Shaxsiy ma\'lumotlar',
  'admin.profile.personalDataHint': 'Bu ma\'lumotlarni tashkilot admini ko\'radi.',
  'admin.profile.firstNameLabel': 'Ism',
  'admin.profile.lastNameLabel': 'Familiya',
  'admin.profile.emailHint': 'Siz tizimga shu email orqali kirasiz, parolni tiklash kodi ham shu manzilga keladi.',
  'admin.profile.saved': 'Saqlangan',
  'admin.profile.dirty': 'Saqlanmagan o\'zgarishlar bor',
  'admin.profile.cancel': 'Bekor qilish',
  'admin.profile.save': 'Saqlash',
  'admin.profile.security': 'Xavfsizlik',
  'admin.profile.password': 'Parol',
  'admin.profile.passwordHint': 'Xavfsizlik maqsadida parol bu yerda o\'zgartirilmaydi — u emailingizga yuboriladigan tasdiqlash kodi orqali tiklanadi.',
  'admin.profile.resetPassword': 'Parolni tiklash',
  'admin.profile.endSession': 'Seansni yakunlash',
  'admin.profile.sessionHint': 'Siz bu qurilmadagi akkauntdan chiqasiz.',
  'admin.profile.logout': 'Chiqish',
  'admin.profile.enterName': 'Ism kiriting',
  'admin.profile.enterLast': 'Familiya kiriting',
  'admin.profile.invalidEmail': 'Noto\'g\'ri email',
  'admin.profile.saveFailed': 'Saqlab bo\'lmadi',

  // admin/MentorDetail.jsx
  'admin.mentorDetail.currency': "so'm",
  'admin.mentorDetail.backToMentors': 'Mentorlarga',
  'admin.mentorDetail.gradeTooltip': 'Mentor darajasi',
  'admin.mentorDetail.emailLabel': 'Email',
  'admin.mentorDetail.phoneLabel': 'Telefon',
  'admin.mentorDetail.notSpecified': 'Kiritilmagan',
  'admin.mentorDetail.skills': "Ko'nikmalar",
  'admin.mentorDetail.freeze': 'Muzlatish',
  'admin.mentorDetail.unfreeze': "Muzdan chiqarish",
  'admin.mentorDetail.edit': 'Tahrirlash',
  'admin.mentorDetail.chat': 'Chat',
  'admin.mentorDetail.archive': 'Arxivlash',
  'admin.mentorDetail.groups': 'Guruhlar',
  'admin.mentorDetail.students': "O'quvchilar",
  'admin.mentorDetail.noGroups': "Guruhlar yo'q",
  'admin.mentorDetail.studentsShort': '{{count}} o\'q.',
  'admin.mentorDetail.editTitle': 'Mentorni tahrirlash',
  'admin.mentorDetail.firstNameLabel': 'Ism',
  'admin.mentorDetail.lastNameLabel': 'Familiya',
  'admin.mentorDetail.cancel': 'Bekor qilish',
  'admin.mentorDetail.save': 'Saqlash',
  'admin.mentorDetail.freezeTitle': 'Mentorni muzlatish',
  'admin.mentorDetail.freezeConfirm': '{{name}}ni muzlatmoqchimisiz?',
  'admin.mentorDetail.freezeHint': "O'qituvchi tizimga kira olmaydi, lekin ma'lumotlari saqlanadi. Sababini ko'rsating.",
  'admin.mentorDetail.freezeReasonPlaceholder': 'Muzlatish sababi…',
  'admin.mentorDetail.archiveTitle': 'Mentorni arxivlash',
  'admin.mentorDetail.archiveConfirm': '{{name}}ni arxivlamoqchimisiz?',
  'admin.mentorDetail.archiveHint': "Mentor faol ro'yxatdan yashiriladi. Bu amalni interfeys orqali bekor qilib bo'lmaydi.",
  'admin.mentorDetail.notFound': 'Mentor topilmadi',

  // admin/Reports.jsx
  'admin.reports.title': 'Hisobotlar',
  'admin.reports.loading': 'Yuklanmoqda...',
  'admin.reports.loadError': 'Yuklashda xatolik: {{message}}',
  'admin.reports.retry': 'Qayta urinish',
  'admin.reports.subtitle': 'Guruhlar bo\'yicha daromad va qarzlar tahlili',
  'admin.reports.export': 'Eksport',
  'admin.reports.searchPlaceholder': 'Guruh nomi bo\'yicha qidirish...',
  'admin.reports.period': 'Davr:',
  'admin.reports.reset': 'Tozalash',
  'admin.reports.totalRevenue': 'Umumiy daromad',
  'admin.reports.totalDebt': 'Umumiy qarz',
  'admin.reports.groupsCount': '{{count}} ta guruh',
  'admin.reports.students': 'O\'quvchilar',
  'admin.reports.avgRevenue': 'O\'rtacha daromad',
  'admin.reports.revenueByGroup': 'Guruhlar bo\'yicha daromad',
  'admin.reports.revenueShare': 'Daromad ulushi',
  'admin.reports.noData': 'Ma\'lumot yo\'q',
  'admin.reports.revenue': 'Daromad',
  'admin.reports.debt': 'Qarz',
  'admin.reports.colGroup': 'Guruh',
  'admin.reports.colStudents': 'O\'quvchilar',
  'admin.reports.colRevenue': 'Daromad',
  'admin.reports.colDebt': 'Qarz',
  'admin.reports.colRatio': 'Nisbat',
  'admin.reports.nothingFound': 'Hech narsa topilmadi',
  'admin.reports.tryAnotherQuery': 'Boshqa so\'rovni sinab ko\'ring',
  'admin.reports.noReportData': 'Hozircha hisobot ma\'lumotlari yo\'q',
  'admin.reports.totalRevenueColon': 'Umumiy daromad:',
  'admin.reports.totalDebtColon': 'Umumiy qarz:',

  // admin/Students.jsx
  'admin.students.archiveConfirm': '{{name}} o\'quvchisini arxivlaysizmi?\n\nO\'quvchi ro\'yxatdan yashiriladi, lekin ma\'lumotlari saqlanadi.',
  'admin.students.title': "O'quvchilar",
  'admin.students.subtitle': "Filial o'quvchilari hisobi",
  'admin.students.add': "O'quvchi qo'shish",
  'admin.students.searchPlaceholder': 'Ism, familiya yoki telefon bo\'yicha qidirish…',
  'admin.students.filterAll': 'Hammasi',
  'admin.students.filterDebt': 'Qarzdor',
  'admin.students.emptySearchTitle': 'Boshqa so\'rovni sinab ko\'ring',
  'admin.students.emptyTitle': "O'quvchilar yo'q",
  'admin.students.emptyHint': "Birinchi o'quvchini qo'shing",
  'admin.students.addShort': "Qo'shish",
  'admin.students.colStudent': "O'quvchi",
  'admin.students.colPhone': 'Telefon',
  'admin.students.colMentor': 'Mentor',
  'admin.students.colGroup': 'Guruh',
  'admin.students.colDirection': "Yo'nalish",
  'admin.students.newTitle': "Yangi o'quvchi",
  'admin.students.newSubtitle': "Ma'lumotlarni to'ldiring — login va parol avtomatik yaratiladi",
  'admin.students.firstNameLabel': 'Ism *',
  'admin.students.lastNameLabel': 'Familiya *',
  'admin.students.genderLabel': 'Jinsi',
  'admin.students.male': 'Erkak',
  'admin.students.female': 'Ayol',
  'admin.students.birthDateLabel': "Tug'ilgan sana",
  'admin.students.phoneLabel': 'Telefon *',
  'admin.students.phoneOwnerLabel': 'Kimga tegishli',
  'admin.students.phoneOwnerPlaceholder': "O'quvchiga",
  'admin.students.parentNameLabel': 'Ota-ona ismi *',
  'admin.students.parentPhoneLabel': 'Ota-ona telefoni *',
  'admin.students.parentPhoneOwnerPlaceholder': 'Ota-onaga',
  'admin.students.extraPhoneLabel': "Qo'shimcha telefon",
  'admin.students.groupLabel': 'Guruh',
  'admin.students.noGroup': 'Guruhsiz',
  'admin.students.languageLabel': "O'qish tili",
  'admin.students.langRu': 'Ruscha',
  'admin.students.sourceLabel': 'Manba',
  'admin.students.sourceReferral': 'Tavsiya orqali',
  'admin.students.sourceWalkIn': "O'zi kelgan",
  'admin.students.schoolLabel': 'Maktab raqami',
  'admin.students.addressLabel': 'Manzil',
  'admin.students.commentLabel': "O'qituvchi uchun izoh",
  'admin.students.hasLaptop': 'Noutbuk bor',
  'admin.students.offerSigned': 'Oferta imzolangan',
  'admin.students.parentNote': "Chapda ota-onaning ismi, familiyasi va telefoni to'ldirilsa, unga ham alohida kirish yaratiladi.",
  'admin.students.cancel': 'Bekor qilish',
  'admin.students.create': 'Yaratish',
  'admin.students.credsTitle': 'Kirish ma\'lumotlari',
  'admin.students.credsHint': "O'quvchiga bering. Parol faqat bir marta ko'rsatiladi.",
  'admin.students.loginCode': 'Login-kod',
  'admin.students.password': 'Parol',
  'admin.students.parentLabel': 'Ota-ona ({{firstName}} {{lastName}})',
  'admin.students.gotIt': 'Tushunarli',

  // admin/Discipline.jsx
  'admin.discipline.roleMentor': 'Mentor',
  'admin.discipline.roleMethodist': 'Metodist',
  'admin.discipline.roleAdmin': 'Administrator',
  'admin.discipline.selectStaff': 'Xodimni tanlang',
  'admin.discipline.specifyReason': 'Sababni ko\'rsating',
  'admin.discipline.percentRange': 'Foiz 0 dan 100 gacha bo\'lishi kerak',
  'admin.discipline.issueTitle': 'Xodimga jazo',
  'admin.discipline.cancel': 'Bekor qilish',
  'admin.discipline.issue': 'Chiqarish',
  'admin.discipline.staffLabel': 'Xodim',
  'admin.discipline.chooseStaff': 'Xodimni tanlang',
  'admin.discipline.noStaffFound': 'Xodimlar topilmadi',
  'admin.discipline.percentLabel': 'Oyliqdan foiz (ixtiyoriy)',
  'admin.discipline.percentHint': 'Oyliqdan ushlab qolinadigan foiz (masalan, 5 = oyliqdan −5%)',
  'admin.discipline.reasonLabel': 'Sabab',
  'admin.discipline.reasonPlaceholder': 'Nima uchun jazo berilmoqda',
  'admin.discipline.qoraWarning': 'Xodim tizimga kirish huquqini yo\'qotadi. Uni faqat Super Admin qaytara oladi.',
  'admin.discipline.ruleLabel': 'Intizom qoidasi',
  'admin.discipline.chooseRule': 'Qoidani tanlang (foiz avtomatik to\'ldiriladi)',
  'admin.discipline.ruleTooltip': 'Tanlanganda foiz avtomatik to\'ldiriladi',
  'admin.discipline.ruleHint': 'Super Admin belgilagan qoidalardan birini tanlang — foiz avtomatik to\'ldiriladi',
  'admin.discipline.rulesUnavailablePrefix': 'Admin uchun qoidalar ro\'yxati hozircha mavjud emas — foizni qo\'lda kiriting. Qoidalarni Super Admin boshqaradi (frontend',
  'admin.discipline.rulesUnavailableSuffix': 'ni Karisdan kutmoqda).',
  'admin.discipline.describeRule': 'Bu qoida nima uchun berilishini tavsiflang',
  'admin.discipline.newRuleTitle': 'Yangi qoida',
  'admin.discipline.save': 'Saqlash',
  'admin.discipline.gapWarningPrefix': 'Admin uchun qoida yaratish backendda hali ulanmagan — hozircha bu faqat Super Adminda mavjud (uning Intizom panelidagi «Yangi qoida»). Frontend tayyor,',
  'admin.discipline.gapWarningSuffix': 'ni Karisdan kutmoqda.',
  'admin.discipline.levelLabel': 'Daraja',
  'admin.discipline.percentAmountLabel': 'Oyliqdan foiz, % (ixtiyoriy)',
  'admin.discipline.percentPlaceholder': 'Masalan, 5',
  'admin.discipline.whatForLabel': 'Nima uchun',
  'admin.discipline.whatForPlaceholder': 'Masalan: 15 daqiqadan ko\'p kechikish',
  'admin.discipline.appliesToAll': 'Qoida tashkilotning barcha xodimlariga qo\'llaniladi — aniq mentor tanlash shart emas.',
  'admin.discipline.rulesTitle': 'Intizom qoidalari',
  'admin.discipline.newRule': 'Yangi qoida',
  'admin.discipline.noRulesTitle': 'Hozircha qoidalar yo\'q',
  'admin.discipline.noRulesHint': 'Buzilishni va u uchun jazo darajasini tasvirlang — qoida tashkilotning barcha xodimlariga qo\'llaniladi.',
  'admin.discipline.colRule': 'Qoida',
  'admin.discipline.colLevel': 'Daraja',
  'admin.discipline.colPercent': 'Oyliqdan %',
  'admin.discipline.colAdded': 'Qo\'shilgan',
  'admin.discipline.title': 'Intizom',
  'admin.discipline.subtitle': 'Filial xodimlarining jazolari',
  'admin.discipline.issueBtn': 'Jazo',
  'admin.discipline.yellow': 'Sariq',
  'admin.discipline.red': 'Qizil',
  'admin.discipline.black': 'Ishdan bo\'shatish',
  'admin.discipline.warningsUnit': 'ogohlantirish',
  'admin.discipline.dismissalsUnit': 'ishdan bo\'shatish',
  'admin.discipline.historyTitle': 'Jazolar tarixi',
  'admin.discipline.filterAll': 'Hammasi',
  'admin.discipline.noPenaltiesTitle': 'Jazolar yo\'q',
  'admin.discipline.emptyCategoryTitle': 'Bu toifada hech narsa yo\'q',
  'admin.discipline.noPenaltiesHint': 'Yaxshi xabar: xodimlar buzilishlarsiz ishlayapti.',
  'admin.discipline.colStaff': 'Xodim',
  'admin.discipline.colType': 'Turi',
  'admin.discipline.colReason': 'Sabab',
  'admin.discipline.colIssuedBy': 'Chiqargan',
  'admin.discipline.colWhen': 'Qachon',

  // shared invoice statuses (admin/Payments.jsx and other invoice views)
  'status.paid': "To'langan",
  'status.partiallyPaid': 'Qisman',
  'status.pending': 'Kutilmoqda',
  'status.overdue': "Muddati o'tgan",
  'status.cancelled': 'Bekor qilindi',

  // admin/Payments.jsx
  'admin.payments.filterAll': 'Hammasi',
  'admin.payments.addPart': "Qism qo'shish (split)",
  'admin.payments.amountPlaceholder': 'Summa',
  'admin.payments.openStudentProfile': "O'quvchi profilini ochish",
  'admin.payments.amount': 'Summa',
  'admin.payments.paidAmount': "To'langan",
  'admin.payments.details': 'Batafsil',
  'admin.payments.pay': "To'lash",
  'admin.payments.title': "To'lovlar",
  'admin.payments.subtitle': "Hisoblar va to'lovlar (naqd + karta)",
  'admin.payments.invoicesCount': '{{count}} ta hisob',
  'admin.payments.export': 'Eksport',
  'admin.payments.oneTimePayment': "Bir martalik to'lov",
  'admin.payments.searchPlaceholder': "O'quvchi ismi bo'yicha qidirish...",
  'admin.payments.totalInvoices': 'Jami hisoblar',
  'admin.payments.paid': "To'langan",
  'admin.payments.waiting': 'Kutilmoqda',
  'admin.payments.overdue': "Muddati o'tgan",
  'admin.payments.loadError': 'Yuklashda xatolik: {{message}}',
  'admin.payments.noInvoicesTitle': 'Hisoblar yo\'q',
  'admin.payments.noInvoicesHint': 'Hisoblar shu yerda paydo bo\'ladi',
  'admin.payments.nothingFoundTitle': 'Hech narsa topilmadi',
  'admin.payments.nothingFoundHint': "Filtrlarni o'zgartirib ko'ring",
  'admin.payments.pageOf': '{{page}}/{{total}}-sahifa',
  'admin.payments.acceptPaymentTitle': "To'lovni qabul qilish",
  'admin.payments.invoiceLine': 'Hisob: {{date}} · Qoldiq: {{amount}}',
  'admin.payments.total': 'Jami: {{amount}}',
  'admin.payments.exceedsRemaining': "Qoldiqdan oshib ketmoqda!",
  'admin.payments.cancel': 'Bekor qilish',
  'admin.payments.accept': 'Qabul qilish',
  'admin.payments.oneTimeTitle': "Bir martalik to'lov",
  'admin.payments.oneTimeHint': "Hisob yaratish va jadvaldan tashqari to'lovni qabul qilish",
  'admin.payments.studentLabel': "O'quvchi",
  'admin.payments.studentSearchPlaceholder': 'Ism, familiya yoki sana bo\'yicha qidirish...',
  'admin.payments.studentNotFound': "O'quvchi topilmadi",
  'admin.payments.invoiceAmountLabel': 'Hisob summasi',
  'admin.payments.partsLabel': "To'lov qismlari",
  'admin.payments.partsTotal': 'Qismlar jami: {{amount}}',
  'admin.payments.exceedsInvoice': "Hisob summasidan oshib ketmoqda!",
  'admin.payments.remaining': 'Qoldiq: {{amount}}',
  'admin.payments.create': 'Yaratish',
  'admin.payments.transactions': 'Tranzaksiyalar ({{count}})',
  'admin.payments.reverseTab': 'Qaytarish / Bekor qilish',
  'admin.payments.receiptTab': 'Chek',
  'admin.payments.noTransactions': 'Bu hisob uchun tranzaksiyalar yo\'q',
  'admin.payments.chooseCompletedTx': 'Qaytarish yoki bekor qilish uchun yakunlangan tranzaksiyani tanlang:',
  'admin.payments.noCompletedTx': 'Yakunlangan tranzaksiyalar yo\'q',
  'admin.payments.chooseTx': 'Tranzaksiyani tanlang...',
  'admin.payments.refund': 'Qaytarish (Refund)',
  'admin.payments.void': 'Bekor qilish (Void)',
  'admin.payments.reasonPlaceholder': 'Sabab (qaytarish uchun majburiy)',
  'admin.payments.doRefund': 'Qaytarishni bajarish',
  'admin.payments.doVoid': 'Bekor qilish',
  'admin.payments.uploadReceiptLabel': 'Tranzaksiya uchun chek yuklash:',
  'admin.payments.receiptExists': " (✅ chek bor)",
  'admin.payments.clickToChooseFile': 'Fayl tanlash uchun bosing',
  'admin.payments.uploading': 'Yuklanmoqda...',
  'admin.payments.close': 'Yopish',
  'admin.payments.sumMismatch': 'Qismlar summasi ({{parts}}) hisob summasiga ({{total}}) mos kelmayapti',
  'admin.payments.genericError': 'Xatolik',
  'admin.payments.studentFetchFailed': "O'quvchi ma'lumotlarini olib bo'lmadi",
  'admin.payments.receiptUploadFailed': 'Chekni yuklashda xatolik',
  'admin.payments.summary': 'Summa',
  'admin.payments.dueDate': 'Muddat',

  // admin/Expenses.jsx
  'admin.expenses.catAll': 'Hammasi',
  'admin.expenses.catRent': 'Ijara',
  'admin.expenses.catSalary': 'Oylik',
  'admin.expenses.catMaterials': 'Materiallar',
  'admin.expenses.catUtility': 'Kommunal',
  'admin.expenses.catOther': 'Boshqa',
  'admin.expenses.statusRejected': 'Rad etildi',
  'admin.expenses.methodCash': 'Naqd pul',
  'admin.expenses.methodCard': 'Karta',
  'admin.expenses.methodBank': 'Bank',
  'admin.expenses.methodTransfer': "O'tkazma",
  'admin.expenses.currency': "so'm",
  'admin.expenses.view': "Ko'rish",
  'admin.expenses.edit': 'Tahrirlash',
  'admin.expenses.delete': "O'chirish",
  'admin.expenses.refresh': 'Yangilash',
  'admin.expenses.title': 'Xarajatlar',
  'admin.expenses.subtitle': "Tashkilot xarajatlarini hisobga olish, boshqarish va tahlil qilish",
  'admin.expenses.export': 'Eksport',
  'admin.expenses.addExpense': "Xarajat qo'shish",
  'admin.expenses.searchPlaceholder': 'Xarajatlarni qidirish...',
  'admin.expenses.categoryFilterLabel': 'Kategoriya',
  'admin.expenses.categoryLabel': 'Kategoriya:',
  'admin.expenses.reset': 'Tozalash',
  'admin.expenses.nothingFoundTitle': 'Hech narsa topilmadi',
  'admin.expenses.emptyTitle': "Hozircha xarajatlar yo'q",
  'admin.expenses.nothingFoundHint': "Qidiruv yoki filtr parametrlarini o'zgartirib ko'ring",
  'admin.expenses.emptyHint': "Boshlash uchun birinchi xarajatni qo'shing",
  'admin.expenses.colCategory': 'Kategoriya',
  'admin.expenses.colNote': 'Izoh',
  'admin.expenses.colAmount': 'Summa',
  'admin.expenses.colMethod': "To'lov usuli",
  'admin.expenses.colDate': 'Sana',
  'admin.expenses.colRecurring': 'Takrorlanish',
  'admin.expenses.colStatus': 'Holat',
  'admin.expenses.colCreatedBy': 'Yaratdi',
  'admin.expenses.everyMonth': 'Har oy',
  'admin.expenses.everyQuarter': 'Har chorak',
  'admin.expenses.everyYear': 'Har yil',
  'admin.expenses.expensesCount': '{{count}} ta xarajat',
  'admin.expenses.ofTotal': '(jami {{count}})',
  'admin.expenses.total': 'Jami:',
  'admin.expenses.updating': 'Yangilanmoqda...',
  'admin.expenses.byCategory': 'Kategoriyalar bo\'yicha',
  'admin.expenses.budget': 'Byudjet',
  'admin.expenses.noExpenseData': "Xarajatlar haqida ma'lumot yo'q",
  'admin.expenses.monthlyTrend': "Oylar bo'yicha tendensiya",
  'admin.expenses.noTrendData': "Tendensiya haqida ma'lumot yo'q",
  'admin.expenses.detailsTitle': 'Xarajat tafsilotlari',
  'admin.expenses.amountLabel': 'Summa',
  'admin.expenses.dateLabel': 'Sana',
  'admin.expenses.methodLabel': "To'lov usuli",
  'admin.expenses.recurringLabel': 'Takrorlanuvchi',
  'admin.expenses.nextPayment': ' — keyingi: {{date}}',
  'admin.expenses.createdByLabel': 'Yaratdi',
  'admin.expenses.noteLabel': 'Izoh',
  'admin.expenses.none': "Yo'q",
  'admin.expenses.close': 'Yopish',
  'admin.expenses.editTitle': 'Xarajatni tahrirlash',
  'admin.expenses.cancel': 'Bekor qilish',
  'admin.expenses.saving': 'Saqlanmoqda...',
  'admin.expenses.save': 'Saqlash',
  'admin.expenses.add': "Qo'shish",
  'admin.expenses.categoryRequired': 'Kategoriya *',
  'admin.expenses.titleRequired': 'Xarajat nomi *',
  'admin.expenses.titlePlaceholder': 'Masalan: Wi-Fi, kantselyariya, ta\'mirlash',
  'admin.expenses.amountRequired': 'Summa *',
  'admin.expenses.recurringExpenseLabel': 'Takrorlanuvchi xarajat',
  'admin.expenses.autoAddMonthly': "Har oy avtomatik qo'shilsin",
  'admin.expenses.recurringPeriodLabel': 'Takrorlanish davri',
  'admin.expenses.nextPaymentDateRequired': "Keyingi to'lov sanasi *",
  'admin.expenses.noteCommentPlaceholder': 'Xarajatga izoh',
  'admin.expenses.editUnavailable': "Tahrirlash hozircha ishlamaydi — backendda PATCH yo'q. Karisga xabar bering.",
  'admin.expenses.saveFailed': 'Xarajatni saqlashda xatolik',
  'admin.expenses.deleteFailed': "O'chirishda xatolik",
  'admin.expenses.deleteTitle': "Xarajatni o'chirish",
  'admin.expenses.deleting': "O'chirilmoqda...",
  'admin.expenses.confirmTitle': 'Ishonchingiz komilmi?',
  'admin.expenses.confirmBody': ' — bu xarajatni o\'chirasizmi? Bu amalni bekor qilib bo\'lmaydi.',
  'admin.expenses.filename': 'xarajatlar',

  // admin/StudentDetail.jsx
  'admin.studentDetail.currency': "so'm",
  'admin.studentDetail.soon': 'Bu funksiya hali ishlab chiqilmoqda',
  'admin.studentDetail.backToStudents': "O'quvchilarga",
  'admin.studentDetail.loginPasswordTooltip': 'Login va parol',
  'admin.studentDetail.offerSigned': 'Oferta imzolangan',
  'admin.studentDetail.offerNotSigned': 'Oferta imzolanmagan',
  'admin.studentDetail.phoneLabel': 'Telefon',
  'admin.studentDetail.notSpecified': 'Kiritilmagan',
  'admin.studentDetail.parentLabel': 'Ota-ona',
  'admin.studentDetail.parentLoginTooltip': 'Ota-ona login va paroli',
  'admin.studentDetail.telegramLabel': 'Telegram',
  'admin.studentDetail.write': 'Yozish',
  'admin.studentDetail.notConnected': "Ulanmagan",
  'admin.studentDetail.graduate': 'Bitiruvchi',
  'admin.studentDetail.expel': "Chetlashtirish",
  'admin.studentDetail.newPassword': 'Yangi parol',
  'admin.studentDetail.sms': 'SMS',
  'admin.studentDetail.referral': 'Referal',
  'admin.studentDetail.changeGroup': "Guruhni almashtirish",
  'admin.studentDetail.addToGroup': "Guruhga qo'shish",
  'admin.studentDetail.topUpBalance': "Hisobni to'ldirish",
  'admin.studentDetail.profileFilled': "Profil to'ldirilgan",
  'admin.studentDetail.fieldBirthDate': "Tug'ilgan sana",
  'admin.studentDetail.fieldPhone': 'Telefon',
  'admin.studentDetail.fieldParent': 'Ota-ona',
  'admin.studentDetail.fieldGender': 'Jinsi',
  'admin.studentDetail.fieldAddress': 'Manzil',
  'admin.studentDetail.fieldSchool': 'Maktab',
  'admin.studentDetail.fieldLaptop': 'Noutbuk',
  'admin.studentDetail.allGroups': 'Barcha guruhlar',
  'admin.studentDetail.courseLabel': 'Kurs',
  'admin.studentDetail.mentorLabel': 'Mentor',
  'admin.studentDetail.lessonTimeLabel': 'Dars vaqti',
  'admin.studentDetail.priceLabel': 'Narxi',
  'admin.studentDetail.perMonth': '/oy',
  'admin.studentDetail.noGroupAttached': "Guruhga biriktirilmagan",
  'admin.studentDetail.attendanceTitle': 'Davomat',
  'admin.studentDetail.noDataYet': "Hozircha ma'lumot yo'q",
  'admin.studentDetail.attendanceHint': 'Davomat birinchi belgilangan darsdan keyin paydo bo\'ladi',
  'admin.studentDetail.paymentHistory': "To'lovlar tarixi",
  'admin.studentDetail.noPayments': "To'lovlar yo'q",
  'admin.studentDetail.acceptedBy': 'Qabul qildi: {{name}}',
  'admin.studentDetail.paid': "To'landi",
  'admin.studentDetail.notPaid': "To'lanmagan",
  'admin.studentDetail.monthlyDebtLine': 'Oylik: {{price}} · Qarz: {{debt}}',
  'admin.studentDetail.coins': 'Coinlar',
  'admin.studentDetail.debt': 'Qarz',
  'admin.studentDetail.invoices': 'Hisoblar',
  'admin.studentDetail.emptyYet': 'Hozircha bo\'sh',
  'admin.studentDetail.split': 'Split',
  'admin.studentDetail.full': "To'liq",
  'admin.studentDetail.stPaid': "To'landi",
  'admin.studentDetail.stPartial': 'Qisman',
  'admin.studentDetail.stPending': 'Kutilmoqda',
  'admin.studentDetail.stOverdue': 'Qarz',
  'admin.studentDetail.stCancelled': 'Bekor qilindi',
  'admin.studentDetail.attPresent': 'Keldi',
  'admin.studentDetail.attLate': 'Kechikdi',
  'admin.studentDetail.attAbsent': 'Kelmadi',
  'admin.studentDetail.attExcused': 'Sababli',
  'admin.studentDetail.credsTitle': 'Kirish ma\'lumotlari',
  'admin.studentDetail.parentCredsTitle': 'Kirish ma\'lumotlari — Ota-ona',
  'admin.studentDetail.loginCode': 'Login-kod',
  'admin.studentDetail.password': 'Parol',
  'admin.studentDetail.passwordUnavailable': '— mavjud emas, «Yangi parol»ni bosing',
  'admin.studentDetail.newParentPassword': 'Ota-ona uchun yangi parol',
  'admin.studentDetail.qrAlt': 'Kirish uchun QR',
  'admin.studentDetail.qrAltParent': 'Ota-ona kirish uchun QR',
  'admin.studentDetail.qrError': 'QR yaratib bo\'lmadi — oynani qayta oching',
  'admin.studentDetail.qrHint': 'O\'quvchi telefon kamerasi bilan skanerlaydi — login va parolsiz darhol kabinetga kiradi. Kod doimiy, har safar skanerlashda ishlaydi — o\'quvchi nishoni kabi.',
  'admin.studentDetail.qrHintParent': 'Ota-ona telefon kamerasi bilan skanerlaydi — login va parolsiz darhol kabinetga kiradi. Kod doimiy, har safar skanerlashda ishlaydi.',
  'admin.studentDetail.newPasswordAlert': 'Yangi parol: {{password}}',
  'admin.studentDetail.newParentPasswordAlert': 'Ota-ona uchun yangi parol: {{password}}',
  'admin.studentDetail.generated': 'yaratildi',
  'admin.studentDetail.editTitle': "O'quvchini tahrirlash",
  'admin.studentDetail.firstNameLabel': 'Ism',
  'admin.studentDetail.lastNameLabel': 'Familiya',
  'admin.studentDetail.birthDateLabel': "Tug'ilgan sana",
  'admin.studentDetail.freezeTitle': "O'quvchini muzlatish",
  'admin.studentDetail.freezeConfirm': 'Nima uchun {{name}}ni muzlatyapsiz?',
  'admin.studentDetail.freezeHint': "Sababni ko'rsating — u boshqa xodimlarga ko'rinadi.",
  'admin.studentDetail.freezeReasonPlaceholder': 'Muzlatish sababi…',
  'admin.studentDetail.archiveTitle': "O'quvchini arxivlash",
  'admin.studentDetail.archiveConfirm': '{{name}}ni arxivlamoqchimisiz?',
  'admin.studentDetail.archiveHint': "O'quvchi faol ro'yxatdan yashiriladi, ma'lumotlar saqlanadi. Sababini ko'rsating.",
  'admin.studentDetail.archiveReasonPlaceholder': 'Arxivlash sababi…',
  'admin.studentDetail.notFound': "O'quvchi topilmadi",
  'admin.studentDetail.topUpTitle': "Hisobni to'ldirish",
  'admin.studentDetail.amountRequired': 'Summa *',
  'admin.studentDetail.amountPlaceholder': 'Masalan: 4.63',
  'admin.studentDetail.invalidAmount': "To'g'ri summani kiriting",
  'admin.studentDetail.remainingOnInvoice': 'Joriy hisob bo\'yicha qoldiq: {{amount}}. Ortiqcha to\'lov balansda saqlanadi.',
  'admin.studentDetail.forWhichMonth': 'Qaysi oy uchun?',
  'admin.studentDetail.methodRequired': "To'lov usuli *",
  'admin.studentDetail.commentLabel': 'Izoh',
  'admin.studentDetail.commentPlaceholder': 'Izoh (ixtiyoriy)',
  'admin.studentDetail.cancel': 'Bekor qilish',
  'admin.studentDetail.save': 'Saqlash',
  'admin.studentDetail.writeToTelegram': "Telegramga yozish",
  'admin.studentDetail.messagePlaceholder': 'Xabar matni…',
  'admin.studentDetail.enterText': 'Matn kiriting',
  'admin.studentDetail.sent': 'Yuborildi',
  'admin.studentDetail.send': 'Yuborish',
  'admin.studentDetail.transferToOtherGroup': "Boshqa guruhga o'tkazish",
  'admin.studentDetail.currentGroupsHint': 'Hozir: {{groups}} — o\'tkazishda o\'quvchi bu yerdan chiqadi.',
  'admin.studentDetail.selectGroupError': 'Guruhni tanlang',
  'admin.studentDetail.selectGroupPlaceholder': 'Guruhni tanlang…',
  'admin.studentDetail.transfer': "O'tkazish",
  'admin.studentDetail.add': "Qo'shish",

  // admin/Groups.jsx (GroupFormModal also reused in GroupDetail.jsx)
  'admin.groups.archived': 'Arxiv',
  'admin.groups.active': 'Faol',
  'admin.groups.editGroupTooltip': 'Guruhni tahrirlash',
  'admin.groups.archiveTooltip': 'Arxivlash',
  'admin.groups.restoreTooltip': 'Arxivdan tiklash',
  'admin.groups.studentsOfMax': '{{count}}/{{max}} o\'quvchi',
  'admin.groups.noStudentsYet': "Hozircha o'quvchilar yo'q",
  'admin.groups.scheduleLoadFailed': 'Mentor jadvalini yuklab bo\'lmadi',
  'admin.groups.enterGroupName': 'Guruh nomini kiriting',
  'admin.groups.selectDirection': "Yo'nalishni tanlang",
  'admin.groups.selectMentorRequired': 'Mentorni tanlang — bu majburiy maydon',
  'admin.groups.selectAtLeastOneDay': 'Kamida bitta dars kunini tanlang',
  'admin.groups.specifyStartTime': 'Dars boshlanish vaqtini ko\'rsating',
  'admin.groups.noFreeSlots': 'Mentorda tanlangan kunlarda bo\'sh vaqt yo\'q — kunlarni yoki mentorni o\'zgartiring',
  'admin.groups.studentCreatedTitle': 'O\'quvchi yaratildi',
  'admin.groups.editGroupTitle': 'Guruhni tahrirlash',
  'admin.groups.newGroupTitle': 'Yangi guruh',
  'admin.groups.done': 'Tayyor',
  'admin.groups.cancel': 'Bekor qilish',
  'admin.groups.saveChanges': "O'zgarishlarni saqlash",
  'admin.groups.createGroup': 'Guruh yaratish',
  'admin.groups.studentCreatedHeadline': "O'quvchi yaratildi va guruhga qo'shildi",
  'admin.groups.studentCreatedHint': "Bu ma'lumotlarni o'quvchiga kirish uchun bering",
  'admin.groups.loginCode': 'Login-kod',
  'admin.groups.password': 'Parol',
  'admin.groups.copied': 'Nusxalandi',
  'admin.groups.copy': 'Nusxalash',
  'admin.groups.groupNameLabel': 'Guruh nomi',
  'admin.groups.groupNamePlaceholder': 'masalan Frontend React A1',
  'admin.groups.directionLabel': "Yo'nalish",
  'admin.groups.selectDirectionOption': "— Yo'nalishni tanlang —",
  'admin.groups.noEvaluatedDirections': "Hali baholangan yo'nalish yo'q — metodist metodikani yaratadi, SEO unga narx qo'yadi.",
  'admin.groups.priceSetBySeo': "Narxni butun metodika uchun SEO belgilaydi — bu yerda tahrirlanmaydi.",
  'admin.groups.priceLabel': 'Narx (UZS)',
  'admin.groups.roomLabel': 'Xona',
  'admin.groups.roomPlaceholder': 'masalan 204',
  'admin.groups.mentorLabel': 'Mentor',
  'admin.groups.selectMentorOption': '— Mentorni tanlang —',
  'admin.groups.noMentors': "Mentorlar yo'q — avval mentor qo'shing",
  'admin.groups.loadingMentorSchedule': 'Mentor jadvali yuklanmoqda…',
  'admin.groups.enterTimeManually': "vaqtni qo'lda kiriting",
  'admin.groups.mentorScheduleLoaded': 'Mentor jadvali yuklandi — quyida bo\'sh soatlarni ko\'rsatamiz',
  'admin.groups.lessonDaysLabel': 'Dars kunlari',
  'admin.groups.otherDaysBtn': 'Boshqa',
  'admin.groups.hasFreeTime': "Bo'sh vaqt bor",
  'admin.groups.dayBusy': 'Kun band',
  'admin.groups.startTimeLabel': 'Boshlanish vaqti',
  'admin.groups.selectDaysFirst': 'Avval dars kunlarini tanlang — mentorning bo\'sh soatlarini ko\'rsatamiz',
  'admin.groups.searchingFreeTime': 'Bo\'sh vaqt qidirilmoqda…',
  'admin.groups.freeHours': "Bo'sh soatlar ({{start}}:00–{{end}}:00)",
  'admin.groups.lessonMinutes': 'dars {{min}} daq',
  'admin.groups.noCommonFreeTime': 'Tanlangan kunlar uchun umumiy bo\'sh vaqt yo\'q — band kunlarni olib tashlang yoki boshqa mentorni tanlang',
  'admin.groups.noScheduleData': "Jadval ma'lumoti yo'q — vaqtni qo'lda kiriting",
  'admin.groups.endLabel': 'Tugash:',
  'admin.groups.minutesShort': '({{min}} daq)',
  'admin.groups.moduleLabel': 'Modul',
  'admin.groups.module1': '1 oy',
  'admin.groups.module3': '3 oy',
  'admin.groups.module6': '6 oy',
  'admin.groups.moduleMonthsSuffix': ' · {{n}} oylik modul',
  'admin.groups.endDatePreliminary': 'Tugash sanasi — taxminiy, birinchi darsdan hisoblanadi',
  'admin.groups.addNewStudentToggle': "Guruhga yangi o'quvchi qo'shish",
  'admin.groups.studentWillBeCreated': "O'quvchi yaratiladi va darhol guruhga qo'shiladi",
  'admin.groups.firstNameLabel': 'Ism',
  'admin.groups.lastNameLabel': 'Familiya',
  'admin.groups.phoneLabel': 'Telefon',
  'admin.groups.title': 'Guruhlar',
  'admin.groups.subtitle': 'Filial o\'quv guruhlari',
  'admin.groups.export': 'Eksport',
  'admin.groups.searchPlaceholder': 'Nomi yoki mentor bo\'yicha qidirish…',
  'admin.groups.loadError': 'Yuklashda xatolik: {{message}}',
  'admin.groups.emptySearchTitle': 'Boshqa so\'rovni sinab ko\'ring',
  'admin.groups.emptyTitle': "Guruhlar yo'q",
  'admin.groups.emptyHint': 'Birinchi o\'quv guruhini yarating',
  'admin.groups.create': 'Yaratish',
  'admin.groups.colName': 'Nomi',
  'admin.groups.colMentor': 'Mentor',
  'admin.groups.colStudents': "O'quvchilar",
  'admin.groups.colSchedule': 'Jadval',
  'admin.groups.colStatus': 'Holat',
  'admin.groups.confirmRestore': '«{{name}}» guruhini arxivdan tiklaysizmi?',
  'admin.groups.genericError': 'Xatolik',
  'admin.groups.archiveGroupTitle': 'Guruhni arxivlash',
  'admin.groups.toArchive': 'Arxivga',
  'admin.groups.archiveConfirm': '{{name}} guruhini arxivlamoqchimisiz? O\'quvchilar va tarix saqlanadi, guruh shunchaki faol ro\'yxatdan yashiriladi.',
  'admin.groups.archiveReasonLabel': 'Arxivlash sababi',
  'admin.groups.archiveReasonPlaceholder': 'masalan Guruh yakunlandi, o\'quvchilar ko\'chirildi…',
  'admin.groups.archiveReasonHint': 'Ixtiyoriy, lekin menejerga foydali bo\'ladi',

  /* ─── admin/GroupDetail.jsx ─── */
  'admin.groupDetail.legendPresent': 'Keldi',
  'admin.groupDetail.legendLate': 'Kechikdi',
  'admin.groupDetail.legendAbsent': 'Kelmadi',
  'admin.groupDetail.legendUnmarked': 'Belgilanmagan',
  'admin.groupDetail.legendCorrected': 'Admin tomonidan tuzatilgan',
  'admin.groupDetail.saving': 'Saqlanmoqda...',
  'admin.groupDetail.saved': 'Saqlandi',
  'admin.groupDetail.saveErrorRetry': 'Saqlanmadi — qayta urinish',
  'admin.groupDetail.prevPage': 'Oldingi sahifa',
  'admin.groupDetail.nextPage': 'Keyingi sahifa',
  'admin.groupDetail.noStudentsInGroup': 'Bu guruhda o\'quvchilar yo\'q',
  'admin.groupDetail.colStudent': 'O\'quvchi',
  'admin.groupDetail.colTotal': 'Jami',
  'admin.groupDetail.futureLessonTooltip': 'Kelajakdagi dars — belgilab bo\'lmaydi',
  'admin.groupDetail.correctedByAdminTooltip': 'Administrator tomonidan tuzatilgan',
  'admin.groupDetail.debtLabel': 'Qarz: {{amount}} so\'m',
  'admin.groupDetail.homeworkCount': 'Uy vazifalari ({{count}})',
  'admin.groupDetail.searchPlaceholder': 'Qidirish...',
  'admin.groupDetail.add': 'Qo\'shish',
  'admin.groupDetail.filterAll': 'Barchasi',
  'admin.groupDetail.hwStatusActive': 'Faol',
  'admin.groupDetail.hwStatusCompleted': 'Bajarilgan',
  'admin.groupDetail.hwStatusOverdue': 'Muddati o\'tgan',
  'admin.groupDetail.noHomeworkYet': 'Hozircha vazifalar yo\'q',
  'admin.groupDetail.nothingFound': 'Hech narsa topilmadi',
  'admin.groupDetail.dueDateLabel': 'Muddat: {{date}}',
  'admin.groupDetail.submissionsCount': '{{submitted}} / {{total}} topshirdi',
  'admin.groupDetail.addHomeworkTitle': 'Vazifa qo\'shish',
  'admin.groupDetail.cancel': 'Bekor qilish',
  'admin.groupDetail.titlePlaceholder': 'Sarlavha',
  'admin.groupDetail.descriptionOptionalPlaceholder': 'Tavsif (ixtiyoriy)',
  'admin.groupDetail.filterStudent': 'O\'quvchi',
  'admin.groupDetail.filterMentor': 'Mentor',
  'admin.groupDetail.noFeedbackYet': 'Hozircha sharhlar yo\'q',
  'admin.groupDetail.anonymous': 'Anonim',
  'admin.groupDetail.studentInitial': 'O',
  'admin.groupDetail.mentorInitial': 'M',
  'admin.groupDetail.addFeedbackTitle': 'Sharh qo\'shish',
  'admin.groupDetail.send': 'Yuborish',
  'admin.groupDetail.authorNamePlaceholder': 'Muallif ismi',
  'admin.groupDetail.feedbackTextPlaceholder': 'Sharh matni...',
  'admin.groupDetail.ratingLabel': 'Baho',
  'admin.groupDetail.tabAttendance': 'Davomat',
  'admin.groupDetail.tabHomework': 'Uy vazifalari',
  'admin.groupDetail.tabFeedback': 'Sharhlar',
  'admin.groupDetail.backToGroups': 'Guruhlarga',
  'admin.groupDetail.groupFallback': 'Guruh',
  'admin.groupDetail.archivedBadge': 'Arxiv',
  'admin.groupDetail.mentorSubtitle': 'Mentor: {{name}}',
  'admin.groupDetail.edit': 'Tahrirlash',
  'admin.groupDetail.restoreFromArchive': 'Arxivdan qaytarish',
  'admin.groupDetail.archive': 'Arxivlash',
  'admin.groupDetail.credentialsTooltip': 'Guruhdagi har bir o\'quvchining QR-kodi, login va paroli bilan PDF',
  'admin.groupDetail.groupPasswords': 'Guruh parollari',
  'admin.groupDetail.metaStudents': 'O\'quvchilar',
  'admin.groupDetail.metaDirection': 'Yo\'nalish',
  'admin.groupDetail.metaRoom': 'Xona',
  'admin.groupDetail.roomNotAssigned': 'Tayinlanmagan',
  'admin.groupDetail.metaSchedule': 'Jadval',
  'admin.groupDetail.metaPricePerMonth': 'Oylik to\'lov',
  'admin.groupDetail.metaTotalDebt': 'Umumiy qarz',
  'admin.groupDetail.tgParentGroupTitle': 'Ota-onalar Telegram-guruhi',
  'admin.groupDetail.tgConnected': 'Ulangan: {{title}}',
  'admin.groupDetail.tgDefaultGroupName': 'Telegram guruhi',
  'admin.groupDetail.tgConnectHint': 'Aynan shu o\'quv guruhiga alohida ota-onalar guruhini ulang.',
  'admin.groupDetail.tgUnlink': 'Uzish',
  'admin.groupDetail.tgGetCode': 'Kod olish',
  'admin.groupDetail.tgStep1': 'Ota-onalar guruhini yarating va botni qo\'shing',
  'admin.groupDetail.tgStep2': 'Shu Telegram-guruhida quyidagi buyruqni yuboring:',
  'admin.groupDetail.tgCopy': 'nusxalash',
  'admin.groupDetail.tgUnlinkConfirm': 'Ota-onalar Telegram-guruhini uzasizmi?',
  'admin.groupDetail.removeStudentConfirm': 'O\'quvchini guruhdan chiqarasizmi?',
  'admin.groupDetail.restoreFromArchiveConfirm': 'Guruhni arxivdan qaytarasizmi?',
  'admin.groupDetail.archiveConfirm': 'Guruhni arxivlaysizmi? Ma\'lumotlar va jadval saqlanadi.',
  'admin.groupDetail.genericError': 'Xatolik',
  'admin.groupDetail.pdfGenericError': 'PDF tayyorlab bo\'lmadi',
  'admin.groupDetail.groupTitleLoading': 'Guruh',
  'admin.groupDetail.loadError': 'Xatolik: {{message}}',
  'admin.groupDetail.addStudentTitle': 'O\'quvchi qo\'shish',
  'admin.groupDetail.selectStudentOption': 'O\'quvchini tanlang...',
};

export default uz;
