const uz = {
  // nav
  'nav.dashboard': 'Boshqaruv',
  'nav.income': 'Daromad',
  'nav.expenses': 'Xarajatlar',
  'nav.salaries': 'Maoshlar',
  'nav.reports': 'Hisobotlar',
  'nav.report': 'Hisobot',
  'nav.admins': 'Xodimlar',
  'nav.finance': 'Moliya',
  'nav.analytics': 'Analitika',
  'nav.stats': 'Statistika',
  'nav.allStudents': "Barcha o'quvchilar",
  'nav.allGroups': 'Barcha guruhlar',
  'nav.attendance': 'Davomat',
  'nav.more': 'Yana',
  'nav.discipline': 'Intizom',
  'nav.announcements': "E'lonlar",
  'nav.reminders': 'Eslatmalar',
  'nav.audit': 'Audit',
  'nav.settings': 'Sozlamalar',
  'nav.students': "O'quvchilar",
  'nav.groups': 'Guruhlar',
  'nav.mentors': 'Mentorlar',
  'nav.chat': 'Chat',
  'nav.payments': "To'lovlar",
  'nav.branch': 'Filial',
  'nav.branches': 'Filiallar',
  'nav.allBranches': 'Barcha filiallar',
  'nav.noBranches': 'Filiallar yo\'q',
  'nav.noGroups': 'Guruhlar yo\'q',
  'nav.methodistTypes': "Ta'lim turlari",
  'nav.tax': 'Soliqlar',
  'nav.main': 'asosiy',
  'nav.collapse': 'Yig\'ish',
  'nav.pin': 'Qotirish',
  'nav.collapsePanel': 'Panelni yig\'ish',
  'nav.pinPanel': 'Panelni qotirish',

  // common
  'common.total': 'Jami',
  'common.amount': 'Summa',
  'common.search': 'Qidiruv',
  'common.profile': 'Profil',
  'common.logout': 'Chiqish',
  'common.myProfile': 'Mening profilim',
  'common.exit': 'Chiqish',

  // roles
  'role.seo': 'SEO',
  'role.admin': 'Administrator',
  'role.branch_manager': 'Boshqaruvchi',
  'role.finance_manager': 'Moliya Menejeri',
  'role.mentor': 'Mentor',
  'role.methodist': 'Metodist',
};

export default uz;
