const uz = {
  // nav
  'nav.dashboard': 'Boshqaruv',
  'nav.income': 'Daromad',
  'nav.expenses': 'Xarajatlar',
  'nav.salaries': 'Maoshlar',
  'nav.reports': 'Hisobotlar',
  'nav.report': 'Hisobot',
  'nav.admins': 'Xodimlar',
  'nav.finance': 'Moliya',
  'nav.analytics': 'Analitika',
  'nav.stats': 'Statistika',
  'nav.tax': 'Soliqlar',
  'nav.taxNdss': 'QQS 20%',
  'nav.taxSocNalog': 'Ijtimoiy soliq 10%',
  'nav.taxOtzyvnoyNalog': 'Aylanma soliq 1.5%',
  'nav.taxTotal': 'Jami soliqlar',
  'nav.taxOrg': 'Tashkilot',
  'nav.allStudents': "Barcha o'quvchilar",
  'nav.allGroups': 'Barcha guruhlar',
  'nav.attendance': 'Davomat',
  'nav.more': 'Yana',
  'nav.discipline': 'Intizom',
  'nav.announcements': "E'lonlar",
  'nav.reminders': 'Eslatmalar',
  'nav.audit': 'Audit',
  'nav.features': 'Imkoniyatlar',
  'nav.billing': "To'lovlar",
  'nav.methodics': 'Metodikalar',
  'nav.shopCatalog': "Do'kon katalogi",
  'nav.settings': 'Sozlamalar',
  'nav.students': "O'quvchilar",
  'nav.groups': 'Guruhlar',
  'nav.mentors': 'Mentorlar',
  'nav.chat': 'Chat',
  'nav.payments': "To'lovlar",
  'nav.branch': 'Filial',
  'nav.branches': 'Filiallar',
  'nav.allBranches': 'Barcha filiallar',
  'nav.noBranches': "Filiallar yo'q",
  'nav.noGroups': "Guruhlar yo'q",
  'nav.methodistTypes': "Ta'lim turlari",
  'nav.people': "Odamlar va mijozlar",
  'nav.clientBase': 'Mijozlar bazasi',
  'nav.myStudents': "Mening o'quvchilarim",
  'nav.participantBase': 'Ishtirokchilar bazasi',
  'nav.schedule': 'Jadval',
  'nav.main': 'asosiy',
  'nav.collapse': "Yig'ish",
  'nav.pin': 'Qotirish',
  'nav.collapsePanel': "Panelni yig'ish",
  'nav.pinPanel': 'Panelni qotirish',

  // common
  'common.total': 'Jami',
  'common.amount': 'Summa',
  'common.search': 'Qidiruv...',
  'common.profile': 'Profil',
  'common.logout': 'Chiqish',
  'common.myProfile': 'Mening profilim',
  'common.exit': 'Chiqish',
  'common.branch': 'Filial',
  'common.allBranches': 'Barcha filiallar',
  'common.status': 'Holat',
  'common.actions': 'Amallar',
  'common.date': 'Sana',
  'common.time': 'Vaqt',
  'common.phone': 'Telefon',
  'common.email': 'Email',
  'common.name': 'Nomi',
  'common.fullName': "To'liq ismi",
  'common.save': 'Saqlash',
  'common.cancel': 'Bekor qilish',
  'common.delete': "O'chirish",
  'common.edit': 'Tahrirlash',
  'common.add': "Qo'shish",
  'common.create': 'Yaratish',
  'common.details': 'Batafsil',
  'common.view': "Ko'rish",
  'common.back': 'Orqaga',
  'common.next': 'Keyingisi',
  'common.loading': 'Yuklanmoqda...',
  'common.error': 'Xatolik yuz berdi',
  'common.success': 'Muvaffaqiyatli',
  'common.filter': 'Filtr',
  'common.all': 'Barchasi',
  'common.active': 'Faol',
  'common.inactive': 'Nofaol',
  'common.frozen': 'Muzlatilgan',
  'common.archived': 'Arxivlangan',
  'common.export': 'Eksport',
  'common.download': 'Yuklab olish',
  'common.upload': 'Yuklash',
  'common.close': 'Yopish',
  'common.confirm': 'Tasdiqlash',
  'common.yes': 'Ha',
  'common.no': "Yo'q",
  'common.empty': "Ma'lumot topilmadi",
  'common.reload': 'Qayta yuklash',
  'common.month': 'Oy',
  'common.period': 'Davr',
  'common.notes': 'Izohlar',
  'common.description': 'Tavsif',
  'common.accountMenu': 'Hisob menyusi',
  'common.yesterday': 'Kecha',

  // roles
  'role.seo': 'SEO (Rahbar)',
  'role.admin': 'Administrator',
  'role.branch_manager': 'Filial Boshqaruvchisi',
  'role.finance_manager': 'Moliya Menejeri',
  'role.mentor': 'Mentor',
  'role.methodist': 'Metodist',
  'role.student': "O'quvchi",
  'role.parent': 'Ota-ona',
  'role.employee': 'Xodim',

  // notifications
  'notifications.title': 'Bildirishnomalar',
  'notifications.empty': "Yangi bildirishnomalar yo'q",
  'notifications.emptyDesc': "O'qilmagan xabarlar shu yerda paydo bo'ladi.",
  'notifications.new': 'yangi',
  'notifications.allMessages': 'Barcha xabarlar',
  'notifications.newMessage': 'Yangi xabar',
  'notifications.soundOn': 'Ovoz yoqilgan',
  'notifications.soundOff': "Ovoz o'chirilgan",
  'notifications.muteSound': "Ovozni o'chirish",
  'notifications.unmuteSound': 'Ovozni yoqish',

  // kpi & dashboard
  'kpi.income': 'Oylik daromad',
  'kpi.expenses': 'Oylik xarajat',
  'kpi.salaries': 'Oylik maoshlar',
  'kpi.profit': 'Sof foyda',
  'kpi.netProfit': 'Sof foyda',
  'kpi.orgIncome': 'Tashkilot daromadi',
  'kpi.orgExpenses': 'Tashkilot xarajati',
  'kpi.orgProfit': 'Tashkilot foydasi',
  'kpi.students': "O'quvchilar soni",
  'kpi.groups': 'Guruhlar soni',
  'kpi.mentors': 'Mentorlar soni',
  'kpi.debt': 'Qarzdorlik',
  'kpi.attendance': "O'rtacha davomat",

  // dashboard details
  'dash.branchStats': 'Filial ko‘rsatkichlari',
  'dash.activeStudents': 'Faol o‘quvchilar',
  'dash.groups': 'Guruhlar',
  'dash.overdueInvoices': 'Muddati o‘tgan hisoblar',
  'dash.recentPayments': 'So‘nggi to‘lovlar',
  'dash.noPayments': 'Hozircha to‘lovlar yo‘q',
  'dash.student': 'O‘quvchi',
  'dash.reminders': 'Eslatmalar',
  'dash.overduePaymentsTitle': 'Muddati o‘tgan to‘lovlar',
  'dash.overduePaymentsDesc': 'Ayni paytda {{count}} ta hisob muddati o‘tgan. To‘lovlarni nazorat qiling.',
  'dash.activeStudentsTitle': 'Faol o‘quvchilar',
  'dash.activeStudentsDesc': 'Filialda {{count}} ta faol o‘quvchi ta’lim olmoqda.',
  'dash.thisMonth': 'Shu oy uchun',
  'dash.income': 'Daromad',
  'dash.expenses': 'Xarajat',
  'dash.profit': 'Foyda',
  'dash.loadError': 'Yuklashda xatolik',
  'dash.title': 'Boshqaruv paneli',
  'dash.welcome': 'Xush kelibsiz',
  'dash.bmSubtitle': 'filialning umumiy holati',
  'dash.incomeThisMonth': 'Shu oy daromadi',
  'dash.expensesThisMonth': 'Shu oy xarajati',
  'dash.debtDesc': 'muddati o‘tgan to‘lovlar',
  'dash.profitFormula': 'daromad − xarajat',
  'dash.vsPrevMonth': 'o‘tgan oyga nisbatan',
  'dash.mainBranch': 'Asosiy filial',
  'dash.addressNotSet': 'Manzil ko‘rsatilmagan',
  'dash.phoneNotSet': 'Telefon ko‘rsatilmagan',
  'dash.workHoursNotSet': 'Ish vaqti ko‘rsatilmagan',
  'dash.staff': 'Xodimlar',
  'dash.recentBranchPayments': 'So‘nggi to‘lovlar',
  'dash.noPaymentsYet': 'Hozircha to‘lovlar yo‘q',
  'dash.last6Months': 'So‘nggi 6 oy: daromad vs xarajat',

  // branch details
  'branch.about': 'Filial haqida',
  'branch.locationStats': 'joylashuv va statistika',
  'branch.contacts': 'Kontaktlar',
  'branch.address': 'Manzil',
  'branch.phone': 'Telefon',
  'branch.financeTotal': 'Moliya (jami)',
  'branch.tgCardTitle': 'Ota-onalar guruhi (Telegram)',
  'branch.tgConnected': 'Guruh ulangan',
  'branch.tgDisconnect': 'O‘chirish',
  'branch.tgDesc': 'Davomat va o‘zlashtirish haqidagi xabarlar avtomatik ushbu guruhga yuboriladi. Avval botni guruhga qo‘shing, so‘ng ulash kodini oling.',
  'branch.tgGetCode': 'Ulash kodini olish',
  'branch.tgStep1': 'Botni guruhga qo‘shing',
  'branch.tgStep2': 'Quyidagi buyruqni guruhga yuboring',
  'branch.tgCodeValid': 'Kod {{min}} daqiqa davomida amal qiladi.',
  'branch.notFound': 'Filial ma’lumotlari topilmadi',
  'branch.unlinkConfirm': 'Haqiqatan ham guruhni uzmoqchimisiz?',

  // tax
  'tax.title': 'Soliq hisoboti',
  'tax.subtitle': 'Filiallar va tashkilot bo‘yicha soliq hisoblari',
  'tax.export': 'CSV eksport',
  'tax.due': 'Jami to‘lanishi kerak',
  'tax.tableTitle': 'Filiallar bo‘yicha soliqlar',
  'tax.netProfit': 'Sof foyda',

  // language
  'lang.uz': "O'zbekcha",
  'lang.ru': 'Русский',
  'lang.en': 'English',
  'lang.select': 'Tilni tanlang',

  // ---------- finance-manager panel (avval pages/finance/_i18n.jsx) ----------
  'finance.nav.dashboard': 'Boshqaruv',
  'finance.nav.income': 'Daromad',
  'finance.nav.expenses': 'Xarajatlar',
  'finance.nav.salaries': 'Maoshlar',
  'finance.nav.reports': 'Hisobotlar',
  'finance.nav.report': 'Hisobot',
  'finance.nav.admins': 'Xodimlar',
  'finance.nav.finance': 'Moliya',
  'finance.nav.analytics': 'Analitika',
  'finance.nav.stats': 'Statistika',
  'finance.nav.allStudents': "Barcha o'quvchilar",
  'finance.nav.allGroups': 'Barcha guruhlar',
  'finance.nav.attendance': 'Davomat',
  'finance.nav.more': 'Yana',
  'finance.nav.discipline': 'Intizom',
  'finance.nav.announcements': "E'lonlar",
  'finance.nav.reminders': 'Eslatmalar',
  'finance.nav.audit': 'Audit',
  'finance.nav.settings': 'Sozlamalar',
  'finance.nav.students': "O'quvchilar",
  'finance.nav.groups': 'Guruhlar',
  'finance.nav.mentors': 'Mentorlar',
  'finance.nav.chat': 'Chat',
  'finance.nav.payments': "To'lovlar",
  'finance.nav.branch': 'Filial',
  'finance.nav.branches': 'Filiallar',
  'finance.nav.allBranches': 'Barcha filiallar',
  'finance.nav.noBranches': "Filiallar yo'q",
  'finance.nav.noGroups': "Guruhlar yo'q",
  'finance.nav.methodistTypes': "Ta'lim turlari",
  'finance.nav.main': 'asosiy',
  'finance.nav.collapse': "Yig'ish",
  'finance.nav.pin': 'Qotirish',
  'finance.nav.collapsePanel': "Panelni yig'ish",
  'finance.nav.pinPanel': 'Panelni qotirish',

  'finance.kpi.income': 'Oy daromadi',
  'finance.kpi.expenses': 'Oy xarajati',
  'finance.kpi.salaries': 'Oy maoshi',
  'finance.kpi.netProfit': 'Sof foyda',
  'finance.kpi.orgIncome': 'Tashkilot daromadi',
  'finance.kpi.orgExpenses': 'Tashkilot xarajati',
  'finance.kpi.orgProfit': 'Tashkilot foydasi',

  'finance.common.total': 'Jami',
  'finance.common.share': 'Ulush',
  'finance.common.amount': 'Summa',
  'finance.common.date': 'Sana',
  'finance.common.status': 'Holat',
  'finance.common.method': 'Usul',
  'finance.common.note': 'Izoh',
  'finance.common.category': 'Kategoriya',
  'finance.common.employee': 'Xodim',
  'finance.common.position': 'Lavozim',
  'finance.common.branch': 'Filial',
  'finance.common.allBranches': 'Barcha filiallar',
  'finance.common.month': 'Oy',
  'finance.common.period': 'Davr',
  'finance.common.vsPrev': "o'tgan oyga nisbatan",
  'finance.common.noData': "Ma'lumot yo'q",
  'finance.common.students': "O'quvchilar",
  'finance.common.groups': 'Guruhlar',
  'finance.common.staff': 'Xodimlar',
  'finance.common.loading': 'Yuklanmoqda…',
  'finance.common.page': 'Bet',
  'finance.common.save': 'Saqlash',
  'finance.common.cancel': 'Bekor qilish',
  'finance.common.add': "Qo'shish",
  'finance.common.edit': "O'zgartirish",
  'finance.common.delete': "O'chirish",
  'finance.common.confirmDelete': "Bu yozuvni o'chirasizmi?",

  'finance.dash.title': 'Moliyaviy boshqaruv',
  'finance.dash.subtitle': 'Butun tashkilot · filiallar va oylar bo‘yicha',
  'finance.dash.trendChart': 'Tashkilot daromadi va xarajati',
  'finance.dash.profitLine': 'Foyda',
  'finance.dash.branchShare': 'Filiallarning daromaddagi ulushi',
  'finance.dash.monthlyProfit': '6 oylik sof foyda',
  'finance.dash.viewReports': 'Batafsil hisobot',
  'finance.dash.days30Org': "So'nggi 30 kun · butun tashkilot",
  'finance.dash.chartSub': '30 kunlik haqiqiy tushum',
  'finance.dash.branches': 'Filiallar',

  'finance.income.title': 'Daromad',
  'finance.income.subtitle': 'Filiallar va oylar bo‘yicha tushumlar',
  'finance.income.tableTitle': "To'lovlar",
  'finance.income.student': "O'quvchi",
  'finance.income.group': 'Guruh',

  'finance.expenses.title': 'Xarajatlar',
  'finance.expenses.subtitle': "Filiallar va kategoriyalar bo'yicha xarajatlar",
  'finance.expenses.catBreakdown': 'Kategoriyalar bo‘yicha',
  'finance.expenses.add': 'Yangi xarajat',
  'finance.expenses.edit': "Xarajatni o'zgartirish",
  'finance.expenses.orgWide': 'Butun tashkilot uchun',
  'finance.expenses.categoryPlaceholder': 'Masalan: Ijara',

  'finance.salaries.title': 'Maoshlar',
  'finance.salaries.subtitle': "Filiallar bo'yicha ish haqi fondi",
  'finance.salaries.payroll': 'Oy uchun IHF',
  'finance.salaries.sheetTitle': 'Vedomost',

  'finance.reports.title': 'Hisobotlar',
  'finance.reports.subtitle': 'Bir oylik filiallar bo‘yicha xulosa',
  'finance.reports.org': 'Tashkilot',
  'finance.reports.cashFlow': 'Pul oqimi',
  'finance.reports.branchTable': 'Filiallar · xulosa',
  'finance.reports.branchNet': 'Filiallar bo‘yicha sof',
  'finance.reports.branchDetail': 'Filiallar bo‘yicha tafsilot',
  'finance.reports.net': 'Sof foyda',
  'finance.reports.opProfit': 'Operatsion foyda',
  'finance.reports.vsPrevMonth': "o'tgan oyga nisbatan",
  'finance.reports.export': 'CSV eksport',
  'finance.reports.paymentsThisMonth': "To'lovlar · shu oy",
  'finance.reports.byStatus': "To'lov holati bo'yicha",
  'finance.reports.byMethod': "To'lov usuli bo'yicha",
  'finance.reports.overdueAmount': "Muddati o'tgan",
  'finance.reports.expensesByCategory': "Xarajatlar toifalar bo'yicha",
  'finance.reports.subtitleLive': "Haqiqiy backend ma'lumotlari · so'nggi 30 kun",
  'finance.reports.incomeLabel': "30 kunlik tushum",
  'finance.reports.activeStudents': "Faol o'quvchilar",
  'finance.reports.last30days': "So'nggi 30 kun",
  'finance.reports.debtLabel': 'Qarz',
  'finance.reports.incomeDebtByBranch': 'Filiallar bo‘yicha tushum va qarzlar',
  'finance.reports.methodsSubtitle': 'Yakunlangan tranzaksiyalar',
  'finance.reports.noCompletedPayments': "Yakunlangan to'lovlar yo'q",
  'finance.reports.orgRow': 'TASHKILOT',
  'finance.method.cash': 'Naqd',
  'finance.method.card': 'Karta',
  'finance.method.transfer': "O'tkazma",
  'finance.method.bankTransfer': 'Bank o‘tkazmasi',
  'finance.salaryStatus.draft': 'Qoralama',
  'finance.salaryStatus.approved': 'Tasdiqlangan',
  'finance.salaryStatus.paid': "To'langan",

  'finance.settings.title': 'Sozlamalar',
  'finance.settings.subtitle': 'Profil va afzalliklar',
  'finance.settings.personal': "Shaxsiy ma'lumotlar",
  'finance.settings.personalSub': "Bu ma'lumotlar tizimda ko'rinadi va profilingizga saqlanadi",
  'finance.settings.firstName': 'Ism',
  'finance.settings.lastName': 'Familiya',
  'finance.settings.phone': 'Telefon',
  'finance.settings.city': 'Shahar',
  'finance.settings.email': 'Email',
  'finance.settings.save': 'Saqlash',
  'finance.settings.saved': 'Sozlamalar saqlandi',
  'finance.settings.lang': 'Interfeys tili',
  'finance.settings.langSub': 'Darhol qo‘llaniladi, butun panel uchun',
  'finance.settings.security': 'Xavfsizlik',
  'finance.settings.securitySub': "Parolni o'zgartirish va hisob ma'lumotlari asosiy hisob orqali boshqariladi",
};

export default uz;
